#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

//GO(pango_cairo_context_get_font_options, 
//GO(pango_cairo_context_get_resolution, 
//GO(pango_cairo_context_get_shape_renderer, 
//GO(pango_cairo_context_set_font_options, 
//GO(pango_cairo_context_set_resolution, 
//GO(pango_cairo_context_set_shape_renderer, 
//GO(pango_cairo_create_context, 
//GO(pango_cairo_create_layout, 
//GO(pango_cairo_error_underline_path, 
//GO(pango_cairo_fc_font_get_type, 
//GO(pango_cairo_fc_font_map_get_type, 
//GO(pango_cairo_font_get_scaled_font, 
//GO(pango_cairo_font_get_type, 
//GO(pango_cairo_font_map_create_context, 
//GO(pango_cairo_font_map_get_default, 
//GO(pango_cairo_font_map_get_font_type, 
//GO(pango_cairo_font_map_get_resolution, 
//GO(pango_cairo_font_map_get_type, 
//GO(pango_cairo_font_map_new, 
//GO(pango_cairo_font_map_new_for_font_type, 
//GO(pango_cairo_font_map_set_default, 
//GO(pango_cairo_font_map_set_resolution, 
//GO(pango_cairo_glyph_string_path, 
//GO(pango_cairo_layout_line_path, 
//GO(pango_cairo_layout_path, 
//GO(pango_cairo_renderer_get_type, 
//GO(pango_cairo_show_error_underline, 
//GO(pango_cairo_show_glyph_item, 
//GO(pango_cairo_show_glyph_string, 
//GO(pango_cairo_show_layout, 
//GO(pango_cairo_show_layout_line, 
//GO(pango_cairo_update_context, 
//GO(pango_cairo_update_layout, 
