#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

GOS(xcb_shm_attach, pFEppuuC)
GOS(xcb_shm_attach_checked, pFEppuuC)
GOS(xcb_shm_attach_fd, pFEppuuC)
GOS(xcb_shm_attach_fd_checked, pFEppuuC)
GOS(xcb_shm_create_pixmap, pFEppuuWWCuu)
GOS(xcb_shm_create_pixmap_checked, pFEppuuWWCuu)
GOS(xcb_shm_create_segment, pFEppuuC)
GO(xcb_shm_create_segment_reply, pFpup)
GO(xcb_shm_create_segment_reply_fds, pFpp)
GOS(xcb_shm_create_segment_unchecked, pFEppuuC)
GOS(xcb_shm_detach, pFEppu)
GOS(xcb_shm_detach_checked, pFEppu)
GOS(xcb_shm_get_image, pFEppuwwWWuCuu)
GO(xcb_shm_get_image_reply, pFpup)
GOS(xcb_shm_get_image_unchecked, pFEppuwwWWuCuu)
DATA(xcb_shm_id, 8)
GOS(xcb_shm_put_image, pFEppuuWWWWWWwwCCCuu)
GOS(xcb_shm_put_image_checked, pFEppuuWWWWWWwwCCCuu)
GOS(xcb_shm_query_version, pFEpp)
GO(xcb_shm_query_version_reply, pFpup)
GOS(xcb_shm_query_version_unchecked, pFEpp)
GOS(xcb_shm_seg_end, pFEppii)   // xcb_generic_iterator _t by value, so "pii"
GO(xcb_shm_seg_next, vFp)