#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh....
#endif

//GO(XAllowDeviceEvents, 
//GO(XChangeDeviceControl, 
//GO(XChangeDeviceDontPropagateList, 
//GO(XChangeDeviceKeyMapping, 
//GO(XChangeDeviceProperty, 
//GO(XChangeFeedbackControl, 
//GO(XChangeKeyboardDevice, 
//GO(XChangePointerDevice, 
//GO(XCloseDevice, 
//GO(XDeleteDeviceProperty, 
//GO(XDeviceBell, 
//GO(XFreeDeviceControl, 
//GO(XFreeDeviceList, 
//GO(XFreeDeviceMotionEvents, 
//GO(XFreeDeviceState, 
//GO(XFreeFeedbackList, 
//GO(XGetDeviceButtonMapping, 
//GO(XGetDeviceControl, 
//GO(XGetDeviceDontPropagateList, 
//GO(XGetDeviceFocus, 
//GO(XGetDeviceKeyMapping, 
//GO(XGetDeviceModifierMapping, 
//GO(XGetDeviceMotionEvents, 
//GO(XGetDeviceProperty, 
//GO(XGetExtensionVersion, 
//GO(XGetFeedbackControl, 
//GO(XGetSelectedExtensionEvents, 
//GO(XGrabDevice, 
//GO(XGrabDeviceButton, 
//GO(XGrabDeviceKey, 
//GO(XIAllowEvents, 
//GO(XIAllowTouchEvents, 
//GO(XIBarrierReleasePointer, 
//GO(XIBarrierReleasePointers, 
//GO(XIChangeHierarchy, 
//GO(XIChangeProperty, 
//GO(XIDefineCursor, 
//GO(XIDeleteProperty, 
GO(XIFreeDeviceInfo, vFp)
//GO(XIGetClientPointer, 
//GO(XIGetFocus, 
//GO(XIGetProperty, 
GO(XIGetSelectedEvents, iFpppi)
//GO(XIGrabButton, 
//GO(XIGrabDevice, 
//GO(XIGrabEnter, 
//GO(XIGrabFocusIn, 
//GO(XIGrabKeycode, 
//GO(XIGrabTouchBegin, 
//GO(XIListProperties, 
GO(XIQueryDevice, pFpip)
GO(XIQueryPointer, iFpipppppppppp)
GO(XIQueryVersion, iFppp)
GO(XISelectEvents, iFpppi)
//GO(XISetClientPointer, 
//GO(XISetFocus, 
//GO(XIUndefineCursor, 
//GO(XIUngrabButton, 
//GO(XIUngrabDevice, 
//GO(XIUngrabEnter, 
//GO(XIUngrabFocusIn, 
//GO(XIUngrabKeycode, 
//GO(XIUngrabTouchBegin, 
//GO(XIWarpPointer, 
//GO(XListDeviceProperties, 
//GO(XListInputDevices, 
//GO(XOpenDevice, 
//GO(XQueryDeviceState, 
//GO(XSelectExtensionEvent, 
//GO(XSendExtensionEvent, 
//GO(XSetDeviceButtonMapping, 
//GO(XSetDeviceFocus, 
//GO(XSetDeviceMode, 
//GO(XSetDeviceModifierMapping, 
//GO(XSetDeviceValuators, 
//GO(XUngrabDevice, 
//GO(XUngrabDeviceButton, 
//GO(XUngrabDeviceKey, 
//GO(_XiGetDevicePresenceNotifyEvent, 
//GO(_xibadclass, 
//GO(_xibaddevice, 
//GO(_xibadevent, 
//GO(_xibadmode, 
//GO(_xidevicebusy, 
