#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

//%S x my_xcb_cookie_t u

//GOS(xcb_xfixes_barrier_end, 
//GOS(xcb_xfixes_barrier_next, 
//GOS(xcb_xfixes_change_cursor, 
//GOS(xcb_xfixes_change_cursor_by_name, 
//GOS(xcb_xfixes_change_cursor_by_name_checked, 
//GOS(xcb_xfixes_change_cursor_by_name_name, 
//GOS(xcb_xfixes_change_cursor_by_name_name_end, 
//GOS(xcb_xfixes_change_cursor_by_name_name_length, 
//GOS(xcb_xfixes_change_cursor_by_name_sizeof, 
//GOS(xcb_xfixes_change_cursor_checked, 
//GOS(xcb_xfixes_change_save_set, 
//GOS(xcb_xfixes_change_save_set_checked, 
//GOS(xcb_xfixes_copy_region, 
//GOS(xcb_xfixes_copy_region_checked, 
//GOS(xcb_xfixes_create_pointer_barrier, 
//GOS(xcb_xfixes_create_pointer_barrier_checked, 
//GOS(xcb_xfixes_create_pointer_barrier_devices, 
//GOS(xcb_xfixes_create_pointer_barrier_devices_end, 
//GOS(xcb_xfixes_create_pointer_barrier_devices_length, 
//GOS(xcb_xfixes_create_pointer_barrier_sizeof, 
GOS(xcb_xfixes_create_region, xFEpuup)
//GOS(xcb_xfixes_create_region_checked, 
//GOS(xcb_xfixes_create_region_from_bitmap, 
//GOS(xcb_xfixes_create_region_from_bitmap_checked, 
//GOS(xcb_xfixes_create_region_from_gc, 
//GOS(xcb_xfixes_create_region_from_gc_checked, 
//GOS(xcb_xfixes_create_region_from_picture, 
//GOS(xcb_xfixes_create_region_from_picture_checked, 
//GOS(xcb_xfixes_create_region_from_window, 
//GOS(xcb_xfixes_create_region_from_window_checked, 
//GOS(xcb_xfixes_create_region_rectangles, 
//GOS(xcb_xfixes_create_region_rectangles_iterator, 
//GOS(xcb_xfixes_create_region_rectangles_length, 
//GOS(xcb_xfixes_create_region_sizeof, 
//GOS(xcb_xfixes_delete_pointer_barrier, 
//GOS(xcb_xfixes_delete_pointer_barrier_checked, 
GOS(xcb_xfixes_destroy_region, xFEpu)
//GOS(xcb_xfixes_destroy_region_checked, 
//GOS(xcb_xfixes_expand_region, 
//GOS(xcb_xfixes_expand_region_checked, 
//GOS(xcb_xfixes_fetch_region, 
//GOS(xcb_xfixes_fetch_region_rectangles, 
//GOS(xcb_xfixes_fetch_region_rectangles_iterator, 
//GOS(xcb_xfixes_fetch_region_rectangles_length, 
//GOS(xcb_xfixes_fetch_region_reply, 
//GOS(xcb_xfixes_fetch_region_sizeof, 
//GOS(xcb_xfixes_fetch_region_unchecked, 
//GOS(xcb_xfixes_get_cursor_image, 
//GOS(xcb_xfixes_get_cursor_image_and_name, 
//GOS(xcb_xfixes_get_cursor_image_and_name_cursor_image, 
//GOS(xcb_xfixes_get_cursor_image_and_name_cursor_image_end, 
//GOS(xcb_xfixes_get_cursor_image_and_name_cursor_image_length, 
//GOS(xcb_xfixes_get_cursor_image_and_name_name, 
//GOS(xcb_xfixes_get_cursor_image_and_name_name_end, 
//GOS(xcb_xfixes_get_cursor_image_and_name_name_length, 
//GOS(xcb_xfixes_get_cursor_image_and_name_reply, 
//GOS(xcb_xfixes_get_cursor_image_and_name_sizeof, 
//GOS(xcb_xfixes_get_cursor_image_and_name_unchecked, 
//GOS(xcb_xfixes_get_cursor_image_cursor_image, 
//GOS(xcb_xfixes_get_cursor_image_cursor_image_end, 
//GOS(xcb_xfixes_get_cursor_image_cursor_image_length, 
//GOS(xcb_xfixes_get_cursor_image_reply, 
//GOS(xcb_xfixes_get_cursor_image_sizeof, 
//GOS(xcb_xfixes_get_cursor_image_unchecked, 
//GOS(xcb_xfixes_get_cursor_name, 
//GOS(xcb_xfixes_get_cursor_name_name, 
//GOS(xcb_xfixes_get_cursor_name_name_end, 
//GOS(xcb_xfixes_get_cursor_name_name_length, 
//GOS(xcb_xfixes_get_cursor_name_reply, 
//GOS(xcb_xfixes_get_cursor_name_sizeof, 
//GOS(xcb_xfixes_get_cursor_name_unchecked, 
//GOS(xcb_xfixes_hide_cursor, 
//GOS(xcb_xfixes_hide_cursor_checked, 
DATA(xcb_xfixes_id, 8)
//GOS(xcb_xfixes_intersect_region, 
//GOS(xcb_xfixes_intersect_region_checked, 
//GOS(xcb_xfixes_invert_region, 
//GOS(xcb_xfixes_invert_region_checked, 
//GOS(xcb_xfixes_query_version, 
GO(xcb_xfixes_query_version_reply, pFpup)
GOS(xcb_xfixes_query_version_unchecked, xFEpuu)
//GOS(xcb_xfixes_region_end, 
//GOS(xcb_xfixes_region_extents, 
//GOS(xcb_xfixes_region_extents_checked, 
//GOS(xcb_xfixes_region_next, 
//GOS(xcb_xfixes_select_cursor_input, 
//GOS(xcb_xfixes_select_cursor_input_checked, 
//GOS(xcb_xfixes_select_selection_input, 
//GOS(xcb_xfixes_select_selection_input_checked, 
//GOS(xcb_xfixes_set_cursor_name, 
//GOS(xcb_xfixes_set_cursor_name_checked, 
//GOS(xcb_xfixes_set_cursor_name_name, 
//GOS(xcb_xfixes_set_cursor_name_name_end, 
//GOS(xcb_xfixes_set_cursor_name_name_length, 
//GOS(xcb_xfixes_set_cursor_name_sizeof, 
//GOS(xcb_xfixes_set_gc_clip_region, 
//GOS(xcb_xfixes_set_gc_clip_region_checked, 
//GOS(xcb_xfixes_set_picture_clip_region, 
//GOS(xcb_xfixes_set_picture_clip_region_checked, 
//GOS(xcb_xfixes_set_region, 
//GOS(xcb_xfixes_set_region_checked, 
//GOS(xcb_xfixes_set_region_rectangles, 
//GOS(xcb_xfixes_set_region_rectangles_iterator, 
//GOS(xcb_xfixes_set_region_rectangles_length, 
//GOS(xcb_xfixes_set_region_sizeof, 
GOS(xcb_xfixes_set_window_shape_region, xFEpuuwwu)
GOS(xcb_xfixes_set_window_shape_region_checked, xFEpuuwwu)
//GOS(xcb_xfixes_show_cursor, 
//GOS(xcb_xfixes_show_cursor_checked, 
//GOS(xcb_xfixes_subtract_region, 
//GOS(xcb_xfixes_subtract_region_checked, 
//GOS(xcb_xfixes_translate_region, 
//GOS(xcb_xfixes_translate_region_checked, 
//GOS(xcb_xfixes_union_region, 
//GOS(xcb_xfixes_union_region_checked, 
