#if defined(GO) && defined(GOM) && defined(GO2) && defined(DATA) && defined(END)

DATA(__data_start, 4)
DATA(_edata, 4)
// _fini
// _init
GO(Mix_AllocateChannels, iFi)
// Mix_ChannelFinished
GO(Mix_CloseAudio, vFv)
// Mix_EachSoundFont
// Mix_ExpireChannel
GO(Mix_FadeInChannelTimed, iFipiii)
GO(Mix_FadeInMusic, iFpii)
// Mix_FadeInMusicPos
// Mix_FadeOutChannel
// Mix_FadeOutGroup
// Mix_FadeOutMusic
// Mix_FadingChannel
// Mix_FadingMusic
GO(Mix_FreeChunk, vFp)
GO(Mix_FreeMusic, vFp)
// Mix_GetChunk
// Mix_GetChunkDecoder
// Mix_GetMusicDecoder
// Mix_GetMusicHookData
// Mix_GetMusicType
// Mix_GetNumChunkDecoders
// Mix_GetNumMusicDecoders
// Mix_GetSoundFonts
// Mix_GetSynchroValue
// Mix_GroupAvailable
// Mix_GroupChannel
// Mix_GroupChannels
// Mix_GroupCount
// Mix_GroupNewer
// Mix_GroupOldest
GO(Mix_HaltChannel, iFi)
// Mix_HaltGroup
GO(Mix_HaltMusic, iFv)
// Mix_HasChunkDecoder
// Mix_HookMusic
// Mix_HookMusicFinished
// Mix_Init
// Mix_Linked_Version
GO(Mix_LoadMUS, pFp)
// Mix_LoadMUS_RW
// Mix_LoadMUSType_RW
GO(Mix_LoadWAV_RW, pFpi)
GO(Mix_OpenAudio, iFiWii)
// Mix_OpenAudioDevice
GO(Mix_Pause, vFi)
// Mix_Paused
// Mix_PausedMusic
GO(Mix_PauseMusic, vFv);
GO(Mix_PlayChannelTimed, iFipii)
GO(Mix_Playing, iFi)
GO(Mix_PlayingMusic, iFpi)
GO(Mix_PlayMusic, iFpi)
// Mix_QuerySpec
// Mix_QuickLoad_RAW
// Mix_QuickLoad_WAV
GO(Mix_Quit, vFv)
// Mix_RegisterEffect
GO(Mix_ReserveChannels, iFi)
GO(Mix_Resume, vFi)
// Mix_ResumeMusic
// Mix_RewindMusic
// Mix_SetDistance
// Mix_SetMusicCMD
// Mix_SetMusicPosition
// Mix_SetPanning
// Mix_SetPosition
// Mix_SetPostMix
// Mix_SetReverseStereo
// Mix_SetSoundFonts
// Mix_SetSynchroValue
// Mix_UnregisterAllEffects
// Mix_UnregisterEffect
GO(Mix_Volume, iFii)
// Mix_VolumeChunk
GO(Mix_VolumeMusic, iFi)

END()

#else
#error Mmmm...
#endif