#if defined(GO) && defined(GOM) && defined(GO2) && defined(DATA) && defined(END)

// all those bss stuff are suspicious
//DATAB(__bss_end__, 4)
//DATAB(_bss_end__, 4)
//DATAB(__bss_start, 4)
//DATAB(__bss_start__, 4)
//DATA(__data_start, 4)
//DATA(_edata, 4)
//DATAB(_end, 4)
//DATAB(__end__, 4)
// __exidx_end  // type r
// __exidx_start    // type r
// _fini
// _init
// KeySymToUcs4
DATAB(_qfree, 4)
// _Utf8GetConvByName
// XActivateScreenSaver
// XAddConnectionWatch
// XAddExtension
// XAddHost
// XAddHosts
// XAddPixel
// XAddToExtensionList
// XAddToSaveSet
// XAllocClassHint
// XAllocColor
// XAllocColorCells
// XAllocColorPlanes
// XAllocIconSize
// _XAllocID
// _XAllocIDs
// XAllocNamedColor
// _XAllocScratch
// XAllocSizeHints
// XAllocStandardColormap
// _XAllocTemp
// XAllocWMHints
// XAllowEvents
// XAllPlanes
// _XAsyncErrorHandler
// XAutoRepeatOff
// XAutoRepeatOn
// XBaseFontNameListOfFontSet
// XBell
// XBitmapBitOrder
// XBitmapPad
// XBitmapUnit
// XBlackPixel
// XBlackPixelOfScreen
// XCellsOfScreen
// XChangeActivePointerGrab
// XChangeGC
// XChangeKeyboardControl
// XChangeKeyboardMapping
// XChangePointerControl
GO(XChangeProperty, iFpppi)
// XChangeSaveSet
// XChangeWindowAttributes
// XCheckIfEvent
// XCheckMaskEvent
// XCheckTypedEvent
// XCheckTypedWindowEvent
// XCheckWindowEvent
// XCirculateSubwindows
// XCirculateSubwindowsDown
// XCirculateSubwindowsUp
GO(XClearArea, iFppiiuui)
GO(XClearWindow, iFpp)
// XClipBox
// XCloseDisplay
// XCloseIM
// _XCloseLC
// XCloseOM
// _XcmsAddCmapRec
// XcmsAddColorSpace
// XcmsAddFunctionSet
// XcmsAllocColor
// XcmsAllocNamedColor
// _XcmsArcTangent
// XcmsCCCOfColormap
// XcmsCIELabClipab
// XcmsCIELabClipL
// XcmsCIELabClipLab
DATA(XcmsCIELabColorSpace, 4)
// _XcmsCIELab_prefix   // type r
// XcmsCIELabQueryMaxC
// XcmsCIELabQueryMaxL
// XcmsCIELabQueryMaxLC
// _XcmsCIELabQueryMaxLCRGB
// XcmsCIELabQueryMinL
// XcmsCIELabToCIEXYZ
// XcmsCIELabWhiteShiftColors
// XcmsCIELuvClipL
// XcmsCIELuvClipLuv
// XcmsCIELuvClipuv
DATA(XcmsCIELuvColorSpace, 4)
// _XcmsCIELuv_prefix   // type r
// XcmsCIELuvQueryMaxC
// XcmsCIELuvQueryMaxL
// XcmsCIELuvQueryMaxLC
// _XcmsCIELuvQueryMaxLCRGB
// XcmsCIELuvQueryMinL
// XcmsCIELuvToCIEuvY
// XcmsCIELuvWhiteShiftColors
DATA(XcmsCIEuvYColorSpace, 4)
// _XcmsCIEuvY_prefix   // type r
// XcmsCIEuvYToCIELuv
// XcmsCIEuvYToCIEXYZ
// XcmsCIEuvYToTekHVC
// _XcmsCIEuvY_ValidSpec
DATA(XcmsCIExyYColorSpace, 4)
// _XcmsCIExyY_prefix   // type r
// XcmsCIExyYToCIEXYZ
DATA(XcmsCIEXYZColorSpace, 4)
// _XcmsCIEXYZ_prefix   // type r
// XcmsCIEXYZToCIELab
// XcmsCIEXYZToCIEuvY
// XcmsCIEXYZToCIExyY
// XcmsCIEXYZToRGBi
// _XcmsCIEXYZ_ValidSpec
// XcmsClientWhitePointOfCCC
// XcmsConvertColors
// _XcmsConvertColorsWithWhitePt
// _XcmsCopyCmapRecAndFree
// _XcmsCopyISOLatin1Lowered
// _XcmsCopyPointerArray
// _XcmsCosine
// XcmsCreateCCC
// _XcmsCubeRoot
DATA(_XcmsDDColorSpaces, 4)
DATA(_XcmsDDColorSpacesInit, 4)
// _XcmsDDConvertColors
// XcmsDefaultCCC
// _XcmsDeleteCmapRec
DATA(_XcmsDIColorSpaces, 4)
DATA(_XcmsDIColorSpacesInit, 4)
// _XcmsDIConvertColors
// XcmsDisplayOfCCC
// _XcmsEqualWhitePts
// XcmsFormatOfPrefix
// XcmsFreeCCC
// _XcmsFreeIntensityMaps
// _XcmsFreePointerArray
// _XcmsGetElement
// _XcmsGetIntensityMap
// _XcmsGetProperty
// _XcmsInitDefaultCCCs
// _XcmsInitScrnInfo
DATA(XcmsLinearRGBFunctionSet, 4)
// XcmsLookupColor
// _XcmsLRGB_InitScrnDefault
// XcmsPrefixOfFormat
// _XcmsPushPointerArray
// XcmsQueryBlack
// XcmsQueryBlue
// XcmsQueryColor
// XcmsQueryColors
// XcmsQueryGreen
// XcmsQueryRed
// XcmsQueryWhite
DATA(_XcmsRegColorSpaces, 4)
// _XcmsRegFormatOfPrefix
// _XcmsResolveColor
// _XcmsResolveColorString
DATA(XcmsRGBColorSpace, 4)
DATA(XcmsRGBiColorSpace, 4)
// _XcmsRGBi_prefix // type r
// XcmsRGBiToCIEXYZ
// XcmsRGBiToRGB
// _XcmsRGB_prefix  // type r
// XcmsRGBToRGBi
// _XcmsRGB_to_XColor
DATA(_XcmsSCCFuncSets, 4)
DATA(_XcmsSCCFuncSetsInit, 4)
// XcmsScreenNumberOfCCC
// XcmsScreenWhitePointOfCCC
// XcmsSetCCCOfColormap
// XcmsSetCompressionProc
// _XcmsSetGetColor
// _XcmsSetGetColors
// XcmsSetWhiteAdjustProc
// XcmsSetWhitePoint
// _XcmsSine
// _XcmsSquareRoot
// XcmsStoreColor
// XcmsStoreColors
// _XcmsTekHVC_CheckModify
// XcmsTekHVCClipC
// XcmsTekHVCClipV
// XcmsTekHVCClipVC
DATA(XcmsTekHVCColorSpace, 4)
// _XcmsTekHVC_prefix   // type r
// XcmsTekHVCQueryMaxC
// XcmsTekHVCQueryMaxV
// XcmsTekHVCQueryMaxVC
// _XcmsTekHVCQueryMaxVCRGB
// XcmsTekHVCQueryMaxVSamples
// XcmsTekHVCQueryMinV
// XcmsTekHVCToCIEuvY
// XcmsTekHVCWhiteShiftColors
DATA(XcmsUNDEFINEDColorSpace, 4)
// _XcmsUnresolveColor
// XcmsVisualOfCCC
// _XColor_to_XcmsRGB
// XConfigureWindow
// XConnectionNumber
// _XConnectXCB
// XContextDependentDrawing
// XContextualDrawing
// XConvertCase
// XConvertSelection
// XCopyArea
// XCopyColormapAndFree
// _XCopyEventCookie
// XCopyGC
// XCopyPlane
// _XCopyToArg
// XCreateBitmapFromData
// XCreateColormap
// XCreateFontCursor
// XCreateFontSet
// XCreateGC
// XCreateGlyphCursor
// XCreateIC
// XCreateImage
DATAB(_XCreateMutex_fn, 4)
// XCreateOC
// XCreatePixmap
// XCreatePixmapCursor
// XCreatePixmapFromBitmapData
// XCreateRegion
// XCreateSimpleWindow
// XCreateWindow
DATAB(_Xdebug, 4)
// XDefaultColormap
// XDefaultColormapOfScreen
// XDefaultDepth
// XDefaultDepthOfScreen
// _XDefaultError
// XDefaultGC
// XDefaultGCOfScreen
// _XDefaultIOError
// _XDefaultOpenIM
// _XDefaultOpenOM
// XDefaultRootWindow
// XDefaultScreen
// XDefaultScreenOfDisplay
// XDefaultString
// XDefaultVisual
// XDefaultVisualOfScreen
// _XDefaultWireError
// XDefineCursor
// XDeleteContext
// XDeleteModifiermapEntry
GO(XDeleteProperty, iFppp)
// _XDeq
// _XDeqAsyncHandler
// XDestroyIC
// XDestroyImage
// XDestroyOC
// XDestroyRegion
// XDestroySubwindows
// XDestroyWindow
// XDirectionalDependentDrawing
// XDisableAccessControl
// XDisplayCells
// XDisplayHeight
// XDisplayHeightMM
// XDisplayKeycodes
// XDisplayMotionBufferSize
// XDisplayName
// XDisplayOfIM
// XDisplayOfOM
// XDisplayOfScreen
// XDisplayPlanes
// XDisplayString
// XDisplayWidth
// XDisplayWidthMM
// XDoesBackingStore
// XDoesSaveUnders
// XDrawArc
// XDrawArcs
// XDrawImageString
// XDrawImageString16
// XDrawLine
// XDrawLines
// XDrawPoint
// XDrawPoints
// XDrawRectangle
// XDrawRectangles
// XDrawSegments
// XDrawString
// XDrawString16
// XDrawText
// XDrawText16
// _XEatData
// _XEatDataWords
// XEHeadOfExtensionList
// XEmptyRegion
// XEnableAccessControl
// _XEnq
// XEqualRegion
// _XError
DATAB(_XErrorFunction, 4)
// XESetBeforeFlush
// XESetCloseDisplay
// XESetCopyEventCookie
// XESetCopyGC
// XESetCreateFont
// XESetCreateGC
// XESetError
// XESetErrorString
// XESetEventToWire
// XESetFlushGC
// XESetFreeFont
// XESetFreeGC
// XESetPrintErrorValues
// XESetWireToError
// XESetWireToEvent
// XESetWireToEventCookie
// XEventMaskOfScreen
GO(XEventsQueued, iFpi)
// _XEventsQueued
// _Xevent_to_mask  // type r
// _XEventToWire
// XExtendedMaxRequestSize
// XExtentsOfFontSet
// _XF86BigfontFreeFontMetrics
// _XF86LoadQueryLocaleFont
// XFetchBuffer
// XFetchBytes
// _XFetchEventCookie
// XFetchName
// XFillArc
// XFillArcs
// XFillPolygon
// XFillRectangle
// XFillRectangles
// XFilterEvent
// XFindContext
// XFindOnExtensionList
GO(XFlush, iFp)
// _XFlush
// XFlushGC
// _XFlushGCCache
// XFontsOfFontSet
// XForceScreenSaver
// XFree
// _XFreeAtomTable
// XFreeColormap
// XFreeColors
// XFreeCursor
DATAB(_XFreeDisplayLock_fn, 4)
// _XFreeDisplayStructure
// _XFreeEventCookies
// XFreeEventData
// _XFreeExtData
// XFreeExtensionList
// XFreeFont
// XFreeFontInfo
// XFreeFontNames
// XFreeFontPath
// XFreeFontSet
// XFreeGC
// XFreeModifiermap
DATAB(_XFreeMutex_fn, 4)
// XFreePixmap
// XFreeStringList
// _XFreeTemp
// _XFreeX11XCBStructure
// XGContextFromGC
// XGeometry
// _XGetAsyncData
// _XGetAsyncReply
// XGetAtomName
// XGetAtomNames
// _XGetBitsPerPixel
// XGetClassHint
// XGetCommand
// XGetDefault
// XGetErrorDatabaseText
// XGetErrorText
// XGetEventData
// XGetFontPath
// XGetFontProperty
// XGetGCValues
// XGetGeometry
// _XGetHostname
// XGetIconName
// XGetIconSizes
// XGetICValues
GO(XGetImage, pFppiiuuui)
// XGetIMValues
// XGetInputFocus
// XGetKeyboardControl
// XGetKeyboardMapping
// _XGetLCValues
// XGetModifierMapping
// XGetMotionEvents
// XGetNormalHints
// XGetOCValues
// XGetOMValues
// XGetPixel
// XGetPointerControl
// XGetPointerMapping
// _XGetRequest
// XGetRGBColormaps
// _XGetScanlinePad
// XGetScreenSaver
// XGetSelectionOwner
// XGetSizeHints
// XGetStandardColormap
GO(XGetSubImage, pFppiiuuuipii)
// XGetTextProperty
// XGetTransientForHint
// XGetVisualInfo
// XGetWindowAttributes
// _XGetWindowAttributes
GO(XGetWindowProperty, iFpppiiipppppp)
// XGetWMClientMachine
// XGetWMColormapWindows
// XGetWMHints
// XGetWMIconName
// XGetWMName
// XGetWMNormalHints
// XGetWMProtocols
// XGetWMSizeHints
// XGetZoomHints
DATAB(_Xglobal_lock, 4)
// XGrabButton
// XGrabKey
GO(XGrabKeyboard, iFppuiiu)
GO(XGrabPointer, iFppiuiippu)
// XGrabServer
DATAB(_XHeadOfDisplayList, 4)
// XHeightMMOfScreen
// XHeightOfScreen
DATAB(_Xi18n_lock, 4)
// XIconifyWindow
// XIfEvent
// XImageByteOrder
// _XIMCompileResourceList
// _XimGetCharCode
// _XimGetLocaleCode
// _XimLookupMBText
// _XimLookupUTF8Text
// _XimLookupWCText
// XIMOfIC
// _XimXTransBytesReadable
// _XimXTransClose
// _XimXTransCloseForCloning
// _XimXTransConnect
// _XimXTransDisconnect
// _XimXTransFreeConnInfo
// _XimXTransGetConnectionNumber
// _XimXTransGetHostname
// _XimXTransGetMyAddr
// _XimXTransGetPeerAddr
// _XimXTransIsLocal
// _XimXTransOpenCLTSClient
// _XimXTransOpenCOTSClient
// _XimXTransRead
// _XimXTransReadv
// _XimXTransSetOption
DATA(_XimXTransSocketINET6Funcs, 4)
DATA(_XimXTransSocketINETFuncs, 4)
DATA(_XimXTransSocketLocalFuncs, 4)
DATA(_XimXTransSocketTCPFuncs, 4)
DATA(_XimXTransSocketUNIXFuncs, 4)
// _XimXTransWrite
// _XimXTransWritev
// _XInitDefaultIM
// _XInitDefaultOM
DATAB(_XInitDisplayLock_fn, 4)
// _XInitDynamicIM
// _XInitDynamicOM
// XInitExtension
// XInitImage
// _XInitImageFuncPtrs
// _XInitKeysymDB
// XInitThreads
// XInsertModifiermapEntry
// XInstallColormap
// XInternalConnectionNumbers
GO(XInternAtom, pFppi)
GO(XInternAtoms, uFppiip)
// XIntersectRegion
// _XIOError
DATAB(_XIOErrorFunction, 4)
// _XIsEventCookie
// XkbAddDeviceLedInfo
// XkbAddGeomColor
// XkbAddGeomDoodad
// XkbAddGeomKey
// XkbAddGeomKeyAlias
// XkbAddGeomOutline
// XkbAddGeomOverlay
// XkbAddGeomOverlayKey
// XkbAddGeomOverlayRow
// XkbAddGeomProperty
// XkbAddGeomRow
// XkbAddGeomSection
// XkbAddGeomShape
// XkbAddKeyType
// XkbAllocClientMap
// XkbAllocCompatMap
// XkbAllocControls
// XkbAllocDeviceInfo
// XkbAllocGeomColors
// XkbAllocGeomDoodads
// XkbAllocGeometry
// XkbAllocGeomKeyAliases
// XkbAllocGeomKeys
// XkbAllocGeomOutlines
// XkbAllocGeomOverlayKeys
// XkbAllocGeomOverlayRows
// XkbAllocGeomOverlays
// XkbAllocGeomPoints
// XkbAllocGeomProps
// XkbAllocGeomRows
// XkbAllocGeomSectionDoodads
// XkbAllocGeomSections
// XkbAllocGeomShapes
// XkbAllocIndicatorMaps
// XkbAllocKeyboard
// XkbAllocNames
// XkbAllocServerMap
// XkbApplyCompatMapToKey
// XkbApplyVirtualModChanges
// XkbBell
// XkbBellEvent
// XkbChangeDeviceInfo
// XkbChangeEnabledControls
// XkbChangeKeycodeRange
// XkbChangeMap
// XkbChangeNames
// XkbChangeTypesOfKey
// XkbComputeEffectiveMap
// XkbComputeRowBounds
// XkbComputeSectionBounds
// XkbComputeShapeBounds
// XkbComputeShapeTop
// _XkbCopyFromReadBuffer
// XkbCopyKeyType
// XkbCopyKeyTypes
// XkbDeviceBell
// XkbDeviceBellEvent
// XkbFindOverlayForKey
// XkbForceBell
// XkbForceDeviceBell
// XkbFreeClientMap
// XkbFreeCompatMap
// XkbFreeComponentList
// XkbFreeControls
// XkbFreeDeviceInfo
// XkbFreeGeomColors
// XkbFreeGeomDoodads
// XkbFreeGeometry
// XkbFreeGeomKeyAliases
// XkbFreeGeomKeys
// XkbFreeGeomOutlines
// XkbFreeGeomOverlayKeys
// XkbFreeGeomOverlayRows
// XkbFreeGeomOverlays
// XkbFreeGeomPoints
// XkbFreeGeomProperties
// XkbFreeGeomRows
// XkbFreeGeomSections
// XkbFreeGeomShapes
// XkbFreeIndicatorMaps
// XkbFreeKeyboard
// XkbFreeNames
// _XkbFreeReadBuffer
// XkbFreeServerMap
DATA(_XkbGetAtomNameFunc, 4)
// XkbGetAutoRepeatRate
// XkbGetAutoResetControls
// _XkbGetCharset
// XkbGetCompatMap
// XkbGetControls
// _XkbGetConverters
// XkbGetDetectableAutoRepeat
// XkbGetDeviceButtonActions
// XkbGetDeviceInfo
// XkbGetDeviceInfoChanges
// XkbGetDeviceLedInfo
// XkbGetGeometry
// XkbGetIndicatorMap
// XkbGetIndicatorState
// XkbGetKeyActions
// XkbGetKeyBehaviors
// XkbGetKeyboard
// XkbGetKeyboardByName
// XkbGetKeyExplicitComponents
// XkbGetKeyModifierMap
// XkbGetKeySyms
// XkbGetKeyTypes
// XkbGetKeyVirtualModMap
// XkbGetMap
// XkbGetMapChanges
// XkbGetNamedDeviceIndicator
// XkbGetNamedGeometry
// XkbGetNamedIndicator
// XkbGetNames
// XkbGetPerClientControls
// _XkbGetReadBufferCountedString
// _XkbGetReadBufferPtr
// XkbGetState
// XkbGetUpdatedMap
// XkbGetVirtualMods
// XkbGetXlibControls
// XkbIgnoreExtension
// XkbInitCanonicalKeyTypes
// _XkbInitReadBuffer
DATA(_XkbInternAtomFunc, 4)
// XkbKeycodeToKeysym
// XkbKeysymToModifiers
// XkbKeyTypesForCoreSymbols
// XkbLatchGroup
// XkbLatchModifiers
// XkbLibraryVersion
// XkbListComponents
// XkbLockGroup
// XkbLockModifiers
// XkbLookupKeyBinding
// XkbLookupKeySym
// XkbNoteControlsChanges
// _XkbNoteCoreMapChanges
// XkbNoteDeviceChanges
// XkbNoteMapChanges
// XkbNoteNameChanges
// XkbOpenDisplay
// _XkbPeekAtReadBuffer
// XkbQueryExtension
// _XkbReadBufferCopyKeySyms
// _XkbReadCopyKeySyms
// _XkbReadGetCompatMapReply
// _XkbReadGetGeometryReply
// _XkbReadGetIndicatorMapReply
// _XkbReadGetMapReply
// _XkbReadGetNamesReply
// XkbRefreshKeyboardMapping
// _XkbReloadDpy
// XkbResizeDeviceButtonActions
// XkbResizeKeyActions
// XkbResizeKeySyms
// XkbResizeKeyType
// XkbSelectEventDetails
// XkbSelectEvents
// XkbSetAtomFuncs
// XkbSetAutoRepeatRate
// XkbSetAutoResetControls
// XkbSetCompatMap
// XkbSetControls
// XkbSetDebuggingFlags
// XkbSetDetectableAutoRepeat
// XkbSetDeviceButtonActions
// XkbSetDeviceInfo
// XkbSetDeviceLedInfo
// XkbSetGeometry
// XkbSetIgnoreLockMods
// XkbSetIndicatorMap
// XkbSetMap
// XkbSetNamedDeviceIndicator
// XkbSetNamedIndicator
// XkbSetNames
// XkbSetPerClientControls
// XkbSetServerInternalMods
// XkbSetXlibControls
// _XkbSkipReadBufferData
// XkbToControl
// XkbTranslateKey
// XkbTranslateKeyCode
// XkbTranslateKeySym
// XkbUpdateActionVirtualMods
// XkbUpdateKeyTypeVirtualMods
// XkbUpdateMapFromCore
// XkbUseExtension
// XkbVirtualModsToReal
// _XkbWriteCopyKeySyms
// XkbXlibControlsImplemented
// XKeycodeToKeysym
// _XKeycodeToKeysym
// _XKeyInitialize
// XKeysymToKeycode
// _XKeysymToKeycode
// _XKeysymToModifiers
// XKeysymToString
// _XkeyTable   // type r
// XKillClient
// XLastKnownRequestProcessed
// _XlcAddCharSet
// _XlcAddCT
// _XlcAddGB18030LocaleConverters
// _XlcAddLoader
// _XlcAddUtf8Converters
// _XlcAddUtf8LocaleConverters
// _XlcCloseConverter
// _XlcCompareISOLatin1
// _XlcCompileResourceList
// _XlcConvert
// _XlcCopyFromArg
// _XlcCopyToArg
// _XlcCountVaList
// _XlcCreateDefaultCharSet
// _XlcCreateLC
// _XlcCreateLocaleDataBase
// _XlcCurrentLC
// _XlcDbg_printValue
// _XlcDefaultMapModifiers
// _XlcDeInitLoader
// _XlcDestroyLC
// _XlcDestroyLocaleDataBase
// _XlcDynamicLoad
// _XlcFileName
DATA(_XlcGenericMethods, 4)
// _XlcGetCharSet
// _XlcGetCharSetWithSide
// _XlcGetCSValues
// _XlcGetLocaleDataBase
// _XlcGetResource
// _XlcGetValues
// _XlcInitCTInfo
// _XlcInitLoader
// _XlcLocaleDirName
// _XlcLocaleLibDirName
// _XlcMapOSLocaleName
// _Xlcmbstoutf8
// _Xlcmbstowcs
// _Xlcmbtowc
// _XlcNCompareISOLatin1
// _XlcOpenConverter
// _XlcParseCharSet
// _XlcParse_scopemaps
DATA(_XlcPublicMethods, 4)
// _XlcRemoveLoader
// _XlcResetConverter
// _XlcResolveI18NPath
// _XlcResolveLocaleName
// _XlcSetConverter
// _XlcSetValues
// _XlcValidModSyntax
// _XlcVaToArgList
// _Xlcwcstombs
// _Xlcwctomb
// XListDepths
// XListExtensions
// XListFonts
// XListFontsWithInfo
// XListHosts
// XListInstalledColormaps
// XListPixmapFormats
GO(XListProperties, pFppp)
// XLoadFont
// XLoadQueryFont
// xlocaledir
// XLocaleOfFontSet
// XLocaleOfIM
// XLocaleOfOM
// XLockDisplay
DATAB(_XLockMutex_fn, 4)
// XLookupColor
// XLookupKeysym
// _XLookupKeysym
// XLookupString
// _XLookupString
// XLowerWindow
// XMapRaised
// XMapSubwindows
// XMapWindow
// XMaskEvent
// XMatchVisualInfo
// XMaxCmapsOfScreen
// XMaxRequestSize
// XmbDrawImageString
// XmbDrawString
// XmbDrawText
// _Xmblen
// XmbLookupString
// XmbResetIC
// XmbSetWMProperties
// _Xmbstoutf8
// _Xmbstowcs
// XmbTextEscapement
// XmbTextExtents
// XmbTextListToTextProperty
// _XmbTextListToTextProperty
// XmbTextPerCharExtents
// XmbTextPropertyToTextList
// _XmbTextPropertyToTextList
// _Xmbtowc
// XMinCmapsOfScreen
// XMoveResizeWindow
// XMoveWindow
// XNewModifiermap
// XNextEvent
// XNextRequest
// XNoOp
// _XNoticeCreateBitmap
// _XNoticePutBitmap
// XOffsetRegion
// XOMOfOC
// XOpenDisplay
// XOpenIM
// _XOpenLC
// XOpenOM
// _XParseBaseFontNameList
// XParseColor
// XParseGeometry
// XPeekEvent
// XPeekIfEvent
GO(XPending, iFp)
// Xpermalloc
// XPlanesOfScreen
// XPointInRegion
// _XPollfdCacheAdd
// _XPollfdCacheDel
// _XPollfdCacheInit
// XPolygonRegion
// XProcessInternalConnection
// _XProcessInternalConnection
// _XProcessWindowAttributes
// XProtocolRevision
// XProtocolVersion
// XPutBackEvent
// _XPutBackEvent
GO(XPutImage, iFppppiiiiuu)
// XPutPixel
// XQLength
// XQueryBestCursor
// XQueryBestSize
// XQueryBestStipple
// XQueryBestTile
// XQueryColor
// XQueryColors
// XQueryExtension
// XQueryFont
// XQueryKeymap
// XQueryPointer
// XQueryTextExtents
// XQueryTextExtents16
// XQueryTree
// XRaiseWindow
// _XRead
// XReadBitmapFile
// XReadBitmapFileData
// _XReadEvents
// _XReadPad
// XRebindKeysym
// XRecolorCursor
// XReconfigureWMWindow
// XRectInRegion
// XRefreshKeyboardMapping
// _XRefreshKeyboardMapping
// _XRegisterFilterByMask
// _XRegisterFilterByType
// XRegisterIMInstantiateCallback
// _XRegisterInternalConnection
// XRemoveConnectionWatch
// XRemoveFromSaveSet
// XRemoveHost
// XRemoveHosts
// XReparentWindow
// _XReply
// XResetScreenSaver
// XResizeWindow
// XResourceManagerString
// XRestackWindows
// _XReverse_Bytes
// XrmCombineDatabase
// XrmCombineFileDatabase
// _XrmDefaultInitParseInfo
// XrmDestroyDatabase
// XrmEnumerateDatabase
// XrmGetDatabase
// XrmGetFileDatabase
// XrmGetResource
// XrmGetStringDatabase
// XrmInitialize
// _XrmInitParseInfo
// _XrmInternalStringToQuark
// XrmLocaleOfDatabase
// XrmMergeDatabases
// XrmParseCommand
// XrmPermStringToQuark
// XrmPutFileDatabase
// XrmPutLineResource
// XrmPutResource
// XrmPutStringResource
// XrmQGetResource
// XrmQGetSearchList
// XrmQGetSearchResource
// XrmQPutResource
// XrmQPutStringResource
// XrmQuarkToString
// XrmSetDatabase
// XrmStringToBindingQuarkList
// XrmStringToQuark
// XrmStringToQuarkList
// XrmUniqueQuark
// XRootWindow
// XRootWindowOfScreen
// XRotateBuffers
GO(XRotateWindowProperties, iFpppii)
// XSaveContext
// XScreenCount
// XScreenNumberOfScreen
// XScreenOfDisplay
// _XScreenOfWindow
// XScreenResourceString
// XSelectInput
// _XSend
GO(XSendEvent, uFppiip)
// XServerVendor
// XSetAccessControl
// XSetAfterFunction
GO(XSetArcMode, iFppi)
// XSetAuthorization
// XSetBackground
// XSetClassHint
// XSetClipMask
// XSetClipOrigin
// XSetClipRectangles
// _XSetClipRectangles
// XSetCloseDownMode
// XSetCommand
// XSetDashes
// XSetErrorHandler
// XSetFillRule
// XSetFillStyle
// XSetFont
// XSetFontPath
// XSetForeground
// XSetFunction
GO(XSetGraphicsExposures, iFppu)
// XSetICFocus
// XSetIconName
// XSetIconSizes
// XSetICValues
// _XSetImage
// XSetIMValues
// XSetInputFocus
// XSetIOErrorHandler
// _XSetLastRequestRead
// XSetLineAttributes
// XSetLocaleModifiers
// XSetModifierMapping
// XSetNormalHints
// XSetOCValues
// XSetOMValues
// XSetPlaneMask
// XSetPointerMapping
// XSetRegion
// XSetRGBColormaps
// XSetScreenSaver
// XSetSelectionOwner
// XSetSizeHints
// XSetStandardColormap
// XSetStandardProperties
// XSetState
// XSetStipple
GO(XSetSubwindowMode, iFppi)
// XSetTextProperty
// XSetTile
// XSetTransientForHint
// XSetTSOrigin
// XSetWindowBackground
// XSetWindowBackgroundPixmap
// XSetWindowBorder
// XSetWindowBorderPixmap
// XSetWindowBorderWidth
// XSetWindowColormap
// XSetWMClientMachine
// XSetWMColormapWindows
// XSetWMHints
// XSetWMIconName
// XSetWMName
// XSetWMNormalHints
// XSetWMProperties
// XSetWMProtocols
// XSetWMSizeHints
// XSetZoomHints
// XShrinkRegion
// XStoreBuffer
// XStoreBytes
// XStoreColor
// XStoreColors
// _XStoreEventCookie
// XStoreName
// XStoreNamedColor
// XStringListToTextProperty
// XStringToKeysym
// XSubImage
// XSubtractRegion
// XSupportsLocale
GO(XSync, iFpu)
GO(XSynchronize, iFpi)
// XTextExtents
// XTextExtents16
// _XTextHeight
// _XTextHeight16
// XTextPropertyToStringList
// XTextWidth
// XTextWidth16
DATAB(_Xthread_self_fn, 4)
// XTranslateCoordinates
// _XTranslateKey
// _XTranslateKeySym
// _XTryShapeBitmapCursor
// XUndefineCursor
// XUngrabButton
// XUngrabKey
GO(XUngrabKeyboard, iFpu)
GO(XUngrabPointer, iFpu)
// XUngrabServer
// XUninstallColormap
// XUnionRectWithRegion
// XUnionRegion
// _XUnknownCopyEventCookie
// _XUnknownNativeEvent
// _XUnknownWireEvent
// _XUnknownWireEventCookie
// XUnloadFont
// XUnlockDisplay
DATAB(_XUnlockMutex_fn, 4)
// XUnmapSubwindows
// XUnmapWindow
// _XUnregisterFilter
// XUnregisterIMInstantiateCallback
// _XUnregisterInternalConnection
// _XUnresolveColor
// XUnsetICFocus
// _XUpdateAtomCache
// _XUpdateGCCache
// Xutf8DrawImageString
// Xutf8DrawString
// Xutf8DrawText
// Xutf8LookupString
// Xutf8ResetIC
// Xutf8SetWMProperties
// Xutf8TextEscapement
// Xutf8TextExtents
// Xutf8TextListToTextProperty
// _Xutf8TextListToTextProperty
// Xutf8TextPerCharExtents
// Xutf8TextPropertyToTextList
// _Xutf8TextPropertyToTextList
// XVaCreateNestedList
// XVendorRelease
// _XVIDtoVisual
// XVisualIDFromVisual
// XWarpPointer
// XwcDrawImageString
// XwcDrawString
// XwcDrawText
// XwcFreeStringList
// _XwcFreeStringList
// XwcLookupString
// XwcResetIC
// _Xwcscmp
// _Xwcscpy
// _Xwcslen
// _Xwcsncmp
// _Xwcsncpy
// _Xwcstombs
// XwcTextEscapement
// XwcTextExtents
// XwcTextListToTextProperty
// _XwcTextListToTextProperty
// XwcTextPerCharExtents
// XwcTextPropertyToTextList
// _XwcTextPropertyToTextList
// _Xwctomb
// XWhitePixel
// XWhitePixelOfScreen
// XWidthMMOfScreen
// XWidthOfScreen
// XWindowEvent
// _XWireToEvent
// XWithdrawWindow
// XWMGeometry
// XWriteBitmapFile
// XXorRegion
END()

#else
#error Mmmm...
#endif