#if defined(GO) && defined(GOM) && defined(GO2) && defined(DATA) && defined(END)

// alsa_lisp
// alsa_lisp_default_cfg
// alsa_lisp_default_cfg_free
// alsa_lisp_free
// alsa_lisp_function
// alsa_lisp_init_objects
DATAB(alsa_lisp_nil, 4)
// alsa_lisp_result_free
// alsa_lisp_seq_count
// alsa_lisp_seq_first
// alsa_lisp_seq_integer
// alsa_lisp_seq_next
// alsa_lisp_seq_pointer
DATAB(alsa_lisp_t, 4)
GO(snd_asoundlib_version, pFv)
// snd_async_add_ctl_handler
GOM(snd_async_add_handler, iFEpipp)
GOM(snd_async_add_pcm_handler, iFEp)
// snd_async_add_timer_handler
// snd_async_del_handler
GOM(snd_async_handler_get_callback_private, pFEp)
// snd_async_handler_get_ctl
GO(snd_async_handler_get_fd, iFp)
// snd_async_handler_get_pcm
GO(snd_async_handler_get_signo, iFp)
// snd_async_handler_get_timer
// snd_atomic_read_wait
// snd_card_get_index
// snd_card_get_longname
// snd_card_get_name
// snd_card_load
// snd_card_next
DATAB(snd_config, 4)
// snd_config_add
// snd_config_copy
// snd_config_delete
// snd_config_delete_compound_members
// snd_config_evaluate
// snd_config_expand
// snd_config_get_ascii
// snd_config_get_bool
// snd_config_get_bool_ascii
// snd_config_get_ctl_iface
// snd_config_get_ctl_iface_ascii
// snd_config_get_id
// snd_config_get_integer
// snd_config_get_integer64
// snd_config_get_ireal
// snd_config_get_pointer
// snd_config_get_real
// snd_config_get_string
// snd_config_get_type
// snd_config_get_type_ascii
// snd_config_hook_load
DATAB(_snd_config_hook_load_dlsym_config_hook_001, 4)
// snd_config_hook_load_for_all_cards
DATAB(_snd_config_hook_load_for_all_cards_dlsym_config_hook_001, 4)
// snd_config_imake_integer
// snd_config_imake_integer64
// snd_config_imake_pointer
// snd_config_imake_real
// snd_config_imake_string
// snd_config_iterator_end
// snd_config_iterator_entry
// snd_config_iterator_first
// snd_config_iterator_next
// snd_config_load
// snd_config_load_override
// snd_config_make
// snd_config_make_compound
// snd_config_make_integer
// snd_config_make_integer64
// snd_config_make_pointer
// snd_config_make_real
// snd_config_make_string
// snd_config_remove
// snd_config_save
// snd_config_search
// snd_config_searcha
// snd_config_searcha_hooks
// snd_config_search_alias
// snd_config_search_definition
// snd_config_search_hooks
// snd_config_searchv
// snd_config_searchva
// snd_config_searchva_hooks
// snd_config_set_ascii
// snd_config_set_id
// snd_config_set_integer
// snd_config_set_integer64
// snd_config_set_pointer
// snd_config_set_real
// snd_config_set_string
// snd_config_substitute
// snd_config_test_id
// snd_config_top
// snd_config_update
// snd_config_update_free
// snd_config_update_free_global
// snd_config_update_r
// snd_ctl_ascii_elem_id_get
// snd_ctl_ascii_elem_id_parse
// snd_ctl_ascii_value_parse
// snd_ctl_async
// snd_ctl_card_info
// snd_ctl_card_info_clear
// snd_ctl_card_info_copy
// snd_ctl_card_info_free
// snd_ctl_card_info_get_card
// snd_ctl_card_info_get_components
// snd_ctl_card_info_get_driver
// snd_ctl_card_info_get_id
// snd_ctl_card_info_get_longname
// snd_ctl_card_info_get_mixername
// snd_ctl_card_info_get_name
// snd_ctl_card_info_malloc
// snd_ctl_card_info_sizeof
// snd_ctl_close
// snd_ctl_convert_from_dB
// snd_ctl_convert_to_dB
// snd_ctl_elem_add_boolean
// snd_ctl_elem_add_enumerated
// snd_ctl_elem_add_iec958
// snd_ctl_elem_add_integer
// snd_ctl_elem_add_integer64
// snd_ctl_elem_id_clear
// snd_ctl_elem_id_copy
// snd_ctl_elem_id_free
// snd_ctl_elem_id_get_device
// snd_ctl_elem_id_get_index
// snd_ctl_elem_id_get_interface
// snd_ctl_elem_id_get_name
// snd_ctl_elem_id_get_numid
// snd_ctl_elem_id_get_subdevice
// snd_ctl_elem_id_malloc
// snd_ctl_elem_id_set_device
// snd_ctl_elem_id_set_index
// snd_ctl_elem_id_set_interface
// snd_ctl_elem_id_set_name
// snd_ctl_elem_id_set_numid
// snd_ctl_elem_id_set_subdevice
// snd_ctl_elem_id_sizeof
// snd_ctl_elem_iface_name
// snd_ctl_elem_info
// snd_ctl_elem_info_clear
// snd_ctl_elem_info_copy
// snd_ctl_elem_info_free
// snd_ctl_elem_info_get_count
// snd_ctl_elem_info_get_device
// snd_ctl_elem_info_get_dimension
// snd_ctl_elem_info_get_dimensions
// snd_ctl_elem_info_get_id
// snd_ctl_elem_info_get_index
// snd_ctl_elem_info_get_interface
// snd_ctl_elem_info_get_item_name
// snd_ctl_elem_info_get_items
// snd_ctl_elem_info_get_max
// snd_ctl_elem_info_get_max64
// snd_ctl_elem_info_get_min
// snd_ctl_elem_info_get_min64
// snd_ctl_elem_info_get_name
// snd_ctl_elem_info_get_numid
// snd_ctl_elem_info_get_owner
// snd_ctl_elem_info_get_step
// snd_ctl_elem_info_get_step64
// snd_ctl_elem_info_get_subdevice
// snd_ctl_elem_info_get_type
// snd_ctl_elem_info_is_inactive
// snd_ctl_elem_info_is_indirect
// snd_ctl_elem_info_is_locked
// snd_ctl_elem_info_is_owner
// snd_ctl_elem_info_is_readable
// snd_ctl_elem_info_is_tlv_commandable
// snd_ctl_elem_info_is_tlv_readable
// snd_ctl_elem_info_is_tlv_writable
// snd_ctl_elem_info_is_user
// snd_ctl_elem_info_is_volatile
// snd_ctl_elem_info_is_writable
// snd_ctl_elem_info_malloc
// snd_ctl_elem_info_set_device
// snd_ctl_elem_info_set_id
// snd_ctl_elem_info_set_index
// snd_ctl_elem_info_set_interface
// snd_ctl_elem_info_set_item
// snd_ctl_elem_info_set_name
// snd_ctl_elem_info_set_numid
// snd_ctl_elem_info_set_subdevice
// snd_ctl_elem_info_sizeof
// snd_ctl_elem_list
// snd_ctl_elem_list_alloc_space
// snd_ctl_elem_list_clear
// snd_ctl_elem_list_copy
// snd_ctl_elem_list_free
// snd_ctl_elem_list_free_space
// snd_ctl_elem_list_get_count
// snd_ctl_elem_list_get_device
// snd_ctl_elem_list_get_id
// snd_ctl_elem_list_get_index
// snd_ctl_elem_list_get_interface
// snd_ctl_elem_list_get_name
// snd_ctl_elem_list_get_numid
// snd_ctl_elem_list_get_subdevice
// snd_ctl_elem_list_get_used
// snd_ctl_elem_list_malloc
// snd_ctl_elem_list_set_offset
// snd_ctl_elem_list_sizeof
// snd_ctl_elem_lock
// snd_ctl_elem_read
// snd_ctl_elem_remove
// snd_ctl_elem_set_bytes
// snd_ctl_elem_tlv_command
// snd_ctl_elem_tlv_read
// snd_ctl_elem_tlv_write
// snd_ctl_elem_type_name
// snd_ctl_elem_unlock
// snd_ctl_elem_value_clear
// snd_ctl_elem_value_compare
// snd_ctl_elem_value_copy
// snd_ctl_elem_value_free
// snd_ctl_elem_value_get_boolean
// snd_ctl_elem_value_get_byte
// snd_ctl_elem_value_get_bytes
// snd_ctl_elem_value_get_device
// snd_ctl_elem_value_get_enumerated
// snd_ctl_elem_value_get_id
// snd_ctl_elem_value_get_iec958
// snd_ctl_elem_value_get_index
// snd_ctl_elem_value_get_integer
// snd_ctl_elem_value_get_integer64
// snd_ctl_elem_value_get_interface
// snd_ctl_elem_value_get_name
// snd_ctl_elem_value_get_numid
// snd_ctl_elem_value_get_subdevice
// snd_ctl_elem_value_malloc
// snd_ctl_elem_value_set_boolean
// snd_ctl_elem_value_set_byte
// snd_ctl_elem_value_set_device
// snd_ctl_elem_value_set_enumerated
// snd_ctl_elem_value_set_id
// snd_ctl_elem_value_set_iec958
// snd_ctl_elem_value_set_index
// snd_ctl_elem_value_set_integer
// snd_ctl_elem_value_set_integer64
// snd_ctl_elem_value_set_interface
// snd_ctl_elem_value_set_name
// snd_ctl_elem_value_set_numid
// snd_ctl_elem_value_set_subdevice
// snd_ctl_elem_value_sizeof
// snd_ctl_elem_write
// snd_ctl_event_clear
// snd_ctl_event_copy
// snd_ctl_event_elem_get_device
// snd_ctl_event_elem_get_id
// snd_ctl_event_elem_get_index
// snd_ctl_event_elem_get_interface
// snd_ctl_event_elem_get_mask
// snd_ctl_event_elem_get_name
// snd_ctl_event_elem_get_numid
// snd_ctl_event_elem_get_subdevice
// snd_ctl_event_free
// snd_ctl_event_get_type
// snd_ctl_event_malloc
// snd_ctl_event_sizeof
// snd_ctl_event_type_name
// snd_ctl_ext_create
// snd_ctl_ext_delete
// snd_ctl_get_dB_range
// snd_ctl_get_power_state
// snd_ctl_hwdep_info
// snd_ctl_hwdep_next_device
// _snd_ctl_hw_open
// snd_ctl_hw_open
DATAB(__snd_ctl_hw_open_dlsym_control_001, 4)
// snd_ctl_name
// snd_ctl_nonblock
// snd_ctl_open
// snd_ctl_open_fallback
// snd_ctl_open_lconf
// snd_ctl_pcm_info
// snd_ctl_pcm_next_device
// snd_ctl_pcm_prefer_subdevice
// _snd_ctl_poll_descriptor
// snd_ctl_poll_descriptors
// snd_ctl_poll_descriptors_count
// snd_ctl_poll_descriptors_revents
// snd_ctl_rawmidi_info
// snd_ctl_rawmidi_next_device
// snd_ctl_rawmidi_prefer_subdevice
// snd_ctl_read
// snd_ctl_set_power_state
// _snd_ctl_shm_open
// snd_ctl_shm_open
DATAB(__snd_ctl_shm_open_dlsym_control_001, 4)
// snd_ctl_subscribe_events
// snd_ctl_type
// snd_ctl_wait
// snd_determine_driver
// snd_device_name_free_hint
// snd_device_name_get_hint
// snd_device_name_hint
// snd_dlclose
// snd_dlopen
// snd_dlsym
DATA(snd_err_msg, 4)
// snd_func_card_driver
DATAB(_snd_func_card_driver_dlsym_config_evaluate_001, 4)
// snd_func_card_id
DATAB(_snd_func_card_id_dlsym_config_evaluate_001, 4)
// snd_func_card_inum
DATAB(_snd_func_card_inum_dlsym_config_evaluate_001, 4)
// snd_func_card_name
DATAB(_snd_func_card_name_dlsym_config_evaluate_001, 4)
// snd_func_concat
DATAB(_snd_func_concat_dlsym_config_evaluate_001, 4)
// snd_func_datadir
DATAB(_snd_func_datadir_dlsym_config_evaluate_001, 4)
// snd_func_getenv
DATAB(_snd_func_getenv_dlsym_config_evaluate_001, 4)
// snd_func_iadd
DATAB(_snd_func_iadd_dlsym_config_evaluate_001, 4)
// snd_func_igetenv
DATAB(_snd_func_igetenv_dlsym_config_evaluate_001, 4)
// snd_func_imul
DATAB(_snd_func_imul_dlsym_config_evaluate_001, 4)
// snd_func_pcm_args_by_class
DATAB(_snd_func_pcm_args_by_class_dlsym_config_evaluate_001, 4)
// snd_func_pcm_id
DATAB(_snd_func_pcm_id_dlsym_config_evaluate_001, 4)
// snd_func_private_card_driver
DATAB(_snd_func_private_card_driver_dlsym_config_evaluate_001, 4)
// snd_func_private_pcm_subdevice
DATAB(_snd_func_private_pcm_subdevice_dlsym_config_evaluate_001, 4)
// snd_func_private_string
DATAB(_snd_func_private_string_dlsym_config_evaluate_001, 4)
// snd_func_refer
DATAB(_snd_func_refer_dlsym_config_evaluate_001, 4)
// snd_hctl_async
// snd_hctl_close
// snd_hctl_compare_fast
// snd_hctl_ctl
// snd_hctl_elem_get_callback_private
// snd_hctl_elem_get_device
// snd_hctl_elem_get_hctl
// snd_hctl_elem_get_id
// snd_hctl_elem_get_index
// snd_hctl_elem_get_interface
// snd_hctl_elem_get_name
// snd_hctl_elem_get_numid
// snd_hctl_elem_get_subdevice
// snd_hctl_elem_info
// snd_hctl_elem_next
// snd_hctl_elem_prev
// snd_hctl_elem_read
// snd_hctl_elem_set_callback
// snd_hctl_elem_set_callback_private
// snd_hctl_elem_tlv_command
// snd_hctl_elem_tlv_read
// snd_hctl_elem_tlv_write
// snd_hctl_elem_write
// snd_hctl_find_elem
// snd_hctl_first_elem
// snd_hctl_free
// snd_hctl_get_callback_private
// snd_hctl_get_count
// snd_hctl_handle_events
// snd_hctl_last_elem
// snd_hctl_load
// snd_hctl_name
// snd_hctl_nonblock
// snd_hctl_open
// snd_hctl_open_ctl
// snd_hctl_poll_descriptors
// snd_hctl_poll_descriptors_count
// snd_hctl_poll_descriptors_revents
// snd_hctl_set_callback
// snd_hctl_set_callback_private
// snd_hctl_set_compare
// snd_hctl_wait
// snd_hwdep_close
// snd_hwdep_dsp_image_copy
// snd_hwdep_dsp_image_free
// snd_hwdep_dsp_image_get_image
// snd_hwdep_dsp_image_get_index
// snd_hwdep_dsp_image_get_length
// snd_hwdep_dsp_image_get_name
// snd_hwdep_dsp_image_malloc
// snd_hwdep_dsp_image_set_image
// snd_hwdep_dsp_image_set_index
// snd_hwdep_dsp_image_set_length
// snd_hwdep_dsp_image_set_name
// snd_hwdep_dsp_image_sizeof
// snd_hwdep_dsp_load
// snd_hwdep_dsp_status
// snd_hwdep_dsp_status_copy
// snd_hwdep_dsp_status_free
// snd_hwdep_dsp_status_get_chip_ready
// snd_hwdep_dsp_status_get_dsp_loaded
// snd_hwdep_dsp_status_get_id
// snd_hwdep_dsp_status_get_num_dsps
// snd_hwdep_dsp_status_get_version
// snd_hwdep_dsp_status_malloc
// snd_hwdep_dsp_status_sizeof
// _snd_hwdep_hw_open
// snd_hwdep_hw_open
DATAB(__snd_hwdep_hw_open_dlsym_hwdep_001, 4)
// snd_hwdep_info
// snd_hwdep_info_copy
// snd_hwdep_info_free
// snd_hwdep_info_get_card
// snd_hwdep_info_get_device
// snd_hwdep_info_get_id
// snd_hwdep_info_get_iface
// snd_hwdep_info_get_name
// snd_hwdep_info_malloc
// snd_hwdep_info_set_device
// snd_hwdep_info_sizeof
// snd_hwdep_ioctl
// snd_hwdep_name
// snd_hwdep_nonblock
// snd_hwdep_open
// snd_hwdep_open_lconf
// snd_hwdep_poll_descriptors
// snd_hwdep_poll_descriptors_count
// snd_hwdep_poll_descriptors_revents
// snd_hwdep_read
// snd_hwdep_type
// snd_hwdep_write
GO(snd_input_buffer_open, iFppu)
GO(snd_input_close, iFp)
// snd_input_getc
// snd_input_gets
// snd_input_scanf
GO(snd_input_stdio_attach, iFppp)
GO(snd_input_stdio_open, iFppp)
// snd_input_ungetc
// snd_instr_fm_convert_from_stream
// snd_instr_fm_convert_to_stream
// snd_instr_fm_free
// snd_instr_header_copy
// snd_instr_header_free
// snd_instr_header_get_alias
// snd_instr_header_get_cluster
// snd_instr_header_get_cmd
// snd_instr_header_get_data
// snd_instr_header_get_follow_alias
// snd_instr_header_get_format
// snd_instr_header_get_id
// snd_instr_header_get_len
// snd_instr_header_get_name
// snd_instr_header_get_type
// snd_instr_header_malloc
// snd_instr_header_set_alias
// snd_instr_header_set_cluster
// snd_instr_header_set_cmd
// snd_instr_header_set_follow_alias
// snd_instr_header_set_format
// snd_instr_header_set_id
// snd_instr_header_set_len
// snd_instr_header_set_name
// snd_instr_header_set_type
// snd_instr_header_sizeof
// snd_instr_iwffff_close
// snd_instr_iwffff_convert_from_stream
// snd_instr_iwffff_convert_to_stream
// snd_instr_iwffff_free
// snd_instr_iwffff_load
// snd_instr_iwffff_open
// snd_instr_iwffff_open_rom
// snd_instr_iwffff_open_rom_file
// snd_instr_simple_convert_from_stream
// snd_instr_simple_convert_to_stream
// snd_instr_simple_free
// snd_is_local
DATA(snd_lib_error, 4)
GOM(snd_lib_error_set_handler, iFEp)
// snd_lib_error_set_local
// snd_midi_event_decode
// snd_midi_event_encode
// snd_midi_event_encode_byte
// snd_midi_event_free
// snd_midi_event_init
// snd_midi_event_new
// snd_midi_event_no_status
// snd_midi_event_reset_decode
// snd_midi_event_reset_encode
// snd_midi_event_resize_buffer
// snd_mixer_attach
// snd_mixer_attach_hctl
// snd_mixer_class_copy
// snd_mixer_class_free
// snd_mixer_class_get_compare
// snd_mixer_class_get_event
// snd_mixer_class_get_mixer
// snd_mixer_class_get_private
// snd_mixer_class_malloc
// snd_mixer_class_register
// snd_mixer_class_set_compare
// snd_mixer_class_set_event
// snd_mixer_class_set_private
// snd_mixer_class_set_private_free
// snd_mixer_class_sizeof
// snd_mixer_class_unregister
// snd_mixer_close
// snd_mixer_detach
// snd_mixer_detach_hctl
// snd_mixer_elem_add
// snd_mixer_elem_attach
// snd_mixer_elem_detach
// snd_mixer_elem_empty
// snd_mixer_elem_free
// snd_mixer_elem_get_callback_private
// snd_mixer_elem_get_private
// snd_mixer_elem_get_type
// snd_mixer_elem_info
// snd_mixer_elem_new
// snd_mixer_elem_next
// snd_mixer_elem_prev
// snd_mixer_elem_remove
// snd_mixer_elem_set_callback
// snd_mixer_elem_set_callback_private
// snd_mixer_elem_value
// snd_mixer_find_selem
// snd_mixer_first_elem
// snd_mixer_free
// snd_mixer_get_callback_private
// snd_mixer_get_count
// snd_mixer_get_hctl
// snd_mixer_handle_events
// snd_mixer_last_elem
// snd_mixer_load
// snd_mixer_open
// snd_mixer_poll_descriptors
// snd_mixer_poll_descriptors_count
// snd_mixer_poll_descriptors_revents
// snd_mixer_sbasic_get_private
// snd_mixer_sbasic_info
// snd_mixer_sbasic_set_private
// snd_mixer_sbasic_set_private_free
// snd_mixer_selem_ask_capture_dB_vol
// snd_mixer_selem_ask_capture_vol_dB
// snd_mixer_selem_ask_playback_dB_vol
// snd_mixer_selem_ask_playback_vol_dB
// snd_mixer_selem_channel_name
// snd_mixer_selem_compare
// snd_mixer_selem_get_capture_dB
// snd_mixer_selem_get_capture_dB_range
// snd_mixer_selem_get_capture_group
// snd_mixer_selem_get_capture_switch
// snd_mixer_selem_get_capture_volume
// snd_mixer_selem_get_capture_volume_range
// snd_mixer_selem_get_enum_item
// snd_mixer_selem_get_enum_item_name
// snd_mixer_selem_get_enum_items
// snd_mixer_selem_get_id
// snd_mixer_selem_get_index
// snd_mixer_selem_get_name
// snd_mixer_selem_get_playback_dB
// snd_mixer_selem_get_playback_dB_range
// snd_mixer_selem_get_playback_switch
// snd_mixer_selem_get_playback_volume
// snd_mixer_selem_get_playback_volume_range
// snd_mixer_selem_has_capture_channel
// snd_mixer_selem_has_capture_switch
// snd_mixer_selem_has_capture_switch_exclusive
// snd_mixer_selem_has_capture_switch_joined
// snd_mixer_selem_has_capture_volume
// snd_mixer_selem_has_capture_volume_joined
// snd_mixer_selem_has_common_switch
// snd_mixer_selem_has_common_volume
// snd_mixer_selem_has_playback_channel
// snd_mixer_selem_has_playback_switch
// snd_mixer_selem_has_playback_switch_joined
// snd_mixer_selem_has_playback_volume
// snd_mixer_selem_has_playback_volume_joined
// snd_mixer_selem_id_copy
// snd_mixer_selem_id_free
// snd_mixer_selem_id_get_index
// snd_mixer_selem_id_get_name
// snd_mixer_selem_id_malloc
// snd_mixer_selem_id_set_index
// snd_mixer_selem_id_set_name
// snd_mixer_selem_id_sizeof
// snd_mixer_selem_is_active
// snd_mixer_selem_is_capture_mono
// snd_mixer_selem_is_enum_capture
// snd_mixer_selem_is_enumerated
// snd_mixer_selem_is_enum_playback
// snd_mixer_selem_is_playback_mono
// snd_mixer_selem_register
// snd_mixer_selem_set_capture_dB
// snd_mixer_selem_set_capture_dB_all
// snd_mixer_selem_set_capture_switch
// snd_mixer_selem_set_capture_switch_all
// snd_mixer_selem_set_capture_volume
// snd_mixer_selem_set_capture_volume_all
// snd_mixer_selem_set_capture_volume_range
// snd_mixer_selem_set_enum_item
// snd_mixer_selem_set_playback_dB
// snd_mixer_selem_set_playback_dB_all
// snd_mixer_selem_set_playback_switch
// snd_mixer_selem_set_playback_switch_all
// snd_mixer_selem_set_playback_volume
// snd_mixer_selem_set_playback_volume_all
// snd_mixer_selem_set_playback_volume_range
// snd_mixer_set_callback
// snd_mixer_set_callback_private
// snd_mixer_set_compare
// snd_mixer_wait
// snd_names_list
// snd_names_list_free
// snd_output_buffer_open
// snd_output_buffer_string
// snd_output_close
// snd_output_flush
// snd_output_printf
// snd_output_putc
// snd_output_puts
// snd_output_stdio_attach
// snd_output_stdio_open
// snd_output_vprintf
// snd_pcm_access_mask_any
// snd_pcm_access_mask_copy
// snd_pcm_access_mask_empty
// snd_pcm_access_mask_free
// snd_pcm_access_mask_malloc
// snd_pcm_access_mask_none
// snd_pcm_access_mask_reset
// snd_pcm_access_mask_set
// snd_pcm_access_mask_sizeof
// snd_pcm_access_mask_test
// snd_pcm_access_name
// _snd_pcm_adpcm_open
// snd_pcm_adpcm_open
DATAB(__snd_pcm_adpcm_open_dlsym_pcm_001, 4)
// _snd_pcm_alaw_open
// snd_pcm_alaw_open
DATAB(__snd_pcm_alaw_open_dlsym_pcm_001, 4)
// snd_pcm_area_copy
// snd_pcm_areas_copy
// snd_pcm_area_silence
// snd_pcm_areas_silence
// _snd_pcm_asym_open
DATAB(__snd_pcm_asym_open_dlsym_pcm_001, 4)
// snd_pcm_async
// snd_pcm_avail
// snd_pcm_avail_delay
// snd_pcm_avail_update
// snd_pcm_build_linear_format
// snd_pcm_bytes_to_frames
// snd_pcm_bytes_to_samples
// snd_pcm_chmap_from_string
// snd_pcm_chmap_long_name
// snd_pcm_chmap_name
// snd_pcm_chmap_parse_string
// snd_pcm_chmap_print
// snd_pcm_chmap_type_name
// snd_pcm_close
// _snd_pcm_copy_open
// snd_pcm_copy_open
DATAB(__snd_pcm_copy_open_dlsym_pcm_001, 4)
// snd_pcm_delay
// _snd_pcm_dmix_open
// snd_pcm_dmix_open
DATAB(__snd_pcm_dmix_open_dlsym_pcm_001, 4)
// snd_pcm_drain
// snd_pcm_drop
// _snd_pcm_dshare_open
// snd_pcm_dshare_open
DATAB(__snd_pcm_dshare_open_dlsym_pcm_001, 4)
// _snd_pcm_dsnoop_open
// snd_pcm_dsnoop_open
DATAB(__snd_pcm_dsnoop_open_dlsym_pcm_001, 4)
// snd_pcm_dump
// snd_pcm_dump_hw_setup
// snd_pcm_dump_setup
// snd_pcm_dump_sw_setup
// _snd_pcm_empty_open
DATAB(__snd_pcm_empty_open_dlsym_pcm_001, 4)
// snd_pcm_extplug_create
// snd_pcm_extplug_delete
// snd_pcm_extplug_params_reset
// snd_pcm_extplug_set_param_list
// snd_pcm_extplug_set_param_minmax
// snd_pcm_extplug_set_slave_param_list
// snd_pcm_extplug_set_slave_param_minmax
// _snd_pcm_file_open
// snd_pcm_file_open
DATAB(__snd_pcm_file_open_dlsym_pcm_001, 4)
// snd_pcm_format_big_endian
// snd_pcm_format_cpu_endian
// snd_pcm_format_description
// snd_pcm_format_float
// snd_pcm_format_linear
// snd_pcm_format_little_endian
// snd_pcm_format_mask_any
// snd_pcm_format_mask_copy
// snd_pcm_format_mask_empty
// snd_pcm_format_mask_free
// snd_pcm_format_mask_malloc
// snd_pcm_format_mask_none
// snd_pcm_format_mask_reset
// snd_pcm_format_mask_set
// snd_pcm_format_mask_sizeof
// snd_pcm_format_mask_test
// snd_pcm_format_name
// snd_pcm_format_physical_width
// snd_pcm_format_set_silence
// snd_pcm_format_signed
// snd_pcm_format_silence
// snd_pcm_format_silence_16
// snd_pcm_format_silence_32
// snd_pcm_format_silence_64
// snd_pcm_format_size
// snd_pcm_format_unsigned
// snd_pcm_format_value
// snd_pcm_format_width
// snd_pcm_forward
// snd_pcm_forwardable
// snd_pcm_frames_to_bytes
// snd_pcm_free_chmaps
// snd_pcm_generic_htimestamp
// snd_pcm_generic_real_htimestamp
// snd_pcm_get_chmap
// snd_pcm_get_params
// snd_pcm_hook_add
// _snd_pcm_hook_ctl_elems_install
DATAB(__snd_pcm_hook_ctl_elems_install_dlsym_pcm_001, 4)
// snd_pcm_hook_get_pcm
// snd_pcm_hook_get_private
// snd_pcm_hook_remove
// snd_pcm_hook_set_private
// _snd_pcm_hooks_open
// snd_pcm_hooks_open
DATAB(__snd_pcm_hooks_open_dlsym_pcm_001, 4)
// snd_pcm_htimestamp
// snd_pcm_hw_fast_tstamp
// snd_pcm_hw_free
// _snd_pcm_hw_open
// snd_pcm_hw_open
DATAB(__snd_pcm_hw_open_dlsym_pcm_001, 4)
// snd_pcm_hw_param_dump
// snd_pcm_hw_params
// snd_pcm_hw_params_any
// snd_pcm_hw_params_can_disable_period_wakeup
// snd_pcm_hw_params_can_mmap_sample_resolution
// snd_pcm_hw_params_can_overrange
// snd_pcm_hw_params_can_pause
// snd_pcm_hw_params_can_resume
// snd_pcm_hw_params_can_sync_start
// snd_pcm_hw_params_copy
// snd_pcm_hw_params_current
// snd_pcm_hw_params_dump
// snd_pcm_hw_params_free
// __snd_pcm_hw_params_get_access
// snd_pcm_hw_params_get_access
// snd_pcm_hw_params_get_access
// snd_pcm_hw_params_get_access_mask
// __snd_pcm_hw_params_get_buffer_size
// snd_pcm_hw_params_get_buffer_size
// snd_pcm_hw_params_get_buffer_size
// __snd_pcm_hw_params_get_buffer_size_max
// snd_pcm_hw_params_get_buffer_size_max
// snd_pcm_hw_params_get_buffer_size_max
// __snd_pcm_hw_params_get_buffer_size_min
// snd_pcm_hw_params_get_buffer_size_min
// snd_pcm_hw_params_get_buffer_size_min
// __snd_pcm_hw_params_get_buffer_time
// snd_pcm_hw_params_get_buffer_time
// snd_pcm_hw_params_get_buffer_time
// __snd_pcm_hw_params_get_buffer_time_max
// snd_pcm_hw_params_get_buffer_time_max
// snd_pcm_hw_params_get_buffer_time_max
// __snd_pcm_hw_params_get_buffer_time_min
// snd_pcm_hw_params_get_buffer_time_min
// snd_pcm_hw_params_get_buffer_time_min
// __snd_pcm_hw_params_get_channels
// snd_pcm_hw_params_get_channels
// snd_pcm_hw_params_get_channels
// __snd_pcm_hw_params_get_channels_max
// snd_pcm_hw_params_get_channels_max
// snd_pcm_hw_params_get_channels_max
// __snd_pcm_hw_params_get_channels_min
// snd_pcm_hw_params_get_channels_min
// snd_pcm_hw_params_get_channels_min
// snd_pcm_hw_params_get_export_buffer
// snd_pcm_hw_params_get_fifo_size
// __snd_pcm_hw_params_get_format
// snd_pcm_hw_params_get_format
// snd_pcm_hw_params_get_format
// snd_pcm_hw_params_get_format_mask
// snd_pcm_hw_params_get_min_align
// __snd_pcm_hw_params_get_periods
// snd_pcm_hw_params_get_periods
// snd_pcm_hw_params_get_periods
// __snd_pcm_hw_params_get_period_size
// snd_pcm_hw_params_get_period_size
// snd_pcm_hw_params_get_period_size
// __snd_pcm_hw_params_get_period_size_max
// snd_pcm_hw_params_get_period_size_max
// snd_pcm_hw_params_get_period_size_max
// __snd_pcm_hw_params_get_period_size_min
// snd_pcm_hw_params_get_period_size_min
// snd_pcm_hw_params_get_period_size_min
// __snd_pcm_hw_params_get_periods_max
// snd_pcm_hw_params_get_periods_max
// snd_pcm_hw_params_get_periods_max
// __snd_pcm_hw_params_get_periods_min
// snd_pcm_hw_params_get_periods_min
// snd_pcm_hw_params_get_periods_min
// __snd_pcm_hw_params_get_period_time
// snd_pcm_hw_params_get_period_time
// snd_pcm_hw_params_get_period_time
// __snd_pcm_hw_params_get_period_time_max
// snd_pcm_hw_params_get_period_time_max
// snd_pcm_hw_params_get_period_time_max
// __snd_pcm_hw_params_get_period_time_min
// snd_pcm_hw_params_get_period_time_min
// snd_pcm_hw_params_get_period_time_min
// snd_pcm_hw_params_get_period_wakeup
// __snd_pcm_hw_params_get_rate
// snd_pcm_hw_params_get_rate
// snd_pcm_hw_params_get_rate
// __snd_pcm_hw_params_get_rate_max
// snd_pcm_hw_params_get_rate_max
// snd_pcm_hw_params_get_rate_max
// __snd_pcm_hw_params_get_rate_min
// snd_pcm_hw_params_get_rate_min
// snd_pcm_hw_params_get_rate_min
// snd_pcm_hw_params_get_rate_numden
// snd_pcm_hw_params_get_rate_resample
// snd_pcm_hw_params_get_sbits
// __snd_pcm_hw_params_get_subformat
// snd_pcm_hw_params_get_subformat
// snd_pcm_hw_params_get_subformat
// snd_pcm_hw_params_get_subformat_mask
// __snd_pcm_hw_params_get_tick_time
// snd_pcm_hw_params_get_tick_time
// snd_pcm_hw_params_get_tick_time
// __snd_pcm_hw_params_get_tick_time_max
// snd_pcm_hw_params_get_tick_time_max
// snd_pcm_hw_params_get_tick_time_max
// __snd_pcm_hw_params_get_tick_time_min
// snd_pcm_hw_params_get_tick_time_min
// snd_pcm_hw_params_get_tick_time_min
// snd_pcm_hw_params_is_batch
// snd_pcm_hw_params_is_block_transfer
// snd_pcm_hw_params_is_double
// snd_pcm_hw_params_is_half_duplex
// snd_pcm_hw_params_is_joint_duplex
// snd_pcm_hw_params_is_monotonic
// snd_pcm_hw_params_malloc
// snd_pcm_hw_params_set_access
// __snd_pcm_hw_params_set_access_first
// snd_pcm_hw_params_set_access_first
// snd_pcm_hw_params_set_access_first
// __snd_pcm_hw_params_set_access_last
// snd_pcm_hw_params_set_access_last
// snd_pcm_hw_params_set_access_last
// snd_pcm_hw_params_set_access_mask
// snd_pcm_hw_params_set_buffer_size
// __snd_pcm_hw_params_set_buffer_size_first
// snd_pcm_hw_params_set_buffer_size_first
// snd_pcm_hw_params_set_buffer_size_first
// __snd_pcm_hw_params_set_buffer_size_last
// snd_pcm_hw_params_set_buffer_size_last
// snd_pcm_hw_params_set_buffer_size_last
// snd_pcm_hw_params_set_buffer_size_max
// snd_pcm_hw_params_set_buffer_size_min
// snd_pcm_hw_params_set_buffer_size_minmax
// __snd_pcm_hw_params_set_buffer_size_near
// snd_pcm_hw_params_set_buffer_size_near
// snd_pcm_hw_params_set_buffer_size_near
// snd_pcm_hw_params_set_buffer_time
// __snd_pcm_hw_params_set_buffer_time_first
// snd_pcm_hw_params_set_buffer_time_first
// snd_pcm_hw_params_set_buffer_time_first
// __snd_pcm_hw_params_set_buffer_time_last
// snd_pcm_hw_params_set_buffer_time_last
// snd_pcm_hw_params_set_buffer_time_last
// snd_pcm_hw_params_set_buffer_time_max
// snd_pcm_hw_params_set_buffer_time_min
// snd_pcm_hw_params_set_buffer_time_minmax
// __snd_pcm_hw_params_set_buffer_time_near
// snd_pcm_hw_params_set_buffer_time_near
// snd_pcm_hw_params_set_buffer_time_near
// snd_pcm_hw_params_set_channels
// __snd_pcm_hw_params_set_channels_first
// snd_pcm_hw_params_set_channels_first
// snd_pcm_hw_params_set_channels_first
// __snd_pcm_hw_params_set_channels_last
// snd_pcm_hw_params_set_channels_last
// snd_pcm_hw_params_set_channels_last
// snd_pcm_hw_params_set_channels_max
// snd_pcm_hw_params_set_channels_min
// snd_pcm_hw_params_set_channels_minmax
// __snd_pcm_hw_params_set_channels_near
// snd_pcm_hw_params_set_channels_near
// snd_pcm_hw_params_set_channels_near
// snd_pcm_hw_params_set_export_buffer
// snd_pcm_hw_params_set_format
// __snd_pcm_hw_params_set_format_first
// snd_pcm_hw_params_set_format_first
// snd_pcm_hw_params_set_format_first
// __snd_pcm_hw_params_set_format_last
// snd_pcm_hw_params_set_format_last
// snd_pcm_hw_params_set_format_last
// snd_pcm_hw_params_set_format_mask
// snd_pcm_hw_params_set_periods
// __snd_pcm_hw_params_set_periods_first
// snd_pcm_hw_params_set_periods_first
// snd_pcm_hw_params_set_periods_first
// snd_pcm_hw_params_set_periods_integer
// snd_pcm_hw_params_set_period_size
// __snd_pcm_hw_params_set_period_size_first
// snd_pcm_hw_params_set_period_size_first
// snd_pcm_hw_params_set_period_size_first
// snd_pcm_hw_params_set_period_size_integer
// __snd_pcm_hw_params_set_period_size_last
// snd_pcm_hw_params_set_period_size_last
// snd_pcm_hw_params_set_period_size_last
// snd_pcm_hw_params_set_period_size_max
// snd_pcm_hw_params_set_period_size_min
// snd_pcm_hw_params_set_period_size_minmax
// __snd_pcm_hw_params_set_period_size_near
// snd_pcm_hw_params_set_period_size_near
// snd_pcm_hw_params_set_period_size_near
// __snd_pcm_hw_params_set_periods_last
// snd_pcm_hw_params_set_periods_last
// snd_pcm_hw_params_set_periods_last
// snd_pcm_hw_params_set_periods_max
// snd_pcm_hw_params_set_periods_min
// snd_pcm_hw_params_set_periods_minmax
// __snd_pcm_hw_params_set_periods_near
// snd_pcm_hw_params_set_periods_near
// snd_pcm_hw_params_set_periods_near
// snd_pcm_hw_params_set_period_time
// __snd_pcm_hw_params_set_period_time_first
// snd_pcm_hw_params_set_period_time_first
// snd_pcm_hw_params_set_period_time_first
// __snd_pcm_hw_params_set_period_time_last
// snd_pcm_hw_params_set_period_time_last
// snd_pcm_hw_params_set_period_time_last
// snd_pcm_hw_params_set_period_time_max
// snd_pcm_hw_params_set_period_time_min
// snd_pcm_hw_params_set_period_time_minmax
// __snd_pcm_hw_params_set_period_time_near
// snd_pcm_hw_params_set_period_time_near
// snd_pcm_hw_params_set_period_time_near
// snd_pcm_hw_params_set_period_wakeup
// snd_pcm_hw_params_set_rate
// __snd_pcm_hw_params_set_rate_first
// snd_pcm_hw_params_set_rate_first
// snd_pcm_hw_params_set_rate_first
// __snd_pcm_hw_params_set_rate_last
// snd_pcm_hw_params_set_rate_last
// snd_pcm_hw_params_set_rate_last
// snd_pcm_hw_params_set_rate_max
// snd_pcm_hw_params_set_rate_min
// snd_pcm_hw_params_set_rate_minmax
// __snd_pcm_hw_params_set_rate_near
// snd_pcm_hw_params_set_rate_near
// snd_pcm_hw_params_set_rate_near
// snd_pcm_hw_params_set_rate_resample
// snd_pcm_hw_params_set_subformat
// __snd_pcm_hw_params_set_subformat_first
// snd_pcm_hw_params_set_subformat_first
// snd_pcm_hw_params_set_subformat_first
// __snd_pcm_hw_params_set_subformat_last
// snd_pcm_hw_params_set_subformat_last
// snd_pcm_hw_params_set_subformat_last
// snd_pcm_hw_params_set_subformat_mask
// snd_pcm_hw_params_set_tick_time
// __snd_pcm_hw_params_set_tick_time_first
// snd_pcm_hw_params_set_tick_time_first
// snd_pcm_hw_params_set_tick_time_first
// __snd_pcm_hw_params_set_tick_time_last
// snd_pcm_hw_params_set_tick_time_last
// snd_pcm_hw_params_set_tick_time_last
// snd_pcm_hw_params_set_tick_time_max
// snd_pcm_hw_params_set_tick_time_min
// snd_pcm_hw_params_set_tick_time_minmax
// __snd_pcm_hw_params_set_tick_time_near
// snd_pcm_hw_params_set_tick_time_near
// snd_pcm_hw_params_set_tick_time_near
// snd_pcm_hw_params_sizeof
// snd_pcm_hw_params_supports_audio_wallclock_ts
// snd_pcm_hw_params_test_access
// snd_pcm_hw_params_test_buffer_size
// snd_pcm_hw_params_test_buffer_time
// snd_pcm_hw_params_test_channels
// snd_pcm_hw_params_test_format
// snd_pcm_hw_params_test_periods
// snd_pcm_hw_params_test_period_size
// snd_pcm_hw_params_test_period_time
// snd_pcm_hw_params_test_rate
// snd_pcm_hw_params_test_subformat
// snd_pcm_hw_params_test_tick_time
// snd_pcm_hw_refine
// snd_pcm_hw_set_hack_params
// snd_pcm_hwsync
// _snd_pcm_iec958_open
// snd_pcm_iec958_open
DATAB(__snd_pcm_iec958_open_dlsym_pcm_001, 4)
// snd_pcm_info
// snd_pcm_info_copy
// snd_pcm_info_free
// snd_pcm_info_get_card
// snd_pcm_info_get_class
// snd_pcm_info_get_device
// snd_pcm_info_get_id
// snd_pcm_info_get_name
// snd_pcm_info_get_stream
// snd_pcm_info_get_subclass
// snd_pcm_info_get_subdevice
// snd_pcm_info_get_subdevice_name
// snd_pcm_info_get_subdevices_avail
// snd_pcm_info_get_subdevices_count
// snd_pcm_info_get_sync
// snd_pcm_info_malloc
// snd_pcm_info_set_device
// snd_pcm_info_set_stream
// snd_pcm_info_set_subdevice
// snd_pcm_info_sizeof
// snd_pcm_ioplug_create
// snd_pcm_ioplug_delete
// snd_pcm_ioplug_mmap_areas
// snd_pcm_ioplug_params_reset
// snd_pcm_ioplug_reinit_status
// snd_pcm_ioplug_set_param_list
// snd_pcm_ioplug_set_param_minmax
// snd_pcm_ioplug_set_state
// _snd_pcm_ladspa_open
// snd_pcm_ladspa_open
DATAB(__snd_pcm_ladspa_open_dlsym_pcm_001, 4)
// snd_pcm_lfloat_convert_float_integer
// snd_pcm_lfloat_convert_integer_float
// snd_pcm_lfloat_get_s32_index
// _snd_pcm_lfloat_open
// snd_pcm_lfloat_open
DATAB(__snd_pcm_lfloat_open_dlsym_pcm_001, 4)
// snd_pcm_lfloat_put_s32_index
// _snd_pcm_linear_open
// snd_pcm_linear_open
DATAB(__snd_pcm_linear_open_dlsym_pcm_001, 4)
// snd_pcm_link
// snd_pcm_mmap
// snd_pcm_mmap_begin
// snd_pcm_mmap_commit
// _snd_pcm_mmap_emul_open
DATAB(__snd_pcm_mmap_emul_open_dlsym_pcm_001, 4)
// snd_pcm_mmap_readi
// snd_pcm_mmap_readn
// snd_pcm_mmap_writei
// snd_pcm_mmap_writen
// _snd_pcm_mulaw_open
// snd_pcm_mulaw_open
DATAB(__snd_pcm_mulaw_open_dlsym_pcm_001, 4)
// _snd_pcm_multi_open
// snd_pcm_multi_open
DATAB(__snd_pcm_multi_open_dlsym_pcm_001, 4)
// snd_pcm_munmap
// snd_pcm_name
// snd_pcm_nonblock
// _snd_pcm_null_open
// snd_pcm_null_open
DATAB(__snd_pcm_null_open_dlsym_pcm_001, 4)
// snd_pcm_open
// snd_pcm_open_fallback
// snd_pcm_open_lconf
// snd_pcm_parse_control_id
// snd_pcm_pause
// _snd_pcm_plug_open
// snd_pcm_plug_open
DATAB(__snd_pcm_plug_open_dlsym_pcm_001, 4)
// _snd_pcm_poll_descriptor
// snd_pcm_poll_descriptors
// snd_pcm_poll_descriptors_count
// snd_pcm_poll_descriptors_revents
// snd_pcm_prepare
// snd_pcm_query_chmaps
// snd_pcm_query_chmaps_from_hw
// _snd_pcm_rate_linear_open
// _snd_pcm_rate_open
// snd_pcm_rate_open
DATAB(__snd_pcm_rate_open_dlsym_pcm_001, 4)
// snd_pcm_readi
// snd_pcm_readn
// snd_pcm_recover
// snd_pcm_reset
// snd_pcm_resume
// snd_pcm_rewind
// snd_pcm_rewindable
// snd_pcm_route_determine_ttable
// snd_pcm_route_load_ttable
// _snd_pcm_route_open
// snd_pcm_route_open
DATAB(__snd_pcm_route_open_dlsym_pcm_001, 4)
// snd_pcm_samples_to_bytes
// snd_pcm_set_chmap
// snd_pcm_set_params
// _snd_pcm_share_open
// snd_pcm_share_open
DATAB(__snd_pcm_share_open_dlsym_pcm_001, 4)
// _snd_pcm_shm_open
// snd_pcm_shm_open
DATAB(__snd_pcm_shm_open_dlsym_pcm_001, 4)
// snd_pcm_slave_conf
// _snd_pcm_softvol_open
// snd_pcm_softvol_open
DATAB(__snd_pcm_softvol_open_dlsym_pcm_001, 4)
// snd_pcm_start
// snd_pcm_start_mode_name
// snd_pcm_state
// snd_pcm_state_name
// snd_pcm_status
// snd_pcm_status_copy
// snd_pcm_status_dump
// snd_pcm_status_free
// snd_pcm_status_get_audio_htstamp
// snd_pcm_status_get_avail
// snd_pcm_status_get_avail_max
// snd_pcm_status_get_delay
// snd_pcm_status_get_htstamp
// snd_pcm_status_get_overrange
// snd_pcm_status_get_state
// snd_pcm_status_get_trigger_htstamp
// snd_pcm_status_get_trigger_tstamp
// snd_pcm_status_get_tstamp
// snd_pcm_status_malloc
// snd_pcm_status_sizeof
// snd_pcm_stream
// snd_pcm_stream_name
// snd_pcm_subformat_description
// snd_pcm_subformat_mask_any
// snd_pcm_subformat_mask_copy
// snd_pcm_subformat_mask_empty
// snd_pcm_subformat_mask_free
// snd_pcm_subformat_mask_malloc
// snd_pcm_subformat_mask_none
// snd_pcm_subformat_mask_reset
// snd_pcm_subformat_mask_set
// snd_pcm_subformat_mask_sizeof
// snd_pcm_subformat_mask_test
// snd_pcm_subformat_name
// snd_pcm_sw_params
// snd_pcm_sw_params_copy
// snd_pcm_sw_params_current
// snd_pcm_sw_params_dump
// snd_pcm_sw_params_free
// __snd_pcm_sw_params_get_avail_min
// snd_pcm_sw_params_get_avail_min
// snd_pcm_sw_params_get_avail_min
// snd_pcm_sw_params_get_boundary
// snd_pcm_sw_params_get_period_event
// __snd_pcm_sw_params_get_silence_size
// snd_pcm_sw_params_get_silence_size
// snd_pcm_sw_params_get_silence_size
// __snd_pcm_sw_params_get_silence_threshold
// snd_pcm_sw_params_get_silence_threshold
// snd_pcm_sw_params_get_silence_threshold
// __snd_pcm_sw_params_get_sleep_min
// snd_pcm_sw_params_get_sleep_min
// snd_pcm_sw_params_get_sleep_min
// snd_pcm_sw_params_get_start_mode
// __snd_pcm_sw_params_get_start_threshold
// snd_pcm_sw_params_get_start_threshold
// snd_pcm_sw_params_get_start_threshold
// __snd_pcm_sw_params_get_stop_threshold
// snd_pcm_sw_params_get_stop_threshold
// snd_pcm_sw_params_get_stop_threshold
// __snd_pcm_sw_params_get_tstamp_mode
// snd_pcm_sw_params_get_tstamp_mode
// snd_pcm_sw_params_get_tstamp_mode
// __snd_pcm_sw_params_get_xfer_align
// snd_pcm_sw_params_get_xfer_align
// snd_pcm_sw_params_get_xfer_align
// snd_pcm_sw_params_get_xrun_mode
// snd_pcm_sw_params_malloc
// snd_pcm_sw_params_set_avail_min
// snd_pcm_sw_params_set_period_event
// snd_pcm_sw_params_set_silence_size
// snd_pcm_sw_params_set_silence_threshold
// snd_pcm_sw_params_set_sleep_min
// snd_pcm_sw_params_set_start_mode
// snd_pcm_sw_params_set_start_threshold
// snd_pcm_sw_params_set_stop_threshold
// snd_pcm_sw_params_set_tstamp_mode
// snd_pcm_sw_params_set_xfer_align
// snd_pcm_sw_params_set_xrun_mode
// snd_pcm_sw_params_sizeof
// snd_pcm_tstamp_mode_name
// snd_pcm_type
// snd_pcm_type_name
// snd_pcm_unlink
// snd_pcm_wait
// snd_pcm_writei
// snd_pcm_writen
// snd_pcm_xrun_mode_name
// snd_rawmidi_close
// snd_rawmidi_conf_generic_id
// snd_rawmidi_drain
// snd_rawmidi_drop
// _snd_rawmidi_hw_open
// snd_rawmidi_hw_open
DATAB(__snd_rawmidi_hw_open_dlsym_rawmidi_001, 4)
// snd_rawmidi_info
// snd_rawmidi_info_copy
// snd_rawmidi_info_free
// snd_rawmidi_info_get_card
// snd_rawmidi_info_get_device
// snd_rawmidi_info_get_flags
// snd_rawmidi_info_get_id
// snd_rawmidi_info_get_name
// snd_rawmidi_info_get_stream
// snd_rawmidi_info_get_subdevice
// snd_rawmidi_info_get_subdevice_name
// snd_rawmidi_info_get_subdevices_avail
// snd_rawmidi_info_get_subdevices_count
// snd_rawmidi_info_malloc
// snd_rawmidi_info_set_device
// snd_rawmidi_info_set_stream
// snd_rawmidi_info_set_subdevice
// snd_rawmidi_info_sizeof
// snd_rawmidi_name
// snd_rawmidi_nonblock
// snd_rawmidi_open
// snd_rawmidi_open_lconf
// snd_rawmidi_params
// snd_rawmidi_params_copy
// snd_rawmidi_params_current
// snd_rawmidi_params_free
// snd_rawmidi_params_get_avail_min
// snd_rawmidi_params_get_buffer_size
// snd_rawmidi_params_get_no_active_sensing
// snd_rawmidi_params_malloc
// snd_rawmidi_params_set_avail_min
// snd_rawmidi_params_set_buffer_size
// snd_rawmidi_params_set_no_active_sensing
// snd_rawmidi_params_sizeof
// snd_rawmidi_poll_descriptors
// snd_rawmidi_poll_descriptors_count
// snd_rawmidi_poll_descriptors_revents
// snd_rawmidi_read
// snd_rawmidi_status
// snd_rawmidi_status_copy
// snd_rawmidi_status_free
// snd_rawmidi_status_get_avail
// snd_rawmidi_status_get_tstamp
// snd_rawmidi_status_get_xruns
// snd_rawmidi_status_malloc
// snd_rawmidi_status_sizeof
// snd_rawmidi_stream
// snd_rawmidi_type
// _snd_rawmidi_virtual_open
// snd_rawmidi_virtual_open
DATAB(__snd_rawmidi_virtual_open_dlsym_rawmidi_001, 4)
// snd_rawmidi_write
// snd_receive_fd
// snd_sctl_build
// snd_sctl_free
// snd_sctl_install
// snd_sctl_remove
// snd_send_fd
// snd_seq_alloc_named_queue
// snd_seq_alloc_queue
// snd_seq_change_bit
// snd_seq_client_id
// snd_seq_client_info_copy
// snd_seq_client_info_event_filter_add
// snd_seq_client_info_event_filter_check
// snd_seq_client_info_event_filter_clear
// snd_seq_client_info_event_filter_del
// snd_seq_client_info_free
// snd_seq_client_info_get_broadcast_filter
// snd_seq_client_info_get_client
// snd_seq_client_info_get_error_bounce
// snd_seq_client_info_get_event_filter
// snd_seq_client_info_get_event_lost
// snd_seq_client_info_get_name
// snd_seq_client_info_get_num_ports
// snd_seq_client_info_get_type
// snd_seq_client_info_malloc
// snd_seq_client_info_set_broadcast_filter
// snd_seq_client_info_set_client
// snd_seq_client_info_set_error_bounce
// snd_seq_client_info_set_event_filter
// snd_seq_client_info_set_name
// snd_seq_client_info_sizeof
// snd_seq_client_pool_copy
// snd_seq_client_pool_free
// snd_seq_client_pool_get_client
// snd_seq_client_pool_get_input_free
// snd_seq_client_pool_get_input_pool
// snd_seq_client_pool_get_output_free
// snd_seq_client_pool_get_output_pool
// snd_seq_client_pool_get_output_room
// snd_seq_client_pool_malloc
// snd_seq_client_pool_set_input_pool
// snd_seq_client_pool_set_output_pool
// snd_seq_client_pool_set_output_room
// snd_seq_client_pool_sizeof
// snd_seq_close
// snd_seq_connect_from
// snd_seq_connect_to
// snd_seq_control_queue
// snd_seq_create_event
// snd_seq_create_port
// snd_seq_create_queue
// snd_seq_create_simple_port
// snd_seq_delete_port
// snd_seq_delete_simple_port
// snd_seq_disconnect_from
// snd_seq_disconnect_to
// snd_seq_drain_output
// snd_seq_drop_input
// snd_seq_drop_input_buffer
// snd_seq_drop_output
// snd_seq_drop_output_buffer
// snd_seq_event_input
// snd_seq_event_input_pending
// snd_seq_event_length
// snd_seq_event_output
// snd_seq_event_output_buffer
// snd_seq_event_output_direct
// snd_seq_event_output_pending
// snd_seq_event_types  // type R
// snd_seq_extract_output
// snd_seq_free_event
// snd_seq_free_queue
// snd_seq_get_any_client_info
// snd_seq_get_any_port_info
// snd_seq_get_bit
// snd_seq_get_client_info
// snd_seq_get_client_pool
// snd_seq_get_input_buffer_size
// snd_seq_get_output_buffer_size
// snd_seq_get_port_info
// snd_seq_get_port_subscription
// snd_seq_get_queue_info
// snd_seq_get_queue_status
// snd_seq_get_queue_tempo
// snd_seq_get_queue_timer
// snd_seq_get_queue_usage
// _snd_seq_hw_open
// snd_seq_hw_open
DATAB(__snd_seq_hw_open_dlsym_seq_001, 4)
// snd_seq_name
// snd_seq_nonblock
// snd_seq_open
// snd_seq_open_lconf
// snd_seq_parse_address
// snd_seq_poll_descriptors
// snd_seq_poll_descriptors_count
// snd_seq_poll_descriptors_revents
// snd_seq_port_info_copy
// snd_seq_port_info_free
// snd_seq_port_info_get_addr
// snd_seq_port_info_get_capability
// snd_seq_port_info_get_client
// snd_seq_port_info_get_midi_channels
// snd_seq_port_info_get_midi_voices
// snd_seq_port_info_get_name
// snd_seq_port_info_get_port
// snd_seq_port_info_get_port_specified
// snd_seq_port_info_get_read_use
// snd_seq_port_info_get_synth_voices
// snd_seq_port_info_get_timestamping
// snd_seq_port_info_get_timestamp_queue
// snd_seq_port_info_get_timestamp_real
// snd_seq_port_info_get_type
// snd_seq_port_info_get_write_use
// snd_seq_port_info_malloc
// snd_seq_port_info_set_addr
// snd_seq_port_info_set_capability
// snd_seq_port_info_set_client
// snd_seq_port_info_set_midi_channels
// snd_seq_port_info_set_midi_voices
// snd_seq_port_info_set_name
// snd_seq_port_info_set_port
// snd_seq_port_info_set_port_specified
// snd_seq_port_info_set_synth_voices
// snd_seq_port_info_set_timestamping
// snd_seq_port_info_set_timestamp_queue
// snd_seq_port_info_set_timestamp_real
// snd_seq_port_info_set_type
// snd_seq_port_info_sizeof
// snd_seq_port_subscribe_copy
// snd_seq_port_subscribe_free
// snd_seq_port_subscribe_get_dest
// snd_seq_port_subscribe_get_exclusive
// snd_seq_port_subscribe_get_queue
// snd_seq_port_subscribe_get_sender
// snd_seq_port_subscribe_get_time_real
// snd_seq_port_subscribe_get_time_update
// snd_seq_port_subscribe_malloc
// snd_seq_port_subscribe_set_dest
// snd_seq_port_subscribe_set_exclusive
// snd_seq_port_subscribe_set_queue
// snd_seq_port_subscribe_set_sender
// snd_seq_port_subscribe_set_time_real
// snd_seq_port_subscribe_set_time_update
// snd_seq_port_subscribe_sizeof
// snd_seq_query_named_queue
// snd_seq_query_next_client
// snd_seq_query_next_port
// snd_seq_query_port_subscribers
// snd_seq_query_subscribe_copy
// snd_seq_query_subscribe_free
// snd_seq_query_subscribe_get_addr
// snd_seq_query_subscribe_get_client
// snd_seq_query_subscribe_get_exclusive
// snd_seq_query_subscribe_get_index
// snd_seq_query_subscribe_get_num_subs
// snd_seq_query_subscribe_get_port
// snd_seq_query_subscribe_get_queue
// snd_seq_query_subscribe_get_root
// snd_seq_query_subscribe_get_time_real
// snd_seq_query_subscribe_get_time_update
// snd_seq_query_subscribe_get_type
// snd_seq_query_subscribe_malloc
// snd_seq_query_subscribe_set_client
// snd_seq_query_subscribe_set_index
// snd_seq_query_subscribe_set_port
// snd_seq_query_subscribe_set_root
// snd_seq_query_subscribe_set_type
// snd_seq_query_subscribe_sizeof
// snd_seq_queue_info_copy
// snd_seq_queue_info_free
// snd_seq_queue_info_get_flags
// snd_seq_queue_info_get_locked
// snd_seq_queue_info_get_name
// snd_seq_queue_info_get_owner
// snd_seq_queue_info_get_queue
// snd_seq_queue_info_malloc
// snd_seq_queue_info_set_flags
// snd_seq_queue_info_set_locked
// snd_seq_queue_info_set_name
// snd_seq_queue_info_set_owner
// snd_seq_queue_info_sizeof
// snd_seq_queue_status_copy
// snd_seq_queue_status_free
// snd_seq_queue_status_get_events
// snd_seq_queue_status_get_queue
// snd_seq_queue_status_get_real_time
// snd_seq_queue_status_get_status
// snd_seq_queue_status_get_tick_time
// snd_seq_queue_status_malloc
// snd_seq_queue_status_sizeof
// snd_seq_queue_tempo_copy
// snd_seq_queue_tempo_free
// snd_seq_queue_tempo_get_ppq
// snd_seq_queue_tempo_get_queue
// snd_seq_queue_tempo_get_skew
// snd_seq_queue_tempo_get_skew_base
// snd_seq_queue_tempo_get_tempo
// snd_seq_queue_tempo_malloc
// snd_seq_queue_tempo_set_ppq
// snd_seq_queue_tempo_set_skew
// snd_seq_queue_tempo_set_skew_base
// snd_seq_queue_tempo_set_tempo
// snd_seq_queue_tempo_sizeof
// snd_seq_queue_timer_copy
// snd_seq_queue_timer_free
// snd_seq_queue_timer_get_id
// snd_seq_queue_timer_get_queue
// snd_seq_queue_timer_get_resolution
// snd_seq_queue_timer_get_type
// snd_seq_queue_timer_malloc
// snd_seq_queue_timer_set_id
// snd_seq_queue_timer_set_resolution
// snd_seq_queue_timer_set_type
// snd_seq_queue_timer_sizeof
// snd_seq_remove_events
// snd_seq_remove_events_copy
// snd_seq_remove_events_free
// snd_seq_remove_events_get_channel
// snd_seq_remove_events_get_condition
// snd_seq_remove_events_get_dest
// snd_seq_remove_events_get_event_type
// snd_seq_remove_events_get_queue
// snd_seq_remove_events_get_tag
// snd_seq_remove_events_get_time
// snd_seq_remove_events_malloc
// snd_seq_remove_events_set_channel
// snd_seq_remove_events_set_condition
// snd_seq_remove_events_set_dest
// snd_seq_remove_events_set_event_type
// snd_seq_remove_events_set_queue
// snd_seq_remove_events_set_tag
// snd_seq_remove_events_set_time
// snd_seq_remove_events_sizeof
// snd_seq_reset_pool_input
// snd_seq_reset_pool_output
// snd_seq_set_bit
// snd_seq_set_client_event_filter
// snd_seq_set_client_info
// snd_seq_set_client_name
// snd_seq_set_client_pool
// snd_seq_set_client_pool_input
// snd_seq_set_client_pool_output
// snd_seq_set_client_pool_output_room
// snd_seq_set_input_buffer_size
// snd_seq_set_output_buffer_size
// snd_seq_set_port_info
// snd_seq_set_queue_info
// snd_seq_set_queue_tempo
// snd_seq_set_queue_timer
// snd_seq_set_queue_usage
// snd_seq_subscribe_port
// snd_seq_sync_output_queue
// snd_seq_system_info
// snd_seq_system_info_copy
// snd_seq_system_info_free
// snd_seq_system_info_get_channels
// snd_seq_system_info_get_clients
// snd_seq_system_info_get_cur_clients
// snd_seq_system_info_get_cur_queues
// snd_seq_system_info_get_ports
// snd_seq_system_info_get_queues
// snd_seq_system_info_malloc
// snd_seq_system_info_sizeof
// snd_seq_type
// snd_seq_unset_bit
// snd_seq_unsubscribe_port
GO(snd_shm_area_create, pFip)
GO(snd_shm_area_destroy, iFp)
// snd_shm_area_destructor
GO(snd_shm_area_share, pFp)
// snd_spcm_init
// snd_spcm_init_duplex
// snd_spcm_init_get_params
// snd_strerror
// snd_timer_async
// snd_timer_close
// snd_timer_continue
// snd_timer_ginfo_copy
// snd_timer_ginfo_free
// snd_timer_ginfo_get_card
// snd_timer_ginfo_get_clients
// snd_timer_ginfo_get_flags
// snd_timer_ginfo_get_id
// snd_timer_ginfo_get_name
// snd_timer_ginfo_get_resolution
// snd_timer_ginfo_get_resolution_max
// snd_timer_ginfo_get_resolution_min
// snd_timer_ginfo_get_tid
// snd_timer_ginfo_malloc
// snd_timer_ginfo_set_tid
// snd_timer_ginfo_sizeof
// _snd_timer_hw_open
// snd_timer_hw_open
DATAB(__snd_timer_hw_open_dlsym_timer_001, 4)
// snd_timer_id_copy
// snd_timer_id_free
// snd_timer_id_get_card
// snd_timer_id_get_class
// snd_timer_id_get_device
// snd_timer_id_get_sclass
// snd_timer_id_get_subdevice
// snd_timer_id_malloc
// snd_timer_id_set_card
// snd_timer_id_set_class
// snd_timer_id_set_device
// snd_timer_id_set_sclass
// snd_timer_id_set_subdevice
// snd_timer_id_sizeof
// snd_timer_info
// snd_timer_info_copy
// snd_timer_info_free
// snd_timer_info_get_card
// snd_timer_info_get_id
// snd_timer_info_get_name
// snd_timer_info_get_resolution
// snd_timer_info_get_ticks
// snd_timer_info_is_slave
// snd_timer_info_malloc
// snd_timer_info_sizeof
// snd_timer_name
// snd_timer_nonblock
// snd_timer_open
// snd_timer_open_lconf
// snd_timer_params
// snd_timer_params_copy
// snd_timer_params_free
// snd_timer_params_get_auto_start
// snd_timer_params_get_early_event
// snd_timer_params_get_exclusive
// snd_timer_params_get_filter
// snd_timer_params_get_queue_size
// snd_timer_params_get_ticks
// snd_timer_params_malloc
// snd_timer_params_set_auto_start
// snd_timer_params_set_early_event
// snd_timer_params_set_exclusive
// snd_timer_params_set_filter
// snd_timer_params_set_queue_size
// snd_timer_params_set_ticks
// snd_timer_params_sizeof
// snd_timer_poll_descriptors
// snd_timer_poll_descriptors_count
// snd_timer_poll_descriptors_revents
// snd_timer_query_close
// _snd_timer_query_hw_open
// snd_timer_query_hw_open
DATAB(__snd_timer_query_hw_open_dlsym_timer_query_001, 4)
// snd_timer_query_info
// snd_timer_query_next_device
// snd_timer_query_open
// snd_timer_query_open_lconf
// snd_timer_query_params
// snd_timer_query_status
// snd_timer_read
// snd_timer_start
// snd_timer_status
// snd_timer_status_copy
// snd_timer_status_free
// snd_timer_status_get_lost
// snd_timer_status_get_overrun
// snd_timer_status_get_queue
// snd_timer_status_get_resolution
// snd_timer_status_get_timestamp
// snd_timer_status_malloc
// snd_timer_status_sizeof
// snd_timer_stop
// snd_timer_type
// snd_tlv_convert_from_dB
// snd_tlv_convert_to_dB
// snd_tlv_get_dB_range
// snd_tlv_parse_dB_info
// snd_use_case_free_list
// snd_use_case_get
// snd_use_case_geti
// snd_use_case_get_list
// snd_use_case_identifier
// snd_use_case_mgr_close
// snd_use_case_mgr_open
// snd_use_case_mgr_reload
// snd_use_case_mgr_reset
// snd_use_case_set
GO(snd_user_file, iFpp)

END()

#else
#error Mmmm...
#endif