#if defined(GO) && defined(GOM) && defined(GO2) && defined(DATA) && defined(END)

// _fini
// glAccum
// glActiveTexture
// glActiveTextureARB
// glAlphaFunc
// glAlphaFuncx
// glAreTexturesResident
// glArrayElement
// glArrayElementEXT
// glAttachObjectARB
// glAttachShader
// glBegin
// glBeginQuery
// glBeginQueryARB
// glBindAttribLocation
// glBindAttribLocationARB
// glBindBuffer
// glBindBufferARB
// glBindFramebuffer
// glBindFramebufferEXT
// glBindMultiTextureEXT
// glBindProgramARB
// glBindRenderbuffer
// glBindRenderbufferEXT
// glBindTexture
// glBindVertexArray
// glBitmap
// glBlendColor
// glBlendColorARB
// glBlendColorEXT
// glBlendEquation
// glBlendEquationEXT
// glBlendEquationSeparate
// glBlendEquationSeparateEXT
// glBlendFunc
// glBlendFuncSeparate
// glBlendFuncSeparateEXT
// glBlitFramebuffer
// glBlitFramebufferEXT
// glBufferData
// glBufferDataARB
// glBufferSubData
// glBufferSubDataARB
// glCallList
// glCallLists
// glCheckFramebufferStatus
// glCheckFramebufferStatusEXT
// glClampColorARB
// glClear
// glClearAccum
// glClearColor
// glClearColorx
// glClearDepth
// glClearDepthx
// glClearIndex
// glClearStencil
// glClientActiveTexture
// glClientActiveTextureARB
// glClientAttribDefaultEXT
// glClipPlane
// glClipPlanef
// glClipPlanex
// glColor3b
// glColor3bv
// glColor3d
// glColor3dv
// glColor3f
// glColor3fv
// glColor3i
// glColor3iv
// glColor3s
// glColor3sv
// glColor3ub
// glColor3ubv
// glColor3ui
// glColor3uiv
// glColor3us
// glColor3usv
// glColor4b
// glColor4bv
// glColor4d
// glColor4dv
// glColor4f
// glColor4fv
// glColor4i
// glColor4iv
// glColor4s
// glColor4sv
// glColor4ub
// glColor4ubv
// glColor4ui
// glColor4uiv
// glColor4us
// glColor4usv
// glColor4x
// glColorMask
// glColorMaterial
// glColorPointer
// glColorTable
// glCompileShader
// glCompileShaderARB
// glCompressedMultiTexImage1DEXT
// glCompressedMultiTexImage2DEXT
// glCompressedMultiTexImage3DEXT
// glCompressedMultiTexSubImage1DEXT
// glCompressedMultiTexSubImage2DEXT
// glCompressedMultiTexSubImage3DEXT
// glCompressedTexImage1D
// glCompressedTexImage1DARB
// glCompressedTexImage1DEXT
// glCompressedTexImage2D
// glCompressedTexImage2DARB
// glCompressedTexImage2DEXT
// glCompressedTexImage3D
// glCompressedTexImage3DARB
// glCompressedTexImage3DEXT
// glCompressedTexSubImage1D
// glCompressedTexSubImage1DARB
// glCompressedTexSubImage1DEXT
// glCompressedTexSubImage2D
// glCompressedTexSubImage2DARB
// glCompressedTexSubImage2DEXT
// glCompressedTexSubImage3D
// glCompressedTexSubImage3DARB
// glCompressedTexSubImage3DEXT
// glCompressedTextureImage1DEXT
// glCompressedTextureImage2DEXT
// glCompressedTextureImage3DEXT
// glCompressedTextureSubImage1DEXT
// glCompressedTextureSubImage2DEXT
// glCompressedTextureSubImage3DEXT
// glCopyMultiTexImage1DEXT
// glCopyMultiTexImage2DEXT
// glCopyMultiTexSubImage1DEXT
// glCopyMultiTexSubImage2DEXT
// glCopyMultiTexSubImage3DEXT
// glCopyPixels
// glCopyTexImage1D
// glCopyTexImage2D
// glCopyTexSubImage1D
// glCopyTexSubImage2D
// glCopyTexSubImage3D
// glCopyTexSubImage3DARB
// glCopyTexSubImage3DEXT
// glCopyTextureImage1DEXT
// glCopyTextureImage2DEXT
// glCopyTextureSubImage1DEXT
// glCopyTextureSubImage2DEXT
// glCopyTextureSubImage3DEXT
// glCreateProgram
// glCreateProgramObjectARB
// glCreateShader
// glCreateShaderObjectARB
// glCullFace
// glDeleteBuffers
// glDeleteBuffersARB
// glDeleteFramebuffers
// glDeleteFramebuffersEXT
// glDeleteLists
// glDeleteObjectARB
// glDeleteProgram
// glDeleteProgramsARB
// glDeleteQueries
// glDeleteQueriesARB
// glDeleteRenderbuffers
// glDeleteRenderbuffersEXT
// glDeleteShader
// glDeleteTextures
// glDeleteVertexArrays
// glDepthFunc
// glDepthMask
// glDepthRange
// glDepthRangef
// glDepthRangex
// glDetachObjectARB
// glDetachShader
// glDisable
// glDisableClientState
// glDisableClientStateIndexedEXT
// glDisableIndexedEXT
// glDisableVertexAttribArray
// glDisableVertexAttribArrayARB
// glDrawArrays
// glDrawArraysEXT
// glDrawArraysInstanced
// glDrawBuffer
// glDrawBuffers
// glDrawBuffersARB
// glDrawElements
// glDrawElementsBaseVertex
// glDrawElementsInstanced
// glDrawElementsInstancedBaseVertex
// glDrawPixels
// glDrawRangeElements
// glDrawRangeElementsBaseVertex
// glDrawRangeElementsEXT
// glDrawTexf
// glDrawTexi
// glEdgeFlag
// glEdgeFlagPointer
// glEdgeFlagv
// glEnable
// glEnableClientState
// glEnableClientStateIndexedEXT
// glEnableIndexedEXT
// glEnableVertexAttribArray
// glEnableVertexAttribArrayARB
// glEnd
// glEndList
// glEndQuery
// glEndQueryARB
// glEvalCoord1d
// glEvalCoord1dv
// glEvalCoord1f
// glEvalCoord1fv
// glEvalCoord2d
// glEvalCoord2dv
// glEvalCoord2f
// glEvalCoord2fv
// glEvalMesh1
// glEvalMesh2
// glEvalPoint1
// glEvalPoint2
// glFeedbackBuffer
// glFinish
// glFlush
// glFogCoordd
// glFogCoorddv
// glFogCoordf
// glFogCoordfv
// glFogCoordPointer
// glFogf
// glFogfv
// glFogi
// glFogiv
// glFogx
// glFogxv
// glFramebufferRenderbuffer
// glFramebufferRenderbufferEXT
// glFramebufferTexture1D
// glFramebufferTexture1DEXT
// glFramebufferTexture2D
// glFramebufferTexture2DEXT
// glFramebufferTexture3D
// glFramebufferTexture3DEXT
// glFramebufferTextureLayer
// glFramebufferTextureLayerEXT
// glFrontFace
// glFrustum
// glFrustumf
// glFrustumx
// glGenBuffers
// glGenBuffersARB
// glGenerateMipmap
// glGenerateMipmapEXT
// glGenFramebuffers
// glGenFramebuffersEXT
// glGenLists
// glGenProgramsARB
// glGenQueries
// glGenQueriesARB
// glGenRenderbuffers
// glGenRenderbuffersEXT
// glGenTextures
// glGenVertexArrays
// glGetActiveAttrib
// glGetActiveAttribARB
// glGetActiveUniform
// glGetActiveUniformARB
// glGetAttachedObjectsARB
// glGetAttachedShaders
// glGetAttribLocation
// glGetAttribLocationARB
// glGetBooleanIndexedvEXT
// glGetBooleanv
// glGetBufferParameteriv
// glGetBufferParameterivARB
// glGetBufferPointerv
// glGetBufferPointervARB
// glGetBufferSubData
// glGetBufferSubDataARB
// glGetClipPlane
// glGetClipPlanef
// glGetClipPlanex
// glGetCompressedMultiTexImageEXT
// glGetCompressedTexImage
// glGetCompressedTexImageARB
// glGetCompressedTexImageEXT
// glGetCompressedTextureImageEXT
// glGetDoubleIndexedvEXT
// glGetDoublev
// glGetError
// glGetFixedv
// glGetFloatIndexedvEXT
// glGetFloatv
// glGetFramebufferAttachmentParameteriv
// glGetFramebufferAttachmentParameterivEXT
// glGetHandleARB
// glGetInfoLogARB
// glGetIntegerIndexedvEXT
// glGetIntegerv
// glGetLightfv
// glGetLightiv
// glGetLightxv
// glGetMapdv
// glGetMapfv
// glGetMapiv
// glGetMaterialfv
// glGetMaterialiv
// glGetMaterialxv
// glGetMultiTexEnvfvEXT
// glGetMultiTexEnvivEXT
// glGetMultiTexGendvEXT
// glGetMultiTexGenfvEXT
// glGetMultiTexGenivEXT
// glGetMultiTexImageEXT
// glGetMultiTexLevelParameterfvEXT
// glGetMultiTexLevelParameterivEXT
// glGetMultiTexParameterfvEXT
// glGetMultiTexParameterivEXT
// glGetObjectParameterfvARB
// glGetObjectParameterivARB
// glGetPixelMapfv
// glGetPixelMapuiv
// glGetPixelMapusv
// glGetPointerIndexedvEXT
// glGetPointerv
// glGetPolygonStipple
// glGetProgramEnvParameterdvARB
// glGetProgramEnvParameterfvARB
// glGetProgramInfoLog
// glGetProgramiv
// glGetProgramivARB
// glGetProgramLocalParameterdvARB
// glGetProgramLocalParameterfvARB
// glGetProgramStringARB
// glGetQueryiv
// glGetQueryivARB
// glGetQueryObjectiv
// glGetQueryObjectivARB
// glGetQueryObjectuiv
// glGetQueryObjectuivARB
// glGetRenderbufferParameteriv
// glGetRenderbufferParameterivEXT
// glGetShaderInfoLog
// glGetShaderiv
// glGetShaderPrecisionFormat
// glGetShaderSource
// glGetShaderSourceARB
// glGetString
// glGetStringi
// glGetTexEnvfv
// glGetTexEnviv
// glGetTexEnvxv
// glGetTexGendv
// glGetTexGenfv
// glGetTexGeniv
// glGetTexImage
// glGetTexLevelParameterfv
// glGetTexLevelParameteriv
// glGetTexParameterfv
// glGetTexParameteriv
// glGetTexParameterxv
// glGetTextureImageEXT
// glGetTextureLevelParameterfvEXT
// glGetTextureLevelParameterivEXT
// glGetTextureParameterfvEXT
// glGetTextureParameterivEXT
// glGetUniformfv
// glGetUniformfvARB
// glGetUniformiv
// glGetUniformivARB
// glGetUniformLocation
// glGetUniformLocationARB
// glGetVertexAttribdv
// glGetVertexAttribdvARB
// glGetVertexAttribfv
// glGetVertexAttribfvARB
// glGetVertexAttribiv
// glGetVertexAttribivARB
// glGetVertexAttribPointerv
// glGetVertexAttribPointervARB
// glHint
// glIndexb
// glIndexbv
// glIndexd
// glIndexdv
// glIndexf
// glIndexfv
// glIndexi
// glIndexiv
// glIndexMask
// glIndexPointer
// glIndexs
// glIndexsv
// glIndexub
// glIndexubv
// glIndexui
// glIndexuiv
// glIndexus
// glIndexusv
// glInitNames
// glInterleavedArrays
// glIsBuffer
// glIsBufferARB
// glIsEnabled
// glIsEnabledIndexedEXT
// glIsFramebuffer
// glIsFramebufferEXT
// glIsList
// glIsProgram
// glIsProgramARB
// glIsQuery
// glIsQueryARB
// glIsRenderbuffer
// glIsRenderbufferEXT
// glIsShader
// glIsTexture
// glIsVertexArray
// glLightf
// glLightfv
// glLighti
// glLightiv
// glLightModelf
// glLightModelfv
// glLightModeli
// glLightModeliv
// glLightModelx
// glLightModelxv
// glLightx
// glLightxv
// glLineStipple
// glLineWidth
// glLineWidthx
// glLinkProgram
// glLinkProgramARB
// glListBase
// glLoadIdentity
// glLoadMatrixd
// glLoadMatrixf
// glLoadMatrixx
// glLoadName
// glLoadTransposeMatrixd
// glLoadTransposeMatrixf
// glLockArraysEXT
// glLogicOp
// glMap1d
// glMap1f
// glMap2d
// glMap2f
// glMapBuffer
// glMapBufferARB
// glMapGrid1d
// glMapGrid1f
// glMapGrid2d
// glMapGrid2f
// glMaterialf
// glMaterialfv
// glMateriali
// glMaterialiv
// glMaterialx
// glMaterialxv
// glMatrixFrustumEXT
// glMatrixLoaddEXT
// glMatrixLoadfEXT
// glMatrixLoadIdentityEXT
// glMatrixLoadTransposedEXT
// glMatrixLoadTransposefEXT
// glMatrixMode
// glMatrixMultdEXT
// glMatrixMultfEXT
// glMatrixMultTransposedEXT
// glMatrixMultTransposefEXT
// glMatrixOrthoEXT
// glMatrixPopEXT
// glMatrixPushEXT
// glMatrixRotatedEXT
// glMatrixRotatefEXT
// glMatrixScaledEXT
// glMatrixScalefEXT
// glMatrixTranslatedEXT
// glMatrixTranslatefEXT
// glMultiDrawArrays
// glMultiDrawElements
// glMultiDrawElementsBaseVertex
// glMultiTexCoord1b
// glMultiTexCoord1bARB
// glMultiTexCoord1bv
// glMultiTexCoord1bvARB
// glMultiTexCoord1d
// glMultiTexCoord1dARB
// glMultiTexCoord1dv
// glMultiTexCoord1dvARB
// glMultiTexCoord1f
// glMultiTexCoord1fARB
// glMultiTexCoord1fv
// glMultiTexCoord1fvARB
// glMultiTexCoord1i
// glMultiTexCoord1iARB
// glMultiTexCoord1iv
// glMultiTexCoord1ivARB
// glMultiTexCoord1s
// glMultiTexCoord1sARB
// glMultiTexCoord1sv
// glMultiTexCoord1svARB
// glMultiTexCoord1ub
// glMultiTexCoord1ubARB
// glMultiTexCoord1ubv
// glMultiTexCoord1ubvARB
// glMultiTexCoord1ui
// glMultiTexCoord1uiARB
// glMultiTexCoord1uiv
// glMultiTexCoord1uivARB
// glMultiTexCoord1us
// glMultiTexCoord1usARB
// glMultiTexCoord1usv
// glMultiTexCoord1usvARB
// glMultiTexCoord2b
// glMultiTexCoord2bARB
// glMultiTexCoord2bv
// glMultiTexCoord2bvARB
// glMultiTexCoord2d
// glMultiTexCoord2dARB
// glMultiTexCoord2dv
// glMultiTexCoord2dvARB
// glMultiTexCoord2f
// glMultiTexCoord2fARB
// glMultiTexCoord2fv
// glMultiTexCoord2fvARB
// glMultiTexCoord2i
// glMultiTexCoord2iARB
// glMultiTexCoord2iv
// glMultiTexCoord2ivARB
// glMultiTexCoord2s
// glMultiTexCoord2sARB
// glMultiTexCoord2sv
// glMultiTexCoord2svARB
// glMultiTexCoord2ub
// glMultiTexCoord2ubARB
// glMultiTexCoord2ubv
// glMultiTexCoord2ubvARB
// glMultiTexCoord2ui
// glMultiTexCoord2uiARB
// glMultiTexCoord2uiv
// glMultiTexCoord2uivARB
// glMultiTexCoord2us
// glMultiTexCoord2usARB
// glMultiTexCoord2usv
// glMultiTexCoord2usvARB
// glMultiTexCoord3b
// glMultiTexCoord3bARB
// glMultiTexCoord3bv
// glMultiTexCoord3bvARB
// glMultiTexCoord3d
// glMultiTexCoord3dARB
// glMultiTexCoord3dv
// glMultiTexCoord3dvARB
// glMultiTexCoord3f
// glMultiTexCoord3fARB
// glMultiTexCoord3fv
// glMultiTexCoord3fvARB
// glMultiTexCoord3i
// glMultiTexCoord3iARB
// glMultiTexCoord3iv
// glMultiTexCoord3ivARB
// glMultiTexCoord3s
// glMultiTexCoord3sARB
// glMultiTexCoord3sv
// glMultiTexCoord3svARB
// glMultiTexCoord3ub
// glMultiTexCoord3ubARB
// glMultiTexCoord3ubv
// glMultiTexCoord3ubvARB
// glMultiTexCoord3ui
// glMultiTexCoord3uiARB
// glMultiTexCoord3uiv
// glMultiTexCoord3uivARB
// glMultiTexCoord3us
// glMultiTexCoord3usARB
// glMultiTexCoord3usv
// glMultiTexCoord3usvARB
// glMultiTexCoord4b
// glMultiTexCoord4bARB
// glMultiTexCoord4bv
// glMultiTexCoord4bvARB
// glMultiTexCoord4d
// glMultiTexCoord4dARB
// glMultiTexCoord4dv
// glMultiTexCoord4dvARB
// glMultiTexCoord4f
// glMultiTexCoord4fARB
// glMultiTexCoord4fv
// glMultiTexCoord4fvARB
// glMultiTexCoord4i
// glMultiTexCoord4iARB
// glMultiTexCoord4iv
// glMultiTexCoord4ivARB
// glMultiTexCoord4s
// glMultiTexCoord4sARB
// glMultiTexCoord4sv
// glMultiTexCoord4svARB
// glMultiTexCoord4ub
// glMultiTexCoord4ubARB
// glMultiTexCoord4ubv
// glMultiTexCoord4ubvARB
// glMultiTexCoord4ui
// glMultiTexCoord4uiARB
// glMultiTexCoord4uiv
// glMultiTexCoord4uivARB
// glMultiTexCoord4us
// glMultiTexCoord4usARB
// glMultiTexCoord4usv
// glMultiTexCoord4usvARB
// glMultiTexCoord4x
// glMultiTexCoordPointerEXT
// glMultiTexEnvfEXT
// glMultiTexEnvfvEXT
// glMultiTexEnviEXT
// glMultiTexEnvivEXT
// glMultiTexGendEXT
// glMultiTexGendvEXT
// glMultiTexGenfEXT
// glMultiTexGenfvEXT
// glMultiTexGeniEXT
// glMultiTexGenivEXT
// glMultiTexImage1DEXT
// glMultiTexImage2DEXT
// glMultiTexImage3DEXT
// glMultiTexParameterfEXT
// glMultiTexParameterfvEXT
// glMultiTexParameteriEXT
// glMultiTexParameterivEXT
// glMultiTexSubImage1DEXT
// glMultiTexSubImage2DEXT
// glMultiTexSubImage3DEXT
// glMultMatrixd
// glMultMatrixf
// glMultMatrixx
// glMultTransposeMatrixd
// glMultTransposeMatrixf
// glNewList
// glNormal3b
// glNormal3bv
// glNormal3d
// glNormal3dv
// glNormal3f
// glNormal3fv
// glNormal3i
// glNormal3iv
// glNormal3s
// glNormal3sv
// glNormal3ub
// glNormal3ubv
// glNormal3ui
// glNormal3uiv
// glNormal3us
// glNormal3usv
// glNormal3x
// glNormalPointer
// glOrtho
// glOrthof
// glOrthox
// glPassThrough
// glPixelMapfv
// glPixelMapuiv
// glPixelMapusv
// glPixelStoref
// glPixelStorei
// glPixelTransferf
// glPixelTransferi
// glPixelZoom
// glPointParameterf
// glPointParameterfARB
// glPointParameterfEXT
// glPointParameterfv
// glPointParameterfvARB
// glPointParameterfvEXT
// glPointParameteri
// glPointParameteriv
// glPointParameterx
// glPointParameterxv
// glPointSize
// glPointSizePointerOES
// glPointSizex
// glPolygonMode
// glPolygonOffset
// glPolygonOffsetx
// glPolygonStipple
// glPopAttrib
// glPopClientAttrib
// glPopMatrix
// glPopName
// glPrioritizeTextures
// glProgramEnvParameter4dARB
// glProgramEnvParameter4dvARB
// glProgramEnvParameter4fARB
// glProgramEnvParameter4fvARB
// glProgramLocalParameter4dARB
// glProgramLocalParameter4dvARB
// glProgramLocalParameter4fARB
// glProgramLocalParameter4fvARB
// glProgramStringARB
// glPushAttrib
// glPushClientAttrib
// glPushClientAttribDefaultEXT
// glPushMatrix
// glPushName
// glRasterPos2b
// glRasterPos2bv
// glRasterPos2d
// glRasterPos2dv
// glRasterPos2f
// glRasterPos2fv
// glRasterPos2i
// glRasterPos2iv
// glRasterPos2s
// glRasterPos2sv
// glRasterPos2ub
// glRasterPos2ubv
// glRasterPos2ui
// glRasterPos2uiv
// glRasterPos2us
// glRasterPos2usv
// glRasterPos3b
// glRasterPos3bv
// glRasterPos3d
// glRasterPos3dv
// glRasterPos3f
// glRasterPos3fv
// glRasterPos3i
// glRasterPos3iv
// glRasterPos3s
// glRasterPos3sv
// glRasterPos3ub
// glRasterPos3ubv
// glRasterPos3ui
// glRasterPos3uiv
// glRasterPos3us
// glRasterPos3usv
// glRasterPos4b
// glRasterPos4bv
// glRasterPos4d
// glRasterPos4dv
// glRasterPos4f
// glRasterPos4fv
// glRasterPos4i
// glRasterPos4iv
// glRasterPos4s
// glRasterPos4sv
// glRasterPos4ub
// glRasterPos4ubv
// glRasterPos4ui
// glRasterPos4uiv
// glRasterPos4us
// glRasterPos4usv
// glReadBuffer
// glReadPixels
// glRectd
// glRectdv
// glRectf
// glRectfv
// glRecti
// glRectiv
// glRects
// glRectsv
// glReleaseShaderCompiler
// glRenderbufferStorage
// glRenderbufferStorageEXT
// glRenderMode
// glRotated
// glRotatef
// glRotatex
// glSampleCoverage
// glSampleCoverageARB
// glSampleCoveragex
// glScaled
// glScalef
// glScalex
// glScissor
// glSecondaryColor3b
// glSecondaryColor3bv
// glSecondaryColor3d
// glSecondaryColor3dv
// glSecondaryColor3f
// glSecondaryColor3fv
// glSecondaryColor3i
// glSecondaryColor3iv
// glSecondaryColor3s
// glSecondaryColor3sv
// glSecondaryColor3ub
// glSecondaryColor3ubv
// glSecondaryColor3ui
// glSecondaryColor3uiv
// glSecondaryColor3us
// glSecondaryColor3usv
// glSecondaryColorPointer
// glSelectBuffer
// glShadeModel
// glShaderBinary
// glShaderSource
// glShaderSourceARB
// glStencilFunc
// glStencilFuncSeparate
// glStencilMask
// glStencilMaskSeparate
// glStencilOp
// glStencilOpSeparate
// glTexCoord1b
// glTexCoord1bv
// glTexCoord1d
// glTexCoord1dv
// glTexCoord1f
// glTexCoord1fv
// glTexCoord1i
// glTexCoord1iv
// glTexCoord1s
// glTexCoord1sv
// glTexCoord1ub
// glTexCoord1ubv
// glTexCoord1ui
// glTexCoord1uiv
// glTexCoord1us
// glTexCoord1usv
// glTexCoord2b
// glTexCoord2bv
// glTexCoord2d
// glTexCoord2dv
// glTexCoord2f
// glTexCoord2fv
// glTexCoord2i
// glTexCoord2iv
// glTexCoord2s
// glTexCoord2sv
// glTexCoord2ub
// glTexCoord2ubv
// glTexCoord2ui
// glTexCoord2uiv
// glTexCoord2us
// glTexCoord2usv
// glTexCoord3b
// glTexCoord3bv
// glTexCoord3d
// glTexCoord3dv
// glTexCoord3f
// glTexCoord3fv
// glTexCoord3i
// glTexCoord3iv
// glTexCoord3s
// glTexCoord3sv
// glTexCoord3ub
// glTexCoord3ubv
// glTexCoord3ui
// glTexCoord3uiv
// glTexCoord3us
// glTexCoord3usv
// glTexCoord4b
// glTexCoord4bv
// glTexCoord4d
// glTexCoord4dv
// glTexCoord4f
// glTexCoord4fv
// glTexCoord4i
// glTexCoord4iv
// glTexCoord4s
// glTexCoord4sv
// glTexCoord4ub
// glTexCoord4ubv
// glTexCoord4ui
// glTexCoord4uiv
// glTexCoord4us
// glTexCoord4usv
// glTexCoordPointer
// glTexEnvf
// glTexEnvfv
// glTexEnvi
// glTexEnviv
// glTexEnvx
// glTexEnvxv
// glTexGend
// glTexGendv
// glTexGenf
// glTexGenfv
// glTexGeni
// glTexGeniv
// glTexImage1D
// glTexImage2D
// glTexImage3D
// glTexImage3DEXT
// glTexParameterf
// glTexParameterfv
// glTexParameteri
// glTexParameteriv
// glTexParameterx
// glTexParameterxv
// glTexSubImage1D
// glTexSubImage2D
// glTexSubImage3D
// glTexSubImage3DARB
// glTexSubImage3DEXT
// glTextureImage1DEXT
// glTextureImage2DEXT
// glTextureImage3DEXT
// glTextureParameterfEXT
// glTextureParameterfvEXT
// glTextureParameteriEXT
// glTextureParameterivEXT
// glTextureSubImage1DEXT
// glTextureSubImage2DEXT
// glTextureSubImage3DEXT
// glTranslated
// glTranslatef
// glTranslatex
// glUniform1f
// glUniform1fARB
// glUniform1fv
// glUniform1fvARB
// glUniform1i
// glUniform1iARB
// glUniform1iv
// glUniform1ivARB
// glUniform2f
// glUniform2fARB
// glUniform2fv
// glUniform2fvARB
// glUniform2i
// glUniform2iARB
// glUniform2iv
// glUniform2ivARB
// glUniform3f
// glUniform3fARB
// glUniform3fv
// glUniform3fvARB
// glUniform3i
// glUniform3iARB
// glUniform3iv
// glUniform3ivARB
// glUniform4f
// glUniform4fARB
// glUniform4fv
// glUniform4fvARB
// glUniform4i
// glUniform4iARB
// glUniform4iv
// glUniform4ivARB
// glUniformMatrix2fv
// glUniformMatrix2fvARB
// glUniformMatrix3fv
// glUniformMatrix3fvARB
// glUniformMatrix4fv
// glUniformMatrix4fvARB
// glUnlockArraysEXT
// glUnmapBuffer
// glUnmapBufferARB
// glUseProgram
// glUseProgramObjectARB
// glValidateProgram
// glValidateProgramARB
// glVertex2b
// glVertex2bv
// glVertex2d
// glVertex2dv
// glVertex2f
// glVertex2fv
// glVertex2i
// glVertex2iv
// glVertex2s
// glVertex2sv
// glVertex2ub
// glVertex2ubv
// glVertex2ui
// glVertex2uiv
// glVertex2us
// glVertex2usv
// glVertex3b
// glVertex3bv
// glVertex3d
// glVertex3dv
// glVertex3f
// glVertex3fv
// glVertex3i
// glVertex3iv
// glVertex3s
// glVertex3sv
// glVertex3ub
// glVertex3ubv
// glVertex3ui
// glVertex3uiv
// glVertex3us
// glVertex3usv
// glVertex4b
// glVertex4bv
// glVertex4d
// glVertex4dv
// glVertex4f
// glVertex4fv
// glVertex4i
// glVertex4iv
// glVertex4s
// glVertex4sv
// glVertex4ub
// glVertex4ubv
// glVertex4ui
// glVertex4uiv
// glVertex4us
// glVertex4usv
// glVertexAttrib1d
// glVertexAttrib1dARB
// glVertexAttrib1dv
// glVertexAttrib1dvARB
// glVertexAttrib1f
// glVertexAttrib1fARB
// glVertexAttrib1fv
// glVertexAttrib1fvARB
// glVertexAttrib1s
// glVertexAttrib1sARB
// glVertexAttrib1sv
// glVertexAttrib1svARB
// glVertexAttrib2d
// glVertexAttrib2dARB
// glVertexAttrib2dv
// glVertexAttrib2dvARB
// glVertexAttrib2f
// glVertexAttrib2fARB
// glVertexAttrib2fv
// glVertexAttrib2fvARB
// glVertexAttrib2s
// glVertexAttrib2sARB
// glVertexAttrib2sv
// glVertexAttrib2svARB
// glVertexAttrib3d
// glVertexAttrib3dARB
// glVertexAttrib3dv
// glVertexAttrib3dvARB
// glVertexAttrib3f
// glVertexAttrib3fARB
// glVertexAttrib3fv
// glVertexAttrib3fvARB
// glVertexAttrib3s
// glVertexAttrib3sARB
// glVertexAttrib3sv
// glVertexAttrib3svARB
// glVertexAttrib4bv
// glVertexAttrib4bvARB
// glVertexAttrib4d
// glVertexAttrib4dARB
// glVertexAttrib4dv
// glVertexAttrib4dvARB
// glVertexAttrib4f
// glVertexAttrib4fARB
// glVertexAttrib4fv
// glVertexAttrib4fvARB
// glVertexAttrib4iv
// glVertexAttrib4ivARB
// glVertexAttrib4Nbv
// glVertexAttrib4NbvARB
// glVertexAttrib4Niv
// glVertexAttrib4NivARB
// glVertexAttrib4Nsv
// glVertexAttrib4NsvARB
// glVertexAttrib4Nub
// glVertexAttrib4NubARB
// glVertexAttrib4Nubv
// glVertexAttrib4NubvARB
// glVertexAttrib4Nuiv
// glVertexAttrib4NuivARB
// glVertexAttrib4Nusv
// glVertexAttrib4NusvARB
// glVertexAttrib4s
// glVertexAttrib4sARB
// glVertexAttrib4sv
// glVertexAttrib4svARB
// glVertexAttrib4ubv
// glVertexAttrib4ubvARB
// glVertexAttrib4uiv
// glVertexAttrib4uivARB
// glVertexAttrib4usv
// glVertexAttrib4usvARB
// glVertexAttribDivisor
// glVertexAttribPointer
// glVertexAttribPointerARB
// glVertexPointer
// glViewport
// glWindowPos2b
// glWindowPos2bv
// glWindowPos2d
// glWindowPos2dv
// glWindowPos2f
// glWindowPos2fv
// glWindowPos2i
// glWindowPos2iv
// glWindowPos2s
// glWindowPos2sv
// glWindowPos2ub
// glWindowPos2ubv
// glWindowPos2ui
// glWindowPos2uiv
// glWindowPos2us
// glWindowPos2usv
// glWindowPos3b
// glWindowPos3bv
// glWindowPos3d
// glWindowPos3dv
// glWindowPos3f
// glWindowPos3fv
// glWindowPos3i
// glWindowPos3iv
// glWindowPos3s
// glWindowPos3sv
// glWindowPos3ub
// glWindowPos3ubv
// glWindowPos3ui
// glWindowPos3uiv
// glWindowPos3us
// glWindowPos3usv
// glXChooseFBConfig
// glXChooseFBConfigSGIX
// glXChooseVisual
// glXCopyContext
// glXCreateContext
// glXCreateContextAttribs
// glXCreateContextAttribsARB
// glXCreateGLXPixmap
// glXCreateNewContext
// glXCreatePbuffer
// glXCreatePixmap
// glXCreateWindow
// glXDestroyContext
// glXDestroyGLXPixmap
// glXDestroyPbuffer
// glXDestroyPixmap
// glXDestroyWindow
// glXGetClientString
// glXGetConfig
// glXGetCurrentContext
// glXGetCurrentDisplay
// glXGetCurrentDrawable
// glXGetFBConfigAttrib
// glXGetFBConfigs
// glXGetProcAddress
// glXGetProcAddressARB
// glXGetVisualFromFBConfig
// glXIsDirect
// glXMakeContextCurrent
// glXMakeCurrent
// glXQueryContext
// glXQueryDrawable
// glXQueryExtension
// glXQueryExtensionsString
// glXQueryServerString
// glXQueryVersion
// glXReleaseBuffersMESA
// glXSwapBuffers
// glXSwapInterval
// glXSwapIntervalEXT
// glXSwapIntervalMESA
// glXSwapIntervalSGI
// glXUseXFont
// glXWaitGL
// glXWaitX
// _init

END()

#else
#error Mmmm...
#endif