#if defined(GO) && defined(GOM) && defined(GO2) && defined(DATA) && defined(END)

// a64l
// abort
// abs
// accept
// access
// acct
// addmntent
// addseverity
// adjtime
// adjtimex
// __adjtimex
// advance
// __aeabi_assert
// __aeabi_atexit
// __aeabi_errno_addr
// __aeabi_localeconv
// __aeabi_MB_CUR_MAX
// __aeabi_memclr
// __aeabi_memclr4
// __aeabi_memclr8
// __aeabi_memcpy
// __aeabi_memcpy4
// __aeabi_memcpy8
// __aeabi_memmove
// __aeabi_memmove4
// __aeabi_memmove8
// __aeabi_memset
// __aeabi_memset4
// __aeabi_memset8
// __after_morecore_hook
// alarm
// alphasort
// alphasort64
// argp_err_exit_status
// argp_error
// argp_failure
// argp_help
// argp_parse
// argp_program_bug_address
// argp_program_version
// argp_program_version_hook
// argp_state_help
// argp_usage
// argz_add
// argz_add_sep
// argz_append
// __argz_count
// argz_count
// argz_create
// argz_create_sep
// argz_delete
// argz_extract
// argz_insert
// __argz_next
// argz_next
// argz_replace
// __argz_stringify
// argz_stringify
// asctime
// asctime_r
// asprintf
// __asprintf
// __asprintf_chk
// __assert
// __assert_fail
// __assert_perror_fail
// atof
// atoi
// atol
// atoll
// authdes_create
// authdes_getucred
// authdes_pk_create
// _authenticate
// authnone_create
// authunix_create
// authunix_create_default
// backtrace
// __backtrace
// __backtrace_symbols
// backtrace_symbols
// __backtrace_symbols_fd
// backtrace_symbols_fd
// basename
// bcmp
// bcopy
// bdflush
// bind
// bindresvport
// bindtextdomain
// bind_textdomain_codeset
// brk
// __bsd_getpgrp
// bsd_signal
// bsearch
// btowc
// bzero
// __bzero
GO(calloc, pFuu)
// callrpc
// canonicalize_file_name
// capget
// capset
// catclose
// catgets
// catopen
// cbc_crypt
// cfgetispeed
// cfgetospeed
// cfmakeraw
// cfree
// cfsetispeed
// cfsetospeed
// cfsetspeed
// chdir
// __check_rhosts_file
// chflags
// __chk_fail
// chmod
// chown
// chroot
// clearenv
// clearerr
// clearerr_unlocked
// clnt_broadcast
// clnt_create
// clnt_pcreateerror
// clnt_perrno
// clnt_perror
// clntraw_create
// clnt_spcreateerror
// clnt_sperrno
// clnt_sperror
// clnttcp_create
// clntudp_bufcreate
// clntudp_create
// clntunix_create
// clock
// clone
// __clone
// close
// __close
// closedir
// closelog
// __cmsg_nxthdr
// confstr
// __confstr_chk
// connect
// __connect
// copysign
// copysignf
// copysignl
// creat
// creat64
// create_module
// ctermid
// ctime
// ctime_r
// __ctype_b_loc
// __ctype_get_mb_cur_max
// __ctype_tolower_loc
// __ctype_toupper_loc
// __curbrk
// cuserid
// __cxa_atexit
// __cxa_finalize
// __cyg_profile_func_enter
// __cyg_profile_func_exit
// daemon
// daylight
// __daylight
// dcgettext
// __dcgettext
// dcngettext
// __default_morecore
// __default_rt_sa_restorer_v1
// __default_rt_sa_restorer_v2
// __default_sa_restorer_v1
// __default_sa_restorer_v2
// delete_module
// des_setparity
// dgettext
// __dgettext
// difftime
// dirfd
// dirname
// div
// _dl_addr
         // _dl_argv
// dl_iterate_phdr
// _dl_mcount_wrapper
// _dl_mcount_wrapper_check
// _dl_open_hook
         // _dl_starting_up
// _dl_sym
// _dl_vsym
// dngettext
// dprintf
// __dprintf_chk
// drand48
// drand48_r
// dup
// dup2
// __dup2
// dup3
// duplocale
// __duplocale
// dysize
// eaccess
// ecb_crypt
// ecvt
// ecvt_r
// endaliasent
// endfsent
// endgrent
// endhostent
// endmntent
// __endmntent
// endnetent
// endnetgrent
// endprotoent
// endpwent
// endrpcent
// endservent
// endspent
// endttyent
// endusershell
// endutent
// endutxent
// environ
// _environ
// __environ
// envz_add
// envz_entry
// envz_get
// envz_merge
// envz_remove
// envz_strip
// epoll_create
// epoll_create1
// epoll_ctl
// epoll_pwait
// epoll_wait
// erand48
// erand48_r
// err
// errno
// __errno_location
// error
// error_at_line
// error_message_count
// error_one_per_line
// error_print_progname
// errx
// ether_aton
// ether_aton_r
// ether_hostton
// ether_line
// ether_ntoa
// ether_ntoa_r
// ether_ntohost
// euidaccess
// eventfd
// eventfd_read
// eventfd_write
// execl
// execle
// execlp
// execv
// execve
// execvp
// exit
// _exit
// _Exit
// faccessat
// fattach
// __fbufsize
// fchdir
// fchflags
// fchmod
// fchmodat
// fchown
// fchownat
// fclose
// fcloseall
// fcntl
// __fcntl
// fcvt
// fcvt_r
// fdatasync
// fdetach
// fdopen
// fdopendir
// feof
// feof_unlocked
// ferror
// ferror_unlocked
// fexecve
// fflush
// fflush_unlocked
// ffs
// __ffs
// ffsl
// ffsll
// fgetc
// fgetc_unlocked
// fgetgrent
// fgetgrent_r
// fgetpos
// fgetpos64
// fgetpwent
// fgetpwent_r
// fgets
// __fgets_chk
// fgetspent
// fgetspent_r
// fgets_unlocked
// __fgets_unlocked_chk
// fgetwc
// fgetwc_unlocked
// fgetws
// __fgetws_chk
// fgetws_unlocked
// __fgetws_unlocked_chk
// fgetxattr
// fileno
// fileno_unlocked
// finite
// __finite
// finitef
// __finitef
// finitel
// __finitel
// __flbf
// flistxattr
// flock
// flockfile
// _flushlbf
// fmemopen
// fmtmsg
// fnmatch
// fopen
// fopen64
// fopencookie
// fork
// __fork
// __fortify_fail
// fpathconf
// __fpending
// fprintf
// __fprintf_chk
// __fpu_control
// __fpurge
// fputc
// fputc_unlocked
// fputs
// fputs_unlocked
// fputwc
// fputwc_unlocked
// fputws
// fputws_unlocked
// fread
// __freadable
// __fread_chk
// __freading
// fread_unlocked
// __fread_unlocked_chk
GO(free, vFp)
// freeaddrinfo
// __free_hook
// freeifaddrs
// freelocale
// __freelocale
// fremovexattr
// freopen
// freopen64
// frexp
// frexpf
// frexpl
// fscanf
// fseek
// fseeko
// fseeko64
// __fsetlocking
// fsetpos
// fsetpos64
// fsetxattr
// fstatfs
// fstatfs64
// fstatvfs
// fstatvfs64
// fsync
// ftell
// ftello
// ftello64
// ftime
// ftok
// ftruncate
// ftruncate64
// ftrylockfile
// fts_children
// fts_close
// fts_open
// fts_read
// fts_set
// ftw
// ftw64
// funlockfile
// futimens
// futimes
// futimesat
// fwide
// fwprintf
// __fwprintf_chk
// __fwritable
// fwrite
// fwrite_unlocked
// __fwriting
// fwscanf
// __fxstat
// __fxstat64
// __fxstatat
// __fxstatat64
// __gai_sigqueue
// gai_strerror
// __gconv_get_alias_db
// __gconv_get_cache
// __gconv_get_modules_db
// gcvt
// getaddrinfo
// getaliasbyname
// getaliasbyname_r
// getaliasent
// getaliasent_r
// get_avphys_pages
// getc
// getchar
// getchar_unlocked
// getcontext
// getc_unlocked
// get_current_dir_name
// getcwd
// __getcwd_chk
// getdate
// getdate_err
// getdate_r
// getdelim
// __getdelim
// getdirentries
// getdirentries64
// getdomainname
// __getdomainname_chk
// getdtablesize
// getegid
// getenv
// geteuid
// getfsent
// getfsfile
// getfsspec
// getgid
// getgrent
// getgrent_r
// getgrgid
// getgrgid_r
// getgrnam
// getgrnam_r
// getgrouplist
// getgroups
// __getgroups_chk
// gethostbyaddr
// gethostbyaddr_r
// gethostbyname
// gethostbyname2
// gethostbyname2_r
// gethostbyname_r
// gethostent
// gethostent_r
// gethostid
// gethostname
// __gethostname_chk
// getifaddrs
// getipv4sourcefilter
// getitimer
// get_kernel_syms
// getline
// getloadavg
// getlogin
// getlogin_r
// __getlogin_r_chk
// getmntent
// __getmntent_r
// getmntent_r
// getmsg
// get_myaddress
// getnameinfo
// getnetbyaddr
// getnetbyaddr_r
// getnetbyname
// getnetbyname_r
// getnetent
// getnetent_r
// getnetgrent
// getnetgrent_r
// getnetname
// get_nprocs
// get_nprocs_conf
// getopt
// getopt_long
// getopt_long_only
// getpagesize
// __getpagesize
// getpass
// getpeername
// getpgid
// __getpgid
// getpgrp
// get_phys_pages
// getpid
// __getpid
// getpmsg
// getppid
// getpriority
// getprotobyname
// getprotobyname_r
// getprotobynumber
// getprotobynumber_r
// getprotoent
// getprotoent_r
// getpt
// getpublickey
// getpw
// getpwent
// getpwent_r
// getpwnam
// getpwnam_r
// getpwuid
// getpwuid_r
// getresgid
// getresuid
// getrlimit
// getrlimit64
// getrpcbyname
// getrpcbyname_r
// getrpcbynumber
// getrpcbynumber_r
// getrpcent
// getrpcent_r
// getrpcport
// getrusage
// gets
// __gets_chk
// getsecretkey
// getservbyname
// getservbyname_r
// getservbyport
// getservbyport_r
// getservent
// getservent_r
// getsid
// getsockname
// getsockopt
// getsourcefilter
// getspent
// getspent_r
// getspnam
// getspnam_r
// getsubopt
// gettext
// gettimeofday
// __gettimeofday
// getttyent
// getttynam
// getuid
// getusershell
// getutent
// getutent_r
// getutid
// getutid_r
// getutline
// getutline_r
// getutmp
// getutmpx
// getutxent
// getutxid
// getutxline
// getw
// getwc
// getwchar
// getwchar_unlocked
// getwc_unlocked
// getwd
// __getwd_chk
// getxattr
// GLIBC_2.4
// GLIBC_2.5
// GLIBC_2.6
// GLIBC_2.7
// GLIBC_2.8
// GLIBC_2.9
// GLIBC_PRIVATE
// glob
// glob64
// globfree
// globfree64
// glob_pattern_p
// gmtime
// __gmtime_r
// gmtime_r
// gnu_dev_major
// gnu_dev_makedev
// gnu_dev_minor
// gnu_get_libc_release
// gnu_get_libc_version
// __gnu_mcount_nc
// __gnu_Unwind_Find_exidx
// grantpt
// group_member
// gsignal
// gtty
// hasmntopt
// hcreate
// hcreate_r
// hdestroy
// hdestroy_r
// h_errlist
// h_errno
// __h_errno_location
// herror
// h_nerr
// host2netname
// hsearch
// hsearch_r
// hstrerror
// htonl
// htons
// iconv
// iconv_close
// iconv_open
// if_freenameindex
// if_indextoname
// if_nameindex
// if_nametoindex
// imaxabs
// imaxdiv
// in6addr_any
// in6addr_loopback
// inb
// index
// inet6_opt_append
// inet6_opt_find
// inet6_opt_finish
// inet6_opt_get_val
// inet6_opt_init
// inet6_option_alloc
// inet6_option_append
// inet6_option_find
// inet6_option_init
// inet6_option_next
// inet6_option_space
// inet6_opt_next
// inet6_opt_set_val
// inet6_rth_add
// inet6_rth_getaddr
// inet6_rth_init
// inet6_rth_reverse
// inet6_rth_segments
// inet6_rth_space
// inet_addr
// inet_aton
// inet_lnaof
// inet_makeaddr
// inet_netof
// inet_network
// inet_nsap_addr
// inet_nsap_ntoa
// inet_ntoa
// inet_ntop
// inet_pton
// initgroups
// init_module
// initstate
// initstate_r
// inl
// innetgr
// inotify_add_watch
// inotify_init
// inotify_init1
// inotify_rm_watch
// insque
// __internal_endnetgrent
// __internal_getnetgrent_r
// __internal_setnetgrent
// inw
// _IO_2_1_stderr_
// _IO_2_1_stdin_
// _IO_2_1_stdout_
// _IO_adjust_column
// _IO_adjust_wcolumn
// ioctl
// _IO_default_doallocate
// _IO_default_finish
// _IO_default_pbackfail
// _IO_default_uflow
// _IO_default_xsgetn
// _IO_default_xsputn
// _IO_doallocbuf
// _IO_do_write
// _IO_fclose
// _IO_fdopen
// _IO_feof
// _IO_ferror
// _IO_fflush
// _IO_fgetpos
// _IO_fgetpos64
// _IO_fgets
// _IO_file_attach
// _IO_file_close
// _IO_file_close_it
// _IO_file_doallocate
// _IO_file_finish
// _IO_file_fopen
// _IO_file_init
// _IO_file_jumps
// _IO_file_open
// _IO_file_overflow
// _IO_file_read
// _IO_file_seek
// _IO_file_seekoff
// _IO_file_setbuf
// _IO_file_stat
// _IO_file_sync
// _IO_file_underflow
// _IO_file_write
// _IO_file_xsputn
// _IO_flockfile
// _IO_flush_all
// _IO_flush_all_linebuffered
// _IO_fopen
// _IO_fprintf
// _IO_fputs
// _IO_fread
// _IO_free_backup_area
// _IO_free_wbackup_area
// _IO_fsetpos
// _IO_fsetpos64
// _IO_ftell
// _IO_ftrylockfile
// _IO_funlockfile
// _IO_fwrite
// _IO_getc
// _IO_getline
// _IO_getline_info
// _IO_gets
// _IO_init
// _IO_init_marker
// _IO_init_wmarker
// _IO_iter_begin
// _IO_iter_end
// _IO_iter_file
// _IO_iter_next
// _IO_least_wmarker
// _IO_link_in
// _IO_list_all
// _IO_list_lock
// _IO_list_resetlock
// _IO_list_unlock
// _IO_marker_delta
// _IO_marker_difference
// _IO_padn
// _IO_peekc_locked
// ioperm
// iopl
// _IO_popen
// _IO_printf
// _IO_proc_close
// _IO_proc_open
// _IO_putc
// _IO_puts
// _IO_remove_marker
// _IO_seekmark
// _IO_seekoff
// _IO_seekpos
// _IO_seekwmark
// _IO_setb
// _IO_setbuffer
// _IO_setvbuf
// _IO_sgetn
// _IO_sprintf
// _IO_sputbackc
// _IO_sputbackwc
// _IO_sscanf
// _IO_str_init_readonly
// _IO_str_init_static
// _IO_str_overflow
// _IO_str_pbackfail
// _IO_str_seekoff
// _IO_str_underflow
// _IO_sungetc
// _IO_sungetwc
// _IO_switch_to_get_mode
// _IO_switch_to_main_wget_area
// _IO_switch_to_wbackup_area
// _IO_switch_to_wget_mode
// _IO_ungetc
// _IO_un_link
// _IO_unsave_markers
// _IO_unsave_wmarkers
// _IO_vfprintf
// _IO_vfscanf
// _IO_vsprintf
// _IO_wdefault_doallocate
// _IO_wdefault_finish
// _IO_wdefault_pbackfail
// _IO_wdefault_uflow
// _IO_wdefault_xsgetn
// _IO_wdefault_xsputn
// _IO_wdoallocbuf
// _IO_wdo_write
// _IO_wfile_jumps
// _IO_wfile_overflow
// _IO_wfile_seekoff
// _IO_wfile_sync
// _IO_wfile_underflow
// _IO_wfile_xsputn
// _IO_wmarker_delta
// _IO_wsetb
// iruserok
// iruserok_af
// isalnum
// __isalnum_l
// isalnum_l
// isalpha
// __isalpha_l
// isalpha_l
// isascii
// __isascii_l
// isastream
// isatty
// isblank
// __isblank_l
// isblank_l
// iscntrl
// __iscntrl_l
// iscntrl_l
// isctype
// __isctype
// isdigit
// __isdigit_l
// isdigit_l
// isfdtype
// isgraph
// __isgraph_l
// isgraph_l
// isinf
// __isinf
// isinff
// __isinff
// isinfl
// __isinfl
// islower
// __islower_l
// islower_l
// isnan
// __isnan
// isnanf
// __isnanf
// isnanl
// __isnanl
// __isoc99_fscanf
// __isoc99_fwscanf
// __isoc99_scanf
// __isoc99_sscanf
// __isoc99_swscanf
// __isoc99_vfscanf
// __isoc99_vfwscanf
// __isoc99_vscanf
// __isoc99_vsscanf
// __isoc99_vswscanf
// __isoc99_vwscanf
// __isoc99_wscanf
// isprint
// __isprint_l
// isprint_l
// ispunct
// __ispunct_l
// ispunct_l
// isspace
// __isspace_l
// isspace_l
// isupper
// __isupper_l
// isupper_l
// iswalnum
// __iswalnum_l
// iswalnum_l
// iswalpha
// __iswalpha_l
// iswalpha_l
// iswblank
// __iswblank_l
// iswblank_l
// iswcntrl
// __iswcntrl_l
// iswcntrl_l
// iswctype
// __iswctype
// __iswctype_l
// iswctype_l
// iswdigit
// __iswdigit_l
// iswdigit_l
// iswgraph
// __iswgraph_l
// iswgraph_l
// iswlower
// __iswlower_l
// iswlower_l
// iswprint
// __iswprint_l
// iswprint_l
// iswpunct
// __iswpunct_l
// iswpunct_l
// iswspace
// __iswspace_l
// iswspace_l
// iswupper
// __iswupper_l
// iswupper_l
// iswxdigit
// __iswxdigit_l
// iswxdigit_l
// isxdigit
// __isxdigit_l
// isxdigit_l
// _itoa_lower_digits
// __ivaliduser
// jrand48
// jrand48_r
// key_decryptsession
// key_decryptsession_pk
// __key_decryptsession_pk_LOCAL
// key_encryptsession
// key_encryptsession_pk
// __key_encryptsession_pk_LOCAL
// key_gendes
// __key_gendes_LOCAL
// key_get_conv
// key_secretkey_is_set
// key_setnet
// key_setsecret
// kill
// killpg
// klogctl
// l64a
// labs
// lchmod
// lchown
// lckpwdf
// lcong48
// lcong48_r
// ldexp
// ldexpf
// ldexpl
// ldiv
// lfind
// lgetxattr
// __libc_allocate_rtsig
// __libc_allocate_rtsig_private
// __libc_calloc
// __libc_clntudp_bufcreate
// __libc_current_sigrtmax
// __libc_current_sigrtmax_private
// __libc_current_sigrtmin
// __libc_current_sigrtmin_private
// __libc_dlclose
// __libc_dl_error_tsd
// __libc_dlopen_mode
// __libc_dlsym
// __libc_enable_secure
// __libc_fatal
// __libc_fork
// __libc_free
// __libc_freeres
// __libc_init_first
// _libc_intl_domainname
// __libc_longjmp
// __libc_mallinfo
// __libc_malloc
// __libc_mallopt
// __libc_memalign
// __libc_pthread_init
// __libc_pvalloc
// __libc_pwrite
// __libc_realloc
// __libc_sa_len
// __libc_siglongjmp
// __libc_stack_end
GOM(__libc_start_main, iFEpippppp)
// __libc_system
// __libc_thread_freeres
// __libc_valloc
// link
// linkat
// listen
// listxattr
// llabs
// lldiv
// llistxattr
// llseek
// loc1
// loc2
// localeconv
// localtime
// localtime_r
// lockf
// lockf64
// locs
// longjmp
// _longjmp
// lrand48
// lrand48_r
// lremovexattr
// lsearch
// lseek
// __lseek
// lseek64
// lsetxattr
// lutimes
// __lxstat
// __lxstat64
// madvise
// makecontext
// mallinfo
// malloc
// malloc_get_state
// __malloc_hook
// __malloc_initialize_hook
// malloc_set_state
// malloc_stats
// malloc_trim
// malloc_usable_size
// mallopt
// mallwatch
// mblen
// mbrlen
// __mbrlen
// mbrtowc
// __mbrtowc
// mbsinit
// mbsnrtowcs
// __mbsnrtowcs_chk
// mbsrtowcs
// __mbsrtowcs_chk
// mbstowcs
// __mbstowcs_chk
// mbtowc
// mcheck
// mcheck_check_all
// mcheck_pedantic
// _mcleanup
// mcount
// _mcount
// memalign
// __memalign_hook
// memccpy
// memchr
// memcmp
// memcpy
// __memcpy_chk
// memfrob
// memmem
// memmove
// __memmove_chk
// mempcpy
// __mempcpy
// __mempcpy_chk
// __mempcpy_small
// memrchr
// memset
// __memset_chk
// mincore
// mkdir
// mkdirat
// mkdtemp
// mkfifo
// mkfifoat
// mkostemp
// mkostemp64
// mkstemp
// mkstemp64
// mktemp
// mktime
// mlock
// mlockall
// mmap
// mmap64
// modf
// modff
// modfl
// moncontrol
// monstartup
// __monstartup
// __morecore
// mount
// mprobe
// mprotect
// mrand48
// mrand48_r
// mremap
// msgctl
// msgget
// msgrcv
// msgsnd
// msync
// mtrace
// munlock
// munlockall
// munmap
// muntrace
// nanosleep
// __nanosleep
// netname2host
// netname2user
// newlocale
// __newlocale
// nfsservctl
// nftw
// nftw64
// ngettext
// nice
// _nl_default_dirname
// _nl_domain_bindings
// nl_langinfo
// __nl_langinfo_l
// nl_langinfo_l
// _nl_msg_cat_cntr
// nrand48
// nrand48_r
// __nss_configure_lookup
// __nss_database_lookup
// __nss_disable_nscd
// _nss_files_parse_grent
// _nss_files_parse_pwent
// _nss_files_parse_spent
// __nss_group_lookup
// __nss_group_lookup2
// __nss_hostname_digits_dots
// __nss_hosts_lookup
// __nss_hosts_lookup2
// __nss_lookup_function
// __nss_next
// __nss_next2
// __nss_passwd_lookup
// __nss_passwd_lookup2
// __nss_services_lookup2
// ntohl
// ntohs
// ntp_adjtime
// ntp_gettime
// _null_auth
// _obstack_allocated_p
// obstack_alloc_failed_handler
// _obstack_begin
// _obstack_begin_1
// obstack_exit_failure
// _obstack_free
// obstack_free
// _obstack_memory_used
// _obstack_newchunk
// obstack_printf
// __obstack_printf_chk
// obstack_vprintf
// __obstack_vprintf_chk
// on_exit
// open
// __open
// __open_2
// open64
// __open64
// __open64_2
// openat
// __openat_2
// openat64
// __openat64_2
// __open_catalog
// opendir
// openlog
// open_memstream
// open_wmemstream
// optarg
// opterr
// optind
// optopt
// outb
// outl
// outw
// __overflow
// parse_printf_format
// passwd2des
// pathconf
// pause
// pclose
// perror
// personality
// pipe
// __pipe
// pipe2
// pivot_root
// pmap_getmaps
// pmap_getport
// pmap_rmtcall
// pmap_set
// pmap_unset
// poll
// __poll
// popen
// posix_fadvise
// posix_fadvise64
// posix_fallocate
// posix_fallocate64
// posix_madvise
// posix_memalign
// posix_openpt
// posix_spawn
// posix_spawnattr_destroy
// posix_spawnattr_getflags
// posix_spawnattr_getpgroup
// posix_spawnattr_getschedparam
// posix_spawnattr_getschedpolicy
// posix_spawnattr_getsigdefault
// posix_spawnattr_getsigmask
// posix_spawnattr_init
// posix_spawnattr_setflags
// posix_spawnattr_setpgroup
// posix_spawnattr_setschedparam
// posix_spawnattr_setschedpolicy
// posix_spawnattr_setsigdefault
// posix_spawnattr_setsigmask
// posix_spawn_file_actions_addclose
// posix_spawn_file_actions_adddup2
// posix_spawn_file_actions_addopen
// posix_spawn_file_actions_destroy
// posix_spawn_file_actions_init
// posix_spawnp
// ppoll
// prctl
// pread
// pread64
// __pread64
// __pread64_chk
// __pread_chk
GO2(printf, iFopV, vfprintf)
GO2(__printf_chk, iFvopV, vfprintf)
// __printf_fp
// printf_size
// printf_size_info
// profil
// __profile_frequency
// __progname
// __progname_full
// program_invocation_name
// program_invocation_short_name
// pselect
// psignal
// pthread_attr_destroy
// pthread_attr_getdetachstate
// pthread_attr_getinheritsched
// pthread_attr_getschedparam
// pthread_attr_getschedpolicy
// pthread_attr_getscope
// pthread_attr_init
// pthread_attr_setdetachstate
// pthread_attr_setinheritsched
// pthread_attr_setschedparam
// pthread_attr_setschedpolicy
// pthread_attr_setscope
// pthread_condattr_destroy
// pthread_condattr_init
// pthread_cond_broadcast
// pthread_cond_destroy
// pthread_cond_init
// pthread_cond_signal
// pthread_cond_timedwait
// pthread_cond_wait
// pthread_equal
// pthread_exit
// pthread_getschedparam
// pthread_mutex_destroy
// pthread_mutex_init
// pthread_mutex_lock
// pthread_mutex_unlock
// pthread_self
// pthread_setcancelstate
// pthread_setcanceltype
// pthread_setschedparam
// ptrace
// ptsname
// ptsname_r
// __ptsname_r_chk
// putc
GO(putchar, iFi)
// putchar_unlocked
// putc_unlocked
// putenv
// putgrent
// putmsg
// putpmsg
// putpwent
GO(puts, iFp)
// putspent
// pututline
// pututxline
// putw
// putwc
// putwchar
// putwchar_unlocked
// putwc_unlocked
// pvalloc
// pwrite
// pwrite64
// __pwrite64
// qecvt
// qecvt_r
// qfcvt
// qfcvt_r
// qgcvt
// qsort
// qsort_r
// query_module
// quotactl
// raise
// rand
// random
// random_r
// rand_r
// rawmemchr
// __rawmemchr
// rcmd
// rcmd_af
// __rcmd_errstr
// read
// __read
// readahead
// __read_chk
// readdir
// readdir64
// readdir64_r
// readdir_r
// readlink
// readlinkat
// __readlinkat_chk
// __readlink_chk
// readv
// realloc
// __realloc_hook
// realpath
// __realpath_chk
// reboot
// re_comp
// re_compile_fastmap
// re_compile_pattern
// recv
// __recv_chk
// recvfrom
// __recvfrom_chk
// recvmsg
// re_exec
// regcomp
// regerror
// regexec
// regfree
// __register_atfork
// register_printf_function
// registerrpc
// remap_file_pages
// re_match
// re_match_2
// remove
// removexattr
// remque
// rename
// renameat
// _res
// re_search
// re_search_2
// re_set_registers
// re_set_syntax
// _res_hconf
// __res_iclose
// __res_init
// __res_maybe_init
// __res_nclose
// __res_ninit
// __resp
// __res_randomid
// __res_state
// re_syntax_options
// revoke
// rewind
// rewinddir
// rexec
// rexec_af
// rexecoptions
// rindex
// rmdir
// rpc_createerr
// _rpc_dtablesize
// __rpc_thread_createerr
// __rpc_thread_svc_fdset
// __rpc_thread_svc_max_pollfd
// __rpc_thread_svc_pollfd
// rpmatch
// rresvport
// rresvport_af
// rtime
         // _rtld_global
         // _rtld_global_ro
// ruserok
// ruserok_af
// ruserpass
// sbrk
// __sbrk
// scalbn
// scalbnf
// scalbnl
// scandir
// scandir64
// scanf
// __sched_cpualloc
// __sched_cpucount
// __sched_cpufree
// sched_getaffinity
// sched_getcpu
// __sched_getparam
// sched_getparam
// __sched_get_priority_max
// sched_get_priority_max
// __sched_get_priority_min
// sched_get_priority_min
// __sched_getscheduler
// sched_getscheduler
// sched_rr_get_interval
// sched_setaffinity
// sched_setparam
// __sched_setscheduler
// sched_setscheduler
// __sched_yield
// sched_yield
// __secure_getenv
// seed48
// seed48_r
// seekdir
// select
// __select
// semctl
// semget
// semop
// semtimedop
// send
// __send
// sendfile
// sendfile64
// sendmsg
// sendto
// setaliasent
// setbuf
// setbuffer
// setcontext
// setdomainname
// setegid
// setenv
// _seterr_reply
// seteuid
// setfsent
// setfsgid
// setfsuid
// setgid
// setgrent
// setgroups
// sethostent
// sethostid
// sethostname
// setipv4sourcefilter
// setitimer
// setjmp
// _setjmp
// setlinebuf
// setlocale
// setlogin
// setlogmask
// setmntent
// __setmntent
// setnetent
// setnetgrent
// setpgid
// __setpgid
// setpgrp
// setpriority
// setprotoent
// setpwent
// setregid
// setresgid
// setresuid
// setreuid
// setrlimit
// setrlimit64
// setrpcent
// setservent
// setsid
// setsockopt
// setsourcefilter
// setspent
// setstate
// setstate_r
// settimeofday
// setttyent
// setuid
// setusershell
// setutent
// setutxent
// setvbuf
// setxattr
// sgetspent
// sgetspent_r
// shmat
// shmctl
// shmdt
// shmget
// shutdown
// sigaction
// __sigaction
// sigaddset
// __sigaddset
// sigaltstack
// sigandset
// sigblock
// sigdelset
// __sigdelset
// sigemptyset
// sigfillset
// siggetmask
// sighold
// sigignore
// siginterrupt
// sigisemptyset
// sigismember
// __sigismember
// siglongjmp
// signal
// signalfd
// __signbit
// __signbitf
// sigorset
// sigpause
// __sigpause
// sigpending
// sigprocmask
// sigqueue
// sigrelse
// sigreturn
// sigset
// __sigsetjmp
// sigsetmask
// sigstack
// sigsuspend
// __sigsuspend
// sigtimedwait
// sigvec
// sigwait
// sigwaitinfo
// sleep
// snprintf
// __snprintf_chk
// sockatmark
// socket
// socketpair
// splice
// sprintf
// __sprintf_chk
// sprofil
// srand
// srand48
// srand48_r
// srandom
// srandom_r
// sscanf
// ssignal
// sstk
GOM(__stack_chk_fail, vFE)
// statfs
// __statfs
// statfs64
// statvfs
// statvfs64
// stderr
// stdin
// stdout
// step
// stime
// stpcpy
// __stpcpy
// __stpcpy_chk
// __stpcpy_small
// stpncpy
// __stpncpy
// __stpncpy_chk
// strcasecmp
// __strcasecmp
// __strcasecmp_l
// strcasecmp_l
// strcasestr
// __strcasestr
// strcat
// __strcat_chk
// strchr
// strchrnul
// strcmp
// strcoll
// __strcoll_l
// strcoll_l
// strcpy
// __strcpy_chk
// __strcpy_small
// strcspn
// __strcspn_c1
// __strcspn_c2
// __strcspn_c3
// strdup
// __strdup
GO(strerror, pFv)
// strerror_l
// __strerror_r
// strerror_r
// strfmon
// __strfmon_l
// strfmon_l
// strfry
// strftime
// __strftime_l
// strftime_l
// strlen
// strncasecmp
// __strncasecmp_l
// strncasecmp_l
// strncat
// __strncat_chk
// strncmp
// strncpy
// __strncpy_chk
// strndup
// __strndup
// strnlen
// strpbrk
// __strpbrk_c2
// __strpbrk_c3
// strptime
// strptime_l
// strrchr
// strsep
// __strsep_1c
// __strsep_2c
// __strsep_3c
// __strsep_g
// strsignal
// strspn
// __strspn_c1
// __strspn_c2
// __strspn_c3
// strstr
// strtod
// __strtod_internal
// __strtod_l
// strtod_l
// strtof
// __strtof_internal
// __strtof_l
// strtof_l
// strtoimax
// strtok
// __strtok_r
// strtok_r
// __strtok_r_1c
GO(strtol, iFppi)
// strtold
// __strtold_internal
// __strtold_l
// strtold_l
// __strtol_internal
// strtoll
// __strtol_l
// strtol_l
// __strtoll_internal
// __strtoll_l
// strtoll_l
// strtoq
// strtoul
// __strtoul_internal
// strtoull
// __strtoul_l
// strtoul_l
// __strtoull_internal
// __strtoull_l
// strtoull_l
// strtoumax
// strtouq
// strverscmp
// __strverscmp
// strxfrm
// __strxfrm_l
// strxfrm_l
// stty
// svcauthdes_stats
// svcerr_auth
// svcerr_decode
// svcerr_noproc
// svcerr_noprog
// svcerr_progvers
// svcerr_systemerr
// svcerr_weakauth
// svc_exit
// svcfd_create
// svc_fdset
// svc_getreq
// svc_getreq_common
// svc_getreq_poll
// svc_getreqset
// svc_max_pollfd
// svc_pollfd
// svcraw_create
// svc_register
// svc_run
// svc_sendreply
// svctcp_create
// svcudp_bufcreate
// svcudp_create
// svcudp_enablecache
// svcunix_create
// svcunixfd_create
// svc_unregister
// swab
// swapcontext
// swapoff
// swapon
// swprintf
// __swprintf_chk
// swscanf
// symlink
// symlinkat
// sync
// sync_file_range
GOM(syscall, uFE)
// sysconf
// __sysconf
// sysctl
// __sysctl
// _sys_errlist
// sys_errlist
// sysinfo
// syslog
// __syslog_chk
// _sys_nerr
// sys_nerr
// sys_sigabbrev
// _sys_siglist
// sys_siglist
// system
// __sysv_signal
// sysv_signal
// tcdrain
// tcflow
// tcflush
// tcgetattr
// tcgetpgrp
// tcgetsid
// tcsendbreak
// tcsetattr
// tcsetpgrp
// tdelete
// tdestroy
// tee
// telldir
// tempnam
// textdomain
// tfind
// time
// timegm
// timelocal
// timerfd_create
// timerfd_gettime
// timerfd_settime
// times
// timezone
// __timezone
         // __tls_get_addr
// tmpfile
// tmpfile64
// tmpnam
// tmpnam_r
// toascii
// __toascii_l
// tolower
// _tolower
// __tolower_l
// tolower_l
// toupper
// _toupper
// __toupper_l
// toupper_l
// towctrans
// __towctrans
// __towctrans_l
// towctrans_l
// towlower
// __towlower_l
// towlower_l
// towupper
// __towupper_l
// towupper_l
// tr_break
// truncate
// truncate64
// tsearch
// ttyname
// ttyname_r
// __ttyname_r_chk
// ttyslot
// twalk
// tzname
// __tzname
// tzset
// ualarm
// __uflow
// ulckpwdf
// ulimit
// umask
// umount
// umount2
// uname
// __underflow
// ungetc
// ungetwc
// unlink
// unlinkat
// unlockpt
// unsetenv
// unshare
// updwtmp
// updwtmpx
// uselib
// uselocale
// __uselocale
// user2netname
// usleep
// ustat
// utime
// utimensat
// utimes
// utmpname
// utmpxname
// valloc
// vasprintf
// __vasprintf_chk
// vdprintf
// __vdprintf_chk
// verr
// verrx
// versionsort
// versionsort64
// vfork
// __vfork
// vfprintf
// __vfprintf_chk
// vfscanf
// __vfscanf
// vfwprintf
// __vfwprintf_chk
// vfwscanf
// vhangup
// vlimit
// vmsplice
// vprintf
// __vprintf_chk
// vscanf
// vsnprintf
// __vsnprintf
// __vsnprintf_chk
// vsprintf
// __vsprintf_chk
// vsscanf
// __vsscanf
// vswprintf
// __vswprintf_chk
// vswscanf
// vsyslog
// __vsyslog_chk
// vtimes
// vwarn
// vwarnx
// vwprintf
// __vwprintf_chk
// vwscanf
// wait
// __wait
// wait3
// wait4
// waitid
// waitpid
// __waitpid
// warn
// warnx
// wcpcpy
// __wcpcpy_chk
// wcpncpy
// __wcpncpy_chk
// wcrtomb
// __wcrtomb_chk
// wcscasecmp
// __wcscasecmp_l
// wcscasecmp_l
// wcscat
// __wcscat_chk
// wcschr
// wcschrnul
// wcscmp
// wcscoll
// __wcscoll_l
// wcscoll_l
// wcscpy
// __wcscpy_chk
// wcscspn
// wcsdup
// wcsftime
// __wcsftime_l
// wcsftime_l
// wcslen
// wcsncasecmp
// __wcsncasecmp_l
// wcsncasecmp_l
// wcsncat
// __wcsncat_chk
// wcsncmp
// wcsncpy
// __wcsncpy_chk
// wcsnlen
// wcsnrtombs
// __wcsnrtombs_chk
// wcspbrk
// wcsrchr
// wcsrtombs
// __wcsrtombs_chk
// wcsspn
// wcsstr
// wcstod
// __wcstod_internal
// __wcstod_l
// wcstod_l
// wcstof
// __wcstof_internal
// __wcstof_l
// wcstof_l
// wcstoimax
// wcstok
// wcstol
// wcstold
// __wcstold_internal
// __wcstold_l
// wcstold_l
// __wcstol_internal
// wcstoll
// __wcstol_l
// wcstol_l
// __wcstoll_internal
// __wcstoll_l
// wcstoll_l
// wcstombs
// __wcstombs_chk
// wcstoq
// wcstoul
// __wcstoul_internal
// wcstoull
// __wcstoul_l
// wcstoul_l
// __wcstoull_internal
// __wcstoull_l
// wcstoull_l
// wcstoumax
// wcstouq
// wcswcs
// wcswidth
// wcsxfrm
// __wcsxfrm_l
// wcsxfrm_l
// wctob
// wctomb
// __wctomb_chk
// wctrans
// __wctrans_l
// wctrans_l
// wctype
// __wctype_l
// wctype_l
// wcwidth
// wmemchr
// wmemcmp
// wmemcpy
// __wmemcpy_chk
// wmemmove
// __wmemmove_chk
// wmempcpy
// __wmempcpy_chk
// wmemset
// __wmemset_chk
// wordexp
// wordfree
// __woverflow
// wprintf
// __wprintf_chk
// write
// __write
// writev
// wscanf
// __wuflow
// __wunderflow
// xdecrypt
// xdr_accepted_reply
// xdr_array
// xdr_authdes_cred
// xdr_authdes_verf
// xdr_authunix_parms
// xdr_bool
// xdr_bytes
// xdr_callhdr
// xdr_callmsg
// xdr_char
// xdr_cryptkeyarg
// xdr_cryptkeyarg2
// xdr_cryptkeyres
// xdr_des_block
// xdr_double
// xdr_enum
// xdr_float
// xdr_free
// xdr_getcredres
// xdr_hyper
// xdr_int
// xdr_int16_t
// xdr_int32_t
// xdr_int64_t
// xdr_int8_t
// xdr_keybuf
// xdr_key_netstarg
// xdr_key_netstres
// xdr_keystatus
// xdr_long
// xdr_longlong_t
// xdrmem_create
// xdr_netnamestr
// xdr_netobj
// xdr_opaque
// xdr_opaque_auth
// xdr_pmap
// xdr_pmaplist
// xdr_pointer
// xdr_quad_t
// xdrrec_create
// xdrrec_endofrecord
// xdrrec_eof
// xdrrec_skiprecord
// xdr_reference
// xdr_rejected_reply
// xdr_replymsg
// xdr_rmtcall_args
// xdr_rmtcallres
// xdr_short
// xdr_sizeof
// xdrstdio_create
// xdr_string
// xdr_u_char
// xdr_u_hyper
// xdr_u_int
// xdr_uint16_t
// xdr_uint32_t
// xdr_uint64_t
// xdr_uint8_t
// xdr_u_long
// xdr_u_longlong_t
// xdr_union
// xdr_unixcred
// xdr_u_quad_t
// xdr_u_short
// xdr_vector
// xdr_void
// xdr_wrapstring
// xencrypt
// __xmknod
// __xmknodat
// __xpg_basename
// __xpg_sigpause
// __xpg_strerror_r
// xprt_register
// xprt_unregister
// __xstat
// __xstat64
END()

#else
#error Mmmm...
#endif