#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error Meh...
#endif

GO(alutInit,iFpp)
GO(alutInitWithoutContext,iFpp)
GO(alutExit,iFv)
GO(alutGetError,iFv)
GO(alutGetErrorString,pFi)
GO(alutCreateBufferFromFile,uFp)
GO(alutCreateBufferFromFileImage,uFpi)
GO(alutCreateBufferHelloWorld,uFv)
GO(alutCreateBufferWaveform,uFifff)
GO(alutLoadMemoryFromFile,pFpppp)
GO(alutLoadMemoryFromFileImage,pFpippp)
GO(alutLoadMemoryHelloWorld,pFppp)
GO(alutLoadMemoryWaveform,pFifffppp)
GO(alutGetMIMETypes,pFi)
GO(alutGetMajorVersion,iFv)
GO(alutGetMinorVersion,iFv)
GO(alutSleep,iFf)
GO(alutLoadWAVFile,vFppppp)
GO(alutLoadWAVMemory,vFppppp)
GO(alutLoadWAVFile,vFpppppp)
GO(alutLoadWAVMemory,vFpppppp)
GO(alutUnloadWAV,vFipii)