#if defined(GO) && defined(GOM) && defined(GO2) && defined(DATA)

// _fini
// _init
// SDL_abs
// SDL_acos
// SDL_acosf
// SDL_AddEventWatch
// SDL_AddHintCallback
// SDL_AddTimer
// SDL_AllocFormat
// SDL_AllocPalette
// SDL_AllocRW
// SDL_asin
// SDL_asinf
// SDL_atan
// SDL_atan2
// SDL_atan2f
// SDL_atanf
// SDL_atof
// SDL_atoi
// SDL_AtomicAdd
// SDL_AtomicCAS
// SDL_AtomicCASPtr
// SDL_AtomicGet
// SDL_AtomicGetPtr
// SDL_AtomicLock
// SDL_AtomicSet
// SDL_AtomicSetPtr
// SDL_AtomicTryLock
// SDL_AtomicUnlock
// SDL_AudioInit
// SDL_AudioQuit
// SDL_AudioStreamAvailable
// SDL_AudioStreamClear
// SDL_AudioStreamFlush
// SDL_AudioStreamGet
// SDL_AudioStreamPut
// SDL_BuildAudioCVT
// SDL_CalculateGammaRamp
// SDL_calloc
// SDL_CaptureMouse
// SDL_ceil
// SDL_ceilf
// SDL_ClearError
// SDL_ClearHints
// SDL_ClearQueuedAudio
// SDL_CloseAudio
// SDL_CloseAudioDevice
// SDL_ComposeCustomBlendMode
// SDL_CondBroadcast
// SDL_CondSignal
// SDL_CondWait
// SDL_CondWaitTimeout
// SDL_ConvertAudio
// SDL_ConvertPixels
// SDL_ConvertSurface
// SDL_ConvertSurfaceFormat
// SDL_copysign
// SDL_copysignf
// SDL_cos
// SDL_cosf
// SDL_CreateColorCursor
// SDL_CreateCond
// SDL_CreateCursor
// SDL_CreateMutex
// SDL_CreateRenderer
// SDL_CreateRGBSurface
// SDL_CreateRGBSurfaceFrom
// SDL_CreateRGBSurfaceWithFormat
// SDL_CreateRGBSurfaceWithFormatFrom
// SDL_CreateSemaphore
// SDL_CreateShapedWindow
// SDL_CreateSoftwareRenderer
// SDL_CreateSystemCursor
// SDL_CreateTexture
// SDL_CreateTextureFromSurface
// SDL_CreateThread
// SDL_CreateThreadWithStackSize
GO(SDL_CreateWindow, pFpiiiiu)
// SDL_CreateWindowAndRenderer
// SDL_CreateWindowFrom
GO(SDL_Delay, vFu)
// SDL_DelEventWatch
// SDL_DelHintCallback
// SDL_DequeueAudio
// SDL_DestroyCond
// SDL_DestroyMutex
// SDL_DestroyRenderer
// SDL_DestroySemaphore
// SDL_DestroyTexture
GO(SDL_DestroyWindow, vFp)
// SDL_DetachThread
// SDL_DisableScreenSaver
// SDL_DuplicateSurface
// SDL_DYNAPI_entry
// SDL_EnableScreenSaver
// SDL_EnclosePoints
// SDL_Error
GO(SDL_EventState, CFui)
// SDL_exp
// SDL_expf
// SDL_fabs
// SDL_fabsf
// SDL_FillRect
// SDL_FillRects
// SDL_FilterEvents
// SDL_floor
// SDL_floorf
// SDL_FlushEvent
// SDL_FlushEvents
// SDL_fmod
// SDL_fmodf
// SDL_free
// SDL_FreeAudioStream
// SDL_FreeCursor
// SDL_FreeFormat
// SDL_FreePalette
GOM(SDL_FreeRW, vFEp)
GO(SDL_FreeSurface, vFp)
// SDL_FreeWAV
// SDL_GameControllerAddMapping
GOM(SDL_GameControllerAddMappingsFromRW, iFEpi)
// SDL_GameControllerClose
// SDL_GameControllerEventState
// SDL_GameControllerFromInstanceID
// SDL_GameControllerGetAttached
// SDL_GameControllerGetAxis
// SDL_GameControllerGetAxisFromString
// SDL_GameControllerGetBindForAxis
// SDL_GameControllerGetBindForButton
// SDL_GameControllerGetButton
// SDL_GameControllerGetButtonFromString
// SDL_GameControllerGetJoystick
// SDL_GameControllerGetPlayerIndex
// SDL_GameControllerGetProduct
// SDL_GameControllerGetProductVersion
// SDL_GameControllerGetStringForAxis
// SDL_GameControllerGetStringForButton
// SDL_GameControllerGetVendor
// SDL_GameControllerMapping
// SDL_GameControllerMappingForDeviceIndex
// SDL_GameControllerMappingForGUID
// SDL_GameControllerMappingForIndex
// SDL_GameControllerName
// SDL_GameControllerNameForIndex
// SDL_GameControllerNumMappings
// SDL_GameControllerOpen
// SDL_GameControllerRumble
// SDL_GameControllerUpdate
// SDL_GetAssertionHandler
// SDL_GetAssertionReport
// SDL_GetAudioDeviceName
// SDL_GetAudioDeviceStatus
// SDL_GetAudioDriver
// SDL_GetAudioStatus
// SDL_GetBasePath
// SDL_GetClipboardText
// SDL_GetClipRect
// SDL_GetClosestDisplayMode
// SDL_GetColorKey
// SDL_GetCPUCacheLineSize
// SDL_GetCPUCount
// SDL_GetCurrentAudioDriver
GO(SDL_GetCurrentDisplayMode, iFip)
// SDL_GetCurrentVideoDriver
// SDL_GetCursor
// SDL_GetDefaultAssertionHandler
// SDL_GetDefaultCursor
// SDL_GetDesktopDisplayMode
// SDL_GetDisplayBounds
// SDL_GetDisplayDPI
// SDL_GetDisplayMode
// SDL_GetDisplayName
// SDL_GetDisplayOrientation
// SDL_GetDisplayUsableBounds
// SDL_getenv
GO(SDL_GetError, pFv)
// SDL_GetEventFilter
// SDL_GetGlobalMouseState
// SDL_GetGrabbedWindow
// SDL_GetHint
// SDL_GetHintBoolean
// SDL_GetKeyboardFocus
// SDL_GetKeyboardState
// SDL_GetKeyFromName
// SDL_GetKeyFromScancode
// SDL_GetKeyName
// SDL_GetMemoryFunctions
// SDL_GetModState
// SDL_GetMouseFocus
GO(SDL_GetMouseState, uFpp)
// SDL_GetNumAllocations
// SDL_GetNumAudioDevices
// SDL_GetNumAudioDrivers
// SDL_GetNumDisplayModes
// SDL_GetNumRenderDrivers
// SDL_GetNumTouchDevices
// SDL_GetNumTouchFingers
// SDL_GetNumVideoDisplays
// SDL_GetNumVideoDrivers
// SDL_GetPerformanceCounter
// SDL_GetPerformanceFrequency
// SDL_GetPixelFormatName
// SDL_GetPlatform
// SDL_GetPowerInfo
// SDL_GetPrefPath
// SDL_GetQueuedAudioSize
// SDL_GetRelativeMouseMode
// SDL_GetRelativeMouseState
// SDL_GetRenderDrawBlendMode
// SDL_GetRenderDrawColor
// SDL_GetRenderDriverInfo
// SDL_GetRenderer
// SDL_GetRendererInfo
// SDL_GetRendererOutputSize
// SDL_GetRenderTarget
// SDL_GetRevision
// SDL_GetRevisionNumber
// SDL_GetRGB
// SDL_GetRGBA
// SDL_GetScancodeFromKey
// SDL_GetScancodeFromName
// SDL_GetScancodeName
// SDL_GetShapedWindowMode
// SDL_GetSurfaceAlphaMod
// SDL_GetSurfaceBlendMode
// SDL_GetSurfaceColorMod
// SDL_GetSystemRAM
// SDL_GetTextureAlphaMod
// SDL_GetTextureBlendMode
// SDL_GetTextureColorMod
// SDL_GetThreadID
// SDL_GetThreadName
GO(SDL_GetTicks, uFv)
// SDL_GetTouchDevice
// SDL_GetTouchDeviceType
// SDL_GetTouchFinger
// SDL_GetVersion
// SDL_GetVideoDriver
// SDL_GetWindowBordersSize
// SDL_GetWindowBrightness
// SDL_GetWindowData
// SDL_GetWindowDisplayIndex
// SDL_GetWindowDisplayMode
// SDL_GetWindowFlags
// SDL_GetWindowFromID
// SDL_GetWindowGammaRamp
// SDL_GetWindowGrab
// SDL_GetWindowID
// SDL_GetWindowMaximumSize
// SDL_GetWindowMinimumSize
// SDL_GetWindowOpacity
// SDL_GetWindowPixelFormat
// SDL_GetWindowPosition
// SDL_GetWindowSize
// SDL_GetWindowSurface
// SDL_GetWindowTitle
// SDL_GetWindowWMInfo
// SDL_GetYUVConversionMode
// SDL_GetYUVConversionModeForResolution
// SDL_GL_BindTexture
GO(SDL_GL_CreateContext, pFp)
GO(SDL_GL_DeleteContext, vFp)
// SDL_GL_ExtensionSupported
// SDL_GL_GetAttribute
// SDL_GL_GetCurrentContext
// SDL_GL_GetCurrentWindow
// SDL_GL_GetDrawableSize
// SDL_GL_GetProcAddress
// SDL_GL_GetSwapInterval
// SDL_GL_LoadLibrary
GO(SDL_GL_MakeCurrent, iFpp)
// SDL_GL_ResetAttributes
GO(SDL_GL_SetAttribute, iFui)
GO(SDL_GL_SetSwapInterval, iFi)
GO(SDL_GL_SwapWindow, vFp)
// SDL_GL_UnbindTexture
// SDL_GL_UnloadLibrary
// SDL_HapticClose
// SDL_HapticDestroyEffect
// SDL_HapticEffectSupported
// SDL_HapticGetEffectStatus
// SDL_HapticIndex
// SDL_HapticName
// SDL_HapticNewEffect
// SDL_HapticNumAxes
// SDL_HapticNumEffects
// SDL_HapticNumEffectsPlaying
// SDL_HapticOpen
// SDL_HapticOpened
// SDL_HapticOpenFromJoystick
// SDL_HapticOpenFromMouse
// SDL_HapticPause
// SDL_HapticQuery
// SDL_HapticRumbleInit
// SDL_HapticRumblePlay
// SDL_HapticRumbleStop
// SDL_HapticRumbleSupported
// SDL_HapticRunEffect
// SDL_HapticSetAutocenter
// SDL_HapticSetGain
// SDL_HapticStopAll
// SDL_HapticStopEffect
// SDL_HapticUnpause
// SDL_HapticUpdateEffect
GOM(SDL_Has3DNow, iFv)
GOM(SDL_HasAltiVec, iFv)
GOM(SDL_HasAVX, iFv)
GOM(SDL_HasAVX2, iFv)
GOM(SDL_HasAVX512F, iFv)
GO(SDL_HasClipboardText, iFv)
GO(SDL_HasColorKey, iFv)
GO(SDL_HasEvent, iFv)
GO(SDL_HasEvents, iFv)
GO(SDL_HasIntersection, iFv)
GOM(SDL_HasMMX, iFv)
GOM(SDL_HasNEON, iFv)
GOM(SDL_HasRDTSC, iFv)
GO(SDL_HasScreenKeyboardSupport, iFv)
GOM(SDL_HasSSE, iFv)
GOM(SDL_HasSSE2, iFv)
GOM(SDL_HasSSE3, iFv)
GOM(SDL_HasSSE41, iFv)
GOM(SDL_HasSSE42, iFv)
// SDL_HideWindow
// SDL_iconv
// SDL_iconv_close
// SDL_iconv_open
// SDL_iconv_string
GO(SDL_Init, iFu)
GO(SDL_InitSubSystem, iFu)
// SDL_IntersectRect
// SDL_IntersectRectAndLine
// SDL_isdigit
// SDL_IsGameController
// SDL_IsScreenKeyboardShown
// SDL_IsScreenSaverEnabled
// SDL_IsShapedWindow
// SDL_isspace
// SDL_IsTablet
// SDL_IsTextInputActive
// SDL_itoa
// SDL_JoystickClose
// SDL_JoystickCurrentPowerLevel
// SDL_JoystickEventState
// SDL_JoystickFromInstanceID
// SDL_JoystickGetAttached
// SDL_JoystickGetAxis
// SDL_JoystickGetAxisInitialState
// SDL_JoystickGetBall
// SDL_JoystickGetButton
// SDL_JoystickGetDeviceGUID
// SDL_JoystickGetDeviceInstanceID
// SDL_JoystickGetDevicePlayerIndex
// SDL_JoystickGetDeviceProduct
// SDL_JoystickGetDeviceProductVersion
// SDL_JoystickGetDeviceType
// SDL_JoystickGetDeviceVendor
// SDL_JoystickGetGUID
// SDL_JoystickGetGUIDFromString
// SDL_JoystickGetGUIDString
// SDL_JoystickGetHat
// SDL_JoystickGetPlayerIndex
// SDL_JoystickGetProduct
// SDL_JoystickGetProductVersion
// SDL_JoystickGetType
// SDL_JoystickGetVendor
// SDL_JoystickInstanceID
// SDL_JoystickIsHaptic
// SDL_JoystickName
// SDL_JoystickNameForIndex
// SDL_JoystickNumAxes
// SDL_JoystickNumBalls
// SDL_JoystickNumButtons
// SDL_JoystickNumHats
// SDL_JoystickOpen
// SDL_JoystickRumble
// SDL_JoystickUpdate
// SDL_LinuxSetThreadPriority
// SDL_lltoa
GOM(SDL_LoadBMP_RW, pFEpi)
// SDL_LoadDollarTemplates
GOM(SDL_LoadFile_RW, pFEppi)
// SDL_LoadFunction
// SDL_LoadObject
GOM(SDL_LoadWAV_RW, pFEpippp)
// SDL_LockAudio
// SDL_LockAudioDevice
// SDL_LockJoysticks
// SDL_LockMutex
// SDL_LockSurface
// SDL_LockTexture
// SDL_log
// SDL_Log
// SDL_log10
// SDL_log10f
// SDL_LogCritical
// SDL_LogDebug
// SDL_LogError
// SDL_logf
// SDL_LogGetOutputFunction
// SDL_LogGetPriority
// SDL_LogInfo
// SDL_LogMessage
// SDL_LogMessageV
// SDL_LogResetPriorities
// SDL_LogSetAllPriority
// SDL_LogSetOutputFunction
// SDL_LogSetPriority
// SDL_LogVerbose
// SDL_LogWarn
// SDL_LowerBlit
// SDL_LowerBlitScaled
// SDL_ltoa
// SDL_malloc
// SDL_MapRGB
// SDL_MapRGBA
// SDL_MasksToPixelFormatEnum
// SDL_MaximizeWindow
// SDL_memcmp
// SDL_memcpy
// SDL_memmove
// SDL_MemoryBarrierAcquireFunction
// SDL_MemoryBarrierReleaseFunction
// SDL_memset
// SDL_MinimizeWindow
// SDL_MixAudio
// SDL_MixAudioFormat
// SDL_MouseIsHaptic
// SDL_NewAudioStream
// SDL_NumHaptics
// SDL_NumJoysticks
// SDL_NumSensors
GOM(SDL_OpenAudio, iFEpp)
// SDL_OpenAudioDevice
// SDL_PauseAudio
// SDL_PauseAudioDevice
// SDL_PeepEvents
// SDL_PixelFormatEnumToMasks
GO(SDL_PollEvent, iFp)
// SDL_pow
// SDL_powf
GO(SDL_PumpEvents, vFv)
// SDL_PushEvent
// SDL_qsort
// SDL_QueryTexture
// SDL_QueueAudio
GO(SDL_Quit, vFv)
// SDL_QuitSubSystem
// SDL_RaiseWindow
GOM(SDL_ReadBE16, uFp)
GOM(SDL_ReadBE32, uFp)
GOM(SDL_ReadBE64, UFp)
GOM(SDL_ReadLE16, uFp)
GOM(SDL_ReadLE32, uFp)
GOM(SDL_ReadLE64, UFp)
GOM(SDL_ReadU8, uFp)
// SDL_realloc
// SDL_RecordGesture
// SDL_RegisterEvents
// SDL_RemoveTimer
// SDL_RenderClear
// SDL_RenderCopy
// SDL_RenderCopyEx
// SDL_RenderCopyExF
// SDL_RenderCopyF
// SDL_RenderDrawLine
// SDL_RenderDrawLineF
// SDL_RenderDrawLines
// SDL_RenderDrawLinesF
// SDL_RenderDrawPoint
// SDL_RenderDrawPointF
// SDL_RenderDrawPoints
// SDL_RenderDrawPointsF
// SDL_RenderDrawRect
// SDL_RenderDrawRectF
// SDL_RenderDrawRects
// SDL_RenderDrawRectsF
// SDL_RenderFillRect
// SDL_RenderFillRectF
// SDL_RenderFillRects
// SDL_RenderFillRectsF
// SDL_RenderFlush
// SDL_RenderGetClipRect
// SDL_RenderGetIntegerScale
// SDL_RenderGetLogicalSize
// SDL_RenderGetMetalCommandEncoder
// SDL_RenderGetMetalLayer
// SDL_RenderGetScale
// SDL_RenderGetViewport
// SDL_RenderIsClipEnabled
// SDL_RenderPresent
// SDL_RenderReadPixels
// SDL_RenderSetClipRect
// SDL_RenderSetIntegerScale
// SDL_RenderSetLogicalSize
// SDL_RenderSetScale
// SDL_RenderSetViewport
// SDL_RenderTargetSupported
// SDL_ReportAssertion
// SDL_ResetAssertionReport
// SDL_RestoreWindow
GOM(SDL_RWFromConstMem, pFEpi)
GOM(SDL_RWFromFP, pFEpi)
GOM(SDL_RWFromFile, pFEpp)
GOM(SDL_RWFromMem, pFEpi)
// SDL_SaveAllDollarTemplates
GOM(SDL_SaveBMP_RW, iFEppi)
// SDL_SaveDollarTemplate
// SDL_scalbn
// SDL_scalbnf
// SDL_SemPost
// SDL_SemTryWait
// SDL_SemValue
// SDL_SemWait
// SDL_SemWaitTimeout
// SDL_SensorClose
// SDL_SensorFromInstanceID
// SDL_SensorGetData
// SDL_SensorGetDeviceInstanceID
// SDL_SensorGetDeviceName
// SDL_SensorGetDeviceNonPortableType
// SDL_SensorGetDeviceType
// SDL_SensorGetInstanceID
// SDL_SensorGetName
// SDL_SensorGetNonPortableType
// SDL_SensorGetType
// SDL_SensorOpen
// SDL_SensorUpdate
// SDL_SetAssertionHandler
// SDL_SetClipboardText
// SDL_SetClipRect
// SDL_SetColorKey
// SDL_SetCursor
// SDL_setenv
GO(SDL_SetError, iFppppp)    // it use ..., so putarbitrary  4 args
// SDL_SetEventFilter
// SDL_SetHint
// SDL_SetHintWithPriority
// SDL_SetMainReady
// SDL_SetMemoryFunctions
// SDL_SetModState
// SDL_SetPaletteColors
// SDL_SetPixelFormatPalette
// SDL_SetRelativeMouseMode
// SDL_SetRenderDrawBlendMode
// SDL_SetRenderDrawColor
// SDL_SetRenderTarget
// SDL_SetSurfaceAlphaMod
// SDL_SetSurfaceBlendMode
// SDL_SetSurfaceColorMod
// SDL_SetSurfacePalette
// SDL_SetSurfaceRLE
// SDL_SetTextInputRect
// SDL_SetTextureAlphaMod
// SDL_SetTextureBlendMode
// SDL_SetTextureColorMod
// SDL_SetThreadPriority
// SDL_SetWindowBordered
// SDL_SetWindowBrightness
// SDL_SetWindowData
// SDL_SetWindowDisplayMode
GO(SDL_SetWindowFullscreen, iFpu)
// SDL_SetWindowGammaRamp
// SDL_SetWindowGrab
// SDL_SetWindowHitTest
GO(SDL_SetWindowIcon, vFpp)
// SDL_SetWindowInputFocus
// SDL_SetWindowMaximumSize
// SDL_SetWindowMinimumSize
// SDL_SetWindowModalFor
// SDL_SetWindowOpacity
GO(SDL_SetWindowPosition, vFpii)
// SDL_SetWindowResizable
// SDL_SetWindowShape
GO(SDL_SetWindowSize, vFpii)
// SDL_SetWindowTitle
// SDL_SetYUVConversionMode
GO(SDL_ShowCursor, iFi)
// SDL_ShowMessageBox
// SDL_ShowSimpleMessageBox
// SDL_ShowWindow
// SDL_sin
// SDL_sinf
// SDL_snprintf
// SDL_SoftStretch
// SDL_sqrt
// SDL_sqrtf
// SDL_sscanf
GO(SDL_StartTextInput, vFv)
GO(SDL_StopTextInput, vFv)
// SDL_strcasecmp
// SDL_strchr
// SDL_strcmp
// SDL_strdup
// SDL_strlcat
// SDL_strlcpy
// SDL_strlen
// SDL_strlwr
// SDL_strncasecmp
// SDL_strncmp
// SDL_strrchr
// SDL_strrev
// SDL_strstr
// SDL_strtod
// SDL_strtol
// SDL_strtoll
// SDL_strtoul
// SDL_strtoull
// SDL_strupr
// SDL_tan
// SDL_tanf
// SDL_ThreadID
// SDL_TLSCreate
// SDL_TLSGet
// SDL_TLSSet
// SDL_tolower
// SDL_toupper
// SDL_TryLockMutex
// SDL_uitoa
// SDL_ulltoa
// SDL_ultoa
// SDL_UnionRect
// SDL_UnloadObject
// SDL_UnlockAudio
// SDL_UnlockAudioDevice
// SDL_UnlockJoysticks
// SDL_UnlockMutex
// SDL_UnlockSurface
// SDL_UnlockTexture
// SDL_UpdateTexture
// SDL_UpdateWindowSurface
// SDL_UpdateWindowSurfaceRects
// SDL_UpdateYUVTexture
// SDL_UpperBlit
// SDL_UpperBlitScaled
// SDL_utf8strlcpy
// SDL_utf8strlen
// SDL_VideoInit
// SDL_VideoQuit
// SDL_vsnprintf
// SDL_vsscanf
// SDL_Vulkan_CreateSurface
// SDL_Vulkan_GetDrawableSize
// SDL_Vulkan_GetInstanceExtensions
// SDL_Vulkan_GetVkGetInstanceProcAddr
// SDL_Vulkan_LoadLibrary
// SDL_Vulkan_UnloadLibrary
// SDL_WaitEvent
// SDL_WaitEventTimeout
// SDL_WaitThread
// SDL_WarpMouseGlobal
GO(SDL_WarpMouseInWindow, vFpii)
// SDL_WasInit
// SDL_wcscmp
// SDL_wcsdup
// SDL_wcslcat
// SDL_wcslcpy
// SDL_wcslen
GOM(SDL_WriteBE16, uFEpW)
GOM(SDL_WriteBE32, uFEpu)
GOM(SDL_WriteBE64, uFEpU)
GOM(SDL_WriteLE16, uFEpW)
GOM(SDL_WriteLE32, uFEpu)
GOM(SDL_WriteLE64, uFEpU)
GOM(SDL_WriteU8, uFEpu)

GO(SDL_doesntexist, IFpIi)

#endif